CREATE TABLE `participant_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`organizationName` varchar(255) NOT NULL,
	`businessType` enum('bank','payment_service_provider','merchant','fintech') NOT NULL,
	`registrationNumber` varchar(128),
	`taxId` varchar(128),
	`website` varchar(512),
	`description` text,
	`contactName` varchar(255) NOT NULL,
	`contactEmail` varchar(320) NOT NULL,
	`contactPhone` varchar(32),
	`country` varchar(64) NOT NULL,
	`address` text NOT NULL,
	`city` varchar(128) NOT NULL,
	`postalCode` varchar(32),
	`settlementCurrency` varchar(3) NOT NULL,
	`settlementBankName` varchar(255),
	`settlementAccountNumber` varchar(128),
	`status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
	`reviewNotes` text,
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `participant_applications_id` PRIMARY KEY(`id`)
);
