FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY ussd/ ./ussd/
COPY shared/ ./shared/
RUN CGO_ENABLED=0 GOOS=linux go build -o /ussd-service ./ussd/

FROM alpine:3.19
RUN apk add --no-cache wget
COPY --from=builder /ussd-service /ussd-service
EXPOSE 8132
CMD ["/ussd-service"]
