FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod .
RUN go mod download
COPY fluvio/ fluvio/
RUN CGO_ENABLED=0 GOOS=linux go build -o /fluvio-service ./fluvio/cmd/main.go

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
COPY --from=builder /fluvio-service /fluvio-service
EXPOSE 8086
CMD ["/fluvio-service"]
