FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod .
RUN go mod download
COPY tigerbeetle/ tigerbeetle/
RUN CGO_ENABLED=0 GOOS=linux go build -o /tigerbeetle-service ./tigerbeetle/cmd/main.go

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
COPY --from=builder /tigerbeetle-service /tigerbeetle-service
EXPOSE 8083
CMD ["/tigerbeetle-service"]
