FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod .
RUN go mod download
COPY kafka/ kafka/
RUN CGO_ENABLED=0 GOOS=linux go build -o /kafka-service ./kafka/cmd/main.go

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
COPY --from=builder /kafka-service /kafka-service
EXPOSE 8081
CMD ["/kafka-service"]
