FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY sms/ ./sms/
COPY shared/ ./shared/
RUN CGO_ENABLED=0 GOOS=linux go build -o /sms-service ./sms/

FROM alpine:3.19
RUN apk add --no-cache wget
COPY --from=builder /sms-service /sms-service
EXPOSE 8133
CMD ["/sms-service"]
