FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY go.mod .
RUN go mod download
COPY apisix/ apisix/
RUN CGO_ENABLED=0 GOOS=linux go build -o /apisix-service ./apisix/cmd/main.go

FROM alpine:3.19
RUN apk --no-cache add ca-certificates
COPY --from=builder /apisix-service /apisix-service
EXPOSE 8084
CMD ["/apisix-service"]
