package enhancements

import (
	"fmt"
	"sync"
	"time"
)

// TierLevel represents participant subscription tier
type TierLevel string

const (
	TierStarter    TierLevel = "starter"
	TierGrowth     TierLevel = "growth"
	TierEnterprise TierLevel = "enterprise"
	TierPremium    TierLevel = "premium"
)

// TierCriteria defines the requirements for each tier
type TierCriteria struct {
	Tier                   TierLevel     `json:"tier"`
	MinMonthlyVolumeNGN    float64       `json:"minMonthlyVolumeNgn"`
	MinMonthsOnPlatform    int           `json:"minMonthsOnPlatform"`
	MaxSanctionsBlocks90d  int           `json:"maxSanctionsBlocks90d"`
	MinSuccessRate         float64       `json:"minSuccessRate"`       // 0-1
	MinPrefundConsistency  float64       `json:"minPrefundConsistency"` // % of time above minimum balance
	MonthlyFeeUSD          float64       `json:"monthlyFeeUsd"`
	TransactionFeeNGN      float64       `json:"transactionFeeNgn"`
	FXSpreadDiscount       float64       `json:"fxSpreadDiscount"`     // % reduction from base spread
	MaxCorridors           int           `json:"maxCorridors"`
}

// ParticipantMetrics captures a participant's performance for tier evaluation
type ParticipantMetrics struct {
	ParticipantID        int       `json:"participantId"`
	MonthlyVolumeNGN     float64   `json:"monthlyVolumeNgn"`
	AvgMonthlyVolume3Mo  float64   `json:"avgMonthlyVolume3Mo"`
	MonthsOnPlatform     int       `json:"monthsOnPlatform"`
	SanctionsBlocks90d   int       `json:"sanctionsBlocks90d"`
	TransferSuccessRate  float64   `json:"transferSuccessRate"`
	PrefundConsistency   float64   `json:"prefundConsistency"`
	TotalTransfers       int       `json:"totalTransfers"`
	ActiveCorridors      int       `json:"activeCorridors"`
	JoinedAt             time.Time `json:"joinedAt"`
	LastEvaluated        time.Time `json:"lastEvaluated"`
}

// TierChangeRequest represents a pending or completed tier transition
type TierChangeRequest struct {
	ID              string    `json:"id"`
	ParticipantID   int       `json:"participantId"`
	CurrentTier     TierLevel `json:"currentTier"`
	ProposedTier    TierLevel `json:"proposedTier"`
	Reason          string    `json:"reason"`
	AutoGenerated   bool      `json:"autoGenerated"` // true = system-triggered, false = manual request
	Status          string    `json:"status"`         // pending, approved, rejected, applied
	EvaluatedMetrics ParticipantMetrics `json:"evaluatedMetrics"`
	CreatedAt       time.Time `json:"createdAt"`
	ReviewedAt      *time.Time `json:"reviewedAt,omitempty"`
	ReviewedBy      string    `json:"reviewedBy,omitempty"`
	AppliedAt       *time.Time `json:"appliedAt,omitempty"`
}

// TierDeterminationService manages automatic and manual tier evaluation
type TierDeterminationService struct {
	mu             sync.RWMutex
	criteria       map[TierLevel]TierCriteria
	currentTiers   map[int]TierLevel       // participantID → current tier
	metrics        map[int]*ParticipantMetrics
	changeRequests []TierChangeRequest
}

// NewTierDeterminationService creates a tier service with Nigerian market defaults
func NewTierDeterminationService() *TierDeterminationService {
	return &TierDeterminationService{
		criteria: map[TierLevel]TierCriteria{
			TierStarter: {
				Tier:                  TierStarter,
				MinMonthlyVolumeNGN:   0,
				MinMonthsOnPlatform:   0,
				MaxSanctionsBlocks90d: 999, // no limit for starter
				MinSuccessRate:        0,
				MinPrefundConsistency: 0,
				MonthlyFeeUSD:        200,
				TransactionFeeNGN:    1500,
				FXSpreadDiscount:     0,
				MaxCorridors:         3,
			},
			TierGrowth: {
				Tier:                  TierGrowth,
				MinMonthlyVolumeNGN:   1_000_000_000, // ₦1B
				MinMonthsOnPlatform:   3,
				MaxSanctionsBlocks90d: 2,
				MinSuccessRate:        0.95,
				MinPrefundConsistency: 0.80,
				MonthlyFeeUSD:        500,
				TransactionFeeNGN:    1000,
				FXSpreadDiscount:     0.10, // 10% discount
				MaxCorridors:         7,
			},
			TierEnterprise: {
				Tier:                  TierEnterprise,
				MinMonthlyVolumeNGN:   5_000_000_000, // ₦5B
				MinMonthsOnPlatform:   6,
				MaxSanctionsBlocks90d: 1,
				MinSuccessRate:        0.97,
				MinPrefundConsistency: 0.90,
				MonthlyFeeUSD:        2000,
				TransactionFeeNGN:    500,
				FXSpreadDiscount:     0.25, // 25% discount
				MaxCorridors:         13,
			},
			TierPremium: {
				Tier:                  TierPremium,
				MinMonthlyVolumeNGN:   10_000_000_000, // ₦10B
				MinMonthsOnPlatform:   12,
				MaxSanctionsBlocks90d: 0,
				MinSuccessRate:        0.99,
				MinPrefundConsistency: 0.95,
				MonthlyFeeUSD:        5000,
				TransactionFeeNGN:    250,
				FXSpreadDiscount:     0.40, // 40% discount
				MaxCorridors:         13,
			},
		},
		currentTiers:   make(map[int]TierLevel),
		metrics:        make(map[int]*ParticipantMetrics),
		changeRequests: make([]TierChangeRequest, 0),
	}
}

// SetCurrentTier sets a participant's current tier
func (ts *TierDeterminationService) SetCurrentTier(participantID int, tier TierLevel) {
	ts.mu.Lock()
	defer ts.mu.Unlock()
	ts.currentTiers[participantID] = tier
}

// UpdateMetrics ingests latest performance metrics for a participant
func (ts *TierDeterminationService) UpdateMetrics(metrics ParticipantMetrics) {
	ts.mu.Lock()
	defer ts.mu.Unlock()
	metrics.LastEvaluated = time.Now()
	ts.metrics[metrics.ParticipantID] = &metrics
}

// EvaluateTier determines the appropriate tier for a participant based on metrics
func (ts *TierDeterminationService) EvaluateTier(participantID int) *TierChangeRequest {
	ts.mu.Lock()
	defer ts.mu.Unlock()

	metrics, hasMetrics := ts.metrics[participantID]
	if !hasMetrics {
		return nil
	}

	currentTier, hasTier := ts.currentTiers[participantID]
	if !hasTier {
		currentTier = TierStarter
	}

	// Evaluate from highest tier down to find the best match
	tiers := []TierLevel{TierPremium, TierEnterprise, TierGrowth, TierStarter}
	eligibleTier := TierStarter

	for _, tier := range tiers {
		criteria := ts.criteria[tier]
		if ts.meetsCriteria(metrics, criteria) {
			eligibleTier = tier
			break
		}
	}

	if eligibleTier == currentTier {
		return nil // no change needed
	}

	direction := "upgrade"
	if tierRank(eligibleTier) < tierRank(currentTier) {
		direction = "downgrade"
	}

	reason := fmt.Sprintf("Auto-evaluated: %s from %s to %s. Volume: ₦%.0fM/mo, Success: %.1f%%, Months: %d, Sanctions blocks: %d",
		direction, currentTier, eligibleTier,
		metrics.MonthlyVolumeNGN/1_000_000,
		metrics.TransferSuccessRate*100,
		metrics.MonthsOnPlatform,
		metrics.SanctionsBlocks90d,
	)

	request := TierChangeRequest{
		ID:               fmt.Sprintf("tier-%d-%d", participantID, time.Now().UnixNano()),
		ParticipantID:    participantID,
		CurrentTier:      currentTier,
		ProposedTier:     eligibleTier,
		Reason:           reason,
		AutoGenerated:    true,
		Status:           "pending",
		EvaluatedMetrics: *metrics,
		CreatedAt:        time.Now(),
	}

	ts.changeRequests = append(ts.changeRequests, request)
	return &request
}

// ApproveTierChange approves a pending tier change request
func (ts *TierDeterminationService) ApproveTierChange(requestID string, reviewedBy string) bool {
	ts.mu.Lock()
	defer ts.mu.Unlock()

	for i := range ts.changeRequests {
		if ts.changeRequests[i].ID == requestID && ts.changeRequests[i].Status == "pending" {
			now := time.Now()
			ts.changeRequests[i].Status = "approved"
			ts.changeRequests[i].ReviewedAt = &now
			ts.changeRequests[i].ReviewedBy = reviewedBy
			ts.changeRequests[i].AppliedAt = &now
			ts.currentTiers[ts.changeRequests[i].ParticipantID] = ts.changeRequests[i].ProposedTier
			return true
		}
	}
	return false
}

// RejectTierChange rejects a pending tier change request
func (ts *TierDeterminationService) RejectTierChange(requestID string, reviewedBy string) bool {
	ts.mu.Lock()
	defer ts.mu.Unlock()

	for i := range ts.changeRequests {
		if ts.changeRequests[i].ID == requestID && ts.changeRequests[i].Status == "pending" {
			now := time.Now()
			ts.changeRequests[i].Status = "rejected"
			ts.changeRequests[i].ReviewedAt = &now
			ts.changeRequests[i].ReviewedBy = reviewedBy
			return true
		}
	}
	return false
}

// GetPendingChanges returns all pending tier change requests
func (ts *TierDeterminationService) GetPendingChanges() []TierChangeRequest {
	ts.mu.RLock()
	defer ts.mu.RUnlock()

	var pending []TierChangeRequest
	for _, r := range ts.changeRequests {
		if r.Status == "pending" {
			pending = append(pending, r)
		}
	}
	return pending
}

// GetTierCriteria returns the criteria for a specific tier
func (ts *TierDeterminationService) GetTierCriteria(tier TierLevel) (TierCriteria, bool) {
	ts.mu.RLock()
	defer ts.mu.RUnlock()
	c, ok := ts.criteria[tier]
	return c, ok
}

// GetParticipantTier returns a participant's current tier
func (ts *TierDeterminationService) GetParticipantTier(participantID int) TierLevel {
	ts.mu.RLock()
	defer ts.mu.RUnlock()
	if tier, ok := ts.currentTiers[participantID]; ok {
		return tier
	}
	return TierStarter
}

func (ts *TierDeterminationService) meetsCriteria(metrics *ParticipantMetrics, criteria TierCriteria) bool {
	if metrics.AvgMonthlyVolume3Mo < criteria.MinMonthlyVolumeNGN {
		return false
	}
	if metrics.MonthsOnPlatform < criteria.MinMonthsOnPlatform {
		return false
	}
	if metrics.SanctionsBlocks90d > criteria.MaxSanctionsBlocks90d {
		return false
	}
	if metrics.TransferSuccessRate < criteria.MinSuccessRate {
		return false
	}
	if metrics.PrefundConsistency < criteria.MinPrefundConsistency {
		return false
	}
	return true
}

func tierRank(tier TierLevel) int {
	switch tier {
	case TierStarter:
		return 0
	case TierGrowth:
		return 1
	case TierEnterprise:
		return 2
	case TierPremium:
		return 3
	default:
		return 0
	}
}
