package main
import ("encoding/json";"fmt";"net/http";"os")
func envOr(k,d string)string{if v:=os.Getenv(k);v!=""{return v};return d}
var mw=map[string]interface{}{"kafka":map[string]interface{}{"broker":envOr("KAFKA_BROKER","localhost:9092"),"topics":[]string{"bureau.crc-checked","bureau.firstcentral-checked","bureau.tin-verified","bureau.credit-score"}},"dapr":map[string]interface{}{"app_id":"multi-bureau-verification-go"},"fluvio":map[string]interface{}{"url":envOr("FLUVIO_URL","localhost:9003")},"temporal":map[string]interface{}{"url":envOr("TEMPORAL_URL","localhost:7233"),"namespace":"bureau-verification"},"postgres":map[string]interface{}{"url":envOr("DATABASE_URL","postgresql://ndsep_user:ndsep_secure_2026@localhost:5432/ndsep_db"),"tables":[]string{"bureau_checks","credit_scores","tin_verifications"}},"keycloak":map[string]interface{}{"url":envOr("KEYCLOAK_URL","http://localhost:8080"),"realm":"54bank"},"permify":map[string]interface{}{"url":envOr("PERMIFY_URL","http://localhost:3476")},"redis":map[string]interface{}{"url":envOr("REDIS_URL","redis://localhost:6379")},"mojaloop":map[string]interface{}{"url":envOr("MOJALOOP_URL","http://localhost:3002")},"opensearch":map[string]interface{}{"url":envOr("OPENSEARCH_URL","http://localhost:9200")},"openappsec":map[string]interface{}{"url":envOr("OPENAPPSEC_URL","http://localhost:4000")},"apisix":map[string]interface{}{"url":envOr("APISIX_URL","http://localhost:9080")},"tigerbeetle":map[string]interface{}{"url":envOr("TIGERBEETLE_URL","localhost:3000")},"lakehouse":map[string]interface{}{"url":envOr("LAKEHOUSE_URL","http://localhost:8181")}}
type BureauCheck struct{ID string`json:"id"`;CustomerID string`json:"customerId"`;Bureau string`json:"bureau"`;CreditScore int`json:"creditScore"`;RiskGrade string`json:"riskGrade"`;ActiveLoans int`json:"activeLoans"`;DefaultHistory bool`json:"defaultHistory"`;CheckedAt string`json:"checkedAt"`;ResponseTime int`json:"responseTimeMs"`}
type TINVerification struct{ID string`json:"id"`;CompanyName string`json:"companyName"`;TIN string`json:"tin"`;FIRSStatus string`json:"firsStatus"`;TaxClearanceValid bool`json:"taxClearanceValid"`;LastFilingYear int`json:"lastFilingYear"`;VerifiedAt string`json:"verifiedAt"`}
var bureauChecks=[]BureauCheck{{ID:"BC-001",CustomerID:"CUS-1045",Bureau:"CRC",CreditScore:720,RiskGrade:"A",ActiveLoans:1,DefaultHistory:false,CheckedAt:"2026-05-12T10:00:00Z",ResponseTime:850},{ID:"BC-002",CustomerID:"CUS-1045",Bureau:"FirstCentral",CreditScore:715,RiskGrade:"A",ActiveLoans:1,DefaultHistory:false,CheckedAt:"2026-05-12T10:00:05Z",ResponseTime:920},{ID:"BC-003",CustomerID:"CUS-2089",Bureau:"CRC",CreditScore:580,RiskGrade:"C",ActiveLoans:3,DefaultHistory:true,CheckedAt:"2026-05-11T14:00:00Z",ResponseTime:780}}
var tinChecks=[]TINVerification{{ID:"TIN-001",CompanyName:"Pinnacle Trading Ltd",TIN:"TIN-1234567890",FIRSStatus:"active",TaxClearanceValid:true,LastFilingYear:2025,VerifiedAt:"2026-05-12T10:00:00Z"},{ID:"TIN-002",CompanyName:"ABC Import Export Ltd",TIN:"TIN-9876543210",FIRSStatus:"active",TaxClearanceValid:false,LastFilingYear:2023,VerifiedAt:"2026-05-12T11:00:00Z"}}
func main(){
	port:=envOr("PORT","8289")
	http.HandleFunc("/healthz",func(w http.ResponseWriter,r*http.Request){json.NewEncoder(w).Encode(map[string]interface{}{"status":"healthy","service":"multi-bureau-verification-go","version":"1.0.0","middleware":mw})})
	http.HandleFunc("/api/bureau-checks",func(w http.ResponseWriter,r*http.Request){json.NewEncoder(w).Encode(map[string]interface{}{"items":bureauChecks,"total":len(bureauChecks)})})
	http.HandleFunc("/api/tin-verifications",func(w http.ResponseWriter,r*http.Request){json.NewEncoder(w).Encode(map[string]interface{}{"items":tinChecks,"total":len(tinChecks)})})
	fmt.Printf("multi-bureau-verification-go listening on :%s\n",port)
	http.ListenAndServe(":"+port,nil)
}
