apisix:
  node_listen: 9080
  admin_listen:
    port: 9180

deployment:
  admin:
    admin_key:
      - name: admin
        key: ngapp-admin-key-2026
        role: admin

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091

plugins:
  - limit-req
  - limit-count
  - cors
  - jwt-auth
  - key-auth
  - prometheus
  - opentelemetry
  - request-id
  - proxy-rewrite
  - response-rewrite
  - real-ip
  - ip-restriction

etcd:
  host:
    - "http://etcd:2379"
