#!/bin/bash

# Master Security Test Execution Script
# Runs all security validation tests and generates comprehensive report

set -e

# Configuration
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
RESULTS_DIR="./security-test-results-${TIMESTAMP}"
VAULT_ADDR="${VAULT_ADDR:-http://localhost:8200}"
VAULT_TOKEN="${VAULT_TOKEN:-root-token-dev}"
KEYCLOAK_URL="${KEYCLOAK_URL:-http://localhost:8180}"
REALM="${REALM:-payment-switch}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Create results directory
mkdir -p "$RESULTS_DIR"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Security Validation Test Suite${NC}"
echo -e "${BLUE}========================================${NC}"
echo -e "Timestamp: $(date)"
echo -e "Results Directory: $RESULTS_DIR"
echo ""

# Function to run a test script
run_test() {
    local test_name=$1
    local test_script=$2
    shift 2
    local test_args=("$@")
    
    echo -e "\n${YELLOW}Running: $test_name${NC}"
    echo "----------------------------------------"
    
    if python3 "$test_script" "${test_args[@]}"; then
        echo -e "${GREEN}✓ $test_name PASSED${NC}"
        return 0
    else
        echo -e "${RED}✗ $test_name FAILED${NC}"
        return 1
    fi
}

# Track test results
TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0

# Test 1: mTLS Validation
if run_test "mTLS Validation" "./test_mtls.py"; then
    ((PASSED_TESTS++))
else
    ((FAILED_TESTS++))
fi
((TOTAL_TESTS++))
mv mtls_test_results.json "$RESULTS_DIR/" 2>/dev/null || true

# Test 2: Secrets Management
if run_test "Secrets Management" "./test_secrets.py" --vault-addr "$VAULT_ADDR" --vault-token "$VAULT_TOKEN"; then
    ((PASSED_TESTS++))
else
    ((FAILED_TESTS++))
fi
((TOTAL_TESTS++))
mv secrets_test_results.json "$RESULTS_DIR/" 2>/dev/null || true

# Test 3: Access Control
if run_test "Access Control" "./test_access_control.py" --keycloak-url "$KEYCLOAK_URL" --realm "$REALM"; then
    ((PASSED_TESTS++))
else
    ((FAILED_TESTS++))
fi
((TOTAL_TESTS++))
mv access_control_test_results.json "$RESULTS_DIR/" 2>/dev/null || true

# Generate summary report
cat > "$RESULTS_DIR/summary.md" << EOF
# Security Validation Test Summary

**Test Date**: $(date)
**Results Directory**: $RESULTS_DIR

## Overall Results

| Metric | Value |
|--------|-------|
| Total Test Suites | $TOTAL_TESTS |
| Passed | $PASSED_TESTS |
| Failed | $FAILED_TESTS |
| Success Rate | $(echo "scale=1; $PASSED_TESTS * 100 / $TOTAL_TESTS" | bc)% |

## Test Suite Details

### 1. mTLS Validation
- **Status**: $([ -f "$RESULTS_DIR/mtls_test_results.json" ] && echo "Completed" || echo "Not Run")
- **Results**: $RESULTS_DIR/mtls_test_results.json

### 2. Secrets Management
- **Status**: $([ -f "$RESULTS_DIR/secrets_test_results.json" ] && echo "Completed" || echo "Not Run")
- **Results**: $RESULTS_DIR/secrets_test_results.json

### 3. Access Control
- **Status**: $([ -f "$RESULTS_DIR/access_control_test_results.json" ] && echo "Completed" || echo "Not Run")
- **Results**: $RESULTS_DIR/access_control_test_results.json

## Recommendations

EOF

if [ $FAILED_TESTS -gt 0 ]; then
    cat >> "$RESULTS_DIR/summary.md" << EOF
⚠️ **Action Required**: $FAILED_TESTS test suite(s) failed. Please review the individual test results and address any issues before deploying to production.

EOF
else
    cat >> "$RESULTS_DIR/summary.md" << EOF
✅ **All Tests Passed**: The security controls are properly configured and functioning as expected.

EOF
fi

cat >> "$RESULTS_DIR/summary.md" << EOF
## Next Steps

1. Review individual test results in the results directory
2. Address any failed tests or errors
3. Re-run tests after making corrections
4. Document any exceptions or known issues
5. Proceed with deployment once all tests pass

---

**Generated by**: Security Validation Test Suite
**Timestamp**: $(date)
EOF

# Print summary
echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Test Summary${NC}"
echo -e "${BLUE}========================================${NC}"
echo -e "Total Test Suites: $TOTAL_TESTS"
echo -e "Passed: ${GREEN}$PASSED_TESTS${NC}"
echo -e "Failed: ${RED}$FAILED_TESTS${NC}"
echo -e "Success Rate: $(echo "scale=1; $PASSED_TESTS * 100 / $TOTAL_TESTS" | bc)%"
echo ""
echo -e "Summary report: ${BLUE}$RESULTS_DIR/summary.md${NC}"
echo ""

# Exit with appropriate code
if [ $FAILED_TESTS -gt 0 ]; then
    echo -e "${RED}Some tests failed. Please review the results.${NC}"
    exit 1
else
    echo -e "${GREEN}All tests passed!${NC}"
    exit 0
fi
