# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ledger_pb2 as ledger__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ledger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LedgerServiceStub(object):
    """Ledger Service - High-performance gRPC service for TigerBeetle ledger operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAccount = channel.unary_unary(
                '/ledger.LedgerService/CreateAccount',
                request_serializer=ledger__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=ledger__pb2.CreateAccountResponse.FromString,
                _registered_method=True)
        self.CreateAccounts = channel.unary_unary(
                '/ledger.LedgerService/CreateAccounts',
                request_serializer=ledger__pb2.CreateAccountsRequest.SerializeToString,
                response_deserializer=ledger__pb2.CreateAccountsResponse.FromString,
                _registered_method=True)
        self.CreateTransfer = channel.unary_unary(
                '/ledger.LedgerService/CreateTransfer',
                request_serializer=ledger__pb2.CreateTransferRequest.SerializeToString,
                response_deserializer=ledger__pb2.CreateTransferResponse.FromString,
                _registered_method=True)
        self.CreateTransfers = channel.unary_unary(
                '/ledger.LedgerService/CreateTransfers',
                request_serializer=ledger__pb2.CreateTransfersRequest.SerializeToString,
                response_deserializer=ledger__pb2.CreateTransfersResponse.FromString,
                _registered_method=True)
        self.GetAccountBalance = channel.unary_unary(
                '/ledger.LedgerService/GetAccountBalance',
                request_serializer=ledger__pb2.GetAccountBalanceRequest.SerializeToString,
                response_deserializer=ledger__pb2.GetAccountBalanceResponse.FromString,
                _registered_method=True)
        self.GetAccountBalances = channel.unary_unary(
                '/ledger.LedgerService/GetAccountBalances',
                request_serializer=ledger__pb2.GetAccountBalancesRequest.SerializeToString,
                response_deserializer=ledger__pb2.GetAccountBalancesResponse.FromString,
                _registered_method=True)
        self.SyncBalanceToPostgres = channel.unary_unary(
                '/ledger.LedgerService/SyncBalanceToPostgres',
                request_serializer=ledger__pb2.SyncBalanceRequest.SerializeToString,
                response_deserializer=ledger__pb2.SyncBalanceResponse.FromString,
                _registered_method=True)


class LedgerServiceServicer(object):
    """Ledger Service - High-performance gRPC service for TigerBeetle ledger operations
    """

    def CreateAccount(self, request, context):
        """CreateAccount creates a new account in the ledger
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccounts(self, request, context):
        """CreateAccounts creates multiple accounts in a batch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTransfer(self, request, context):
        """CreateTransfer creates a new transfer between accounts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTransfers(self, request, context):
        """CreateTransfers creates multiple transfers in a batch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountBalance(self, request, context):
        """GetAccountBalance retrieves the balance of an account
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountBalances(self, request, context):
        """GetAccountBalances retrieves balances for multiple accounts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncBalanceToPostgres(self, request, context):
        """SyncBalanceToPostgres synchronizes an account balance to PostgreSQL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LedgerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccount,
                    request_deserializer=ledger__pb2.CreateAccountRequest.FromString,
                    response_serializer=ledger__pb2.CreateAccountResponse.SerializeToString,
            ),
            'CreateAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccounts,
                    request_deserializer=ledger__pb2.CreateAccountsRequest.FromString,
                    response_serializer=ledger__pb2.CreateAccountsResponse.SerializeToString,
            ),
            'CreateTransfer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTransfer,
                    request_deserializer=ledger__pb2.CreateTransferRequest.FromString,
                    response_serializer=ledger__pb2.CreateTransferResponse.SerializeToString,
            ),
            'CreateTransfers': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTransfers,
                    request_deserializer=ledger__pb2.CreateTransfersRequest.FromString,
                    response_serializer=ledger__pb2.CreateTransfersResponse.SerializeToString,
            ),
            'GetAccountBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountBalance,
                    request_deserializer=ledger__pb2.GetAccountBalanceRequest.FromString,
                    response_serializer=ledger__pb2.GetAccountBalanceResponse.SerializeToString,
            ),
            'GetAccountBalances': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountBalances,
                    request_deserializer=ledger__pb2.GetAccountBalancesRequest.FromString,
                    response_serializer=ledger__pb2.GetAccountBalancesResponse.SerializeToString,
            ),
            'SyncBalanceToPostgres': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncBalanceToPostgres,
                    request_deserializer=ledger__pb2.SyncBalanceRequest.FromString,
                    response_serializer=ledger__pb2.SyncBalanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ledger.LedgerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ledger.LedgerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LedgerService(object):
    """Ledger Service - High-performance gRPC service for TigerBeetle ledger operations
    """

    @staticmethod
    def CreateAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ledger.LedgerService/CreateAccount',
            ledger__pb2.CreateAccountRequest.SerializeToString,
            ledger__pb2.CreateAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ledger.LedgerService/CreateAccounts',
            ledger__pb2.CreateAccountsRequest.SerializeToString,
            ledger__pb2.CreateAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTransfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ledger.LedgerService/CreateTransfer',
            ledger__pb2.CreateTransferRequest.SerializeToString,
            ledger__pb2.CreateTransferResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTransfers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ledger.LedgerService/CreateTransfers',
            ledger__pb2.CreateTransfersRequest.SerializeToString,
            ledger__pb2.CreateTransfersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ledger.LedgerService/GetAccountBalance',
            ledger__pb2.GetAccountBalanceRequest.SerializeToString,
            ledger__pb2.GetAccountBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountBalances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ledger.LedgerService/GetAccountBalances',
            ledger__pb2.GetAccountBalancesRequest.SerializeToString,
            ledger__pb2.GetAccountBalancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncBalanceToPostgres(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ledger.LedgerService/SyncBalanceToPostgres',
            ledger__pb2.SyncBalanceRequest.SerializeToString,
            ledger__pb2.SyncBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
