# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vpa_pb2 as vpa__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vpa_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VPAServiceStub(object):
    """VPA Service for Virtual Payment Address management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateVPA = channel.unary_unary(
                '/vpa.VPAService/CreateVPA',
                request_serializer=vpa__pb2.CreateVPARequest.SerializeToString,
                response_deserializer=vpa__pb2.CreateVPAResponse.FromString,
                _registered_method=True)
        self.ResolveVPA = channel.unary_unary(
                '/vpa.VPAService/ResolveVPA',
                request_serializer=vpa__pb2.ResolveVPARequest.SerializeToString,
                response_deserializer=vpa__pb2.ResolveVPAResponse.FromString,
                _registered_method=True)
        self.ListVPAs = channel.unary_unary(
                '/vpa.VPAService/ListVPAs',
                request_serializer=vpa__pb2.ListVPAsRequest.SerializeToString,
                response_deserializer=vpa__pb2.ListVPAsResponse.FromString,
                _registered_method=True)
        self.UpdateVPA = channel.unary_unary(
                '/vpa.VPAService/UpdateVPA',
                request_serializer=vpa__pb2.UpdateVPARequest.SerializeToString,
                response_deserializer=vpa__pb2.UpdateVPAResponse.FromString,
                _registered_method=True)
        self.DeleteVPA = channel.unary_unary(
                '/vpa.VPAService/DeleteVPA',
                request_serializer=vpa__pb2.DeleteVPARequest.SerializeToString,
                response_deserializer=vpa__pb2.DeleteVPAResponse.FromString,
                _registered_method=True)
        self.CheckAvailability = channel.unary_unary(
                '/vpa.VPAService/CheckAvailability',
                request_serializer=vpa__pb2.CheckAvailabilityRequest.SerializeToString,
                response_deserializer=vpa__pb2.CheckAvailabilityResponse.FromString,
                _registered_method=True)
        self.TransferVPA = channel.unary_unary(
                '/vpa.VPAService/TransferVPA',
                request_serializer=vpa__pb2.TransferVPARequest.SerializeToString,
                response_deserializer=vpa__pb2.TransferVPAResponse.FromString,
                _registered_method=True)


class VPAServiceServicer(object):
    """VPA Service for Virtual Payment Address management
    """

    def CreateVPA(self, request, context):
        """Create a new VPA
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveVPA(self, request, context):
        """Resolve a VPA to account details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVPAs(self, request, context):
        """List VPAs for an account
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateVPA(self, request, context):
        """Update VPA
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVPA(self, request, context):
        """Delete VPA
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAvailability(self, request, context):
        """Check VPA availability
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferVPA(self, request, context):
        """Transfer VPA to another bank
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VPAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateVPA': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVPA,
                    request_deserializer=vpa__pb2.CreateVPARequest.FromString,
                    response_serializer=vpa__pb2.CreateVPAResponse.SerializeToString,
            ),
            'ResolveVPA': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveVPA,
                    request_deserializer=vpa__pb2.ResolveVPARequest.FromString,
                    response_serializer=vpa__pb2.ResolveVPAResponse.SerializeToString,
            ),
            'ListVPAs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVPAs,
                    request_deserializer=vpa__pb2.ListVPAsRequest.FromString,
                    response_serializer=vpa__pb2.ListVPAsResponse.SerializeToString,
            ),
            'UpdateVPA': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateVPA,
                    request_deserializer=vpa__pb2.UpdateVPARequest.FromString,
                    response_serializer=vpa__pb2.UpdateVPAResponse.SerializeToString,
            ),
            'DeleteVPA': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVPA,
                    request_deserializer=vpa__pb2.DeleteVPARequest.FromString,
                    response_serializer=vpa__pb2.DeleteVPAResponse.SerializeToString,
            ),
            'CheckAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailability,
                    request_deserializer=vpa__pb2.CheckAvailabilityRequest.FromString,
                    response_serializer=vpa__pb2.CheckAvailabilityResponse.SerializeToString,
            ),
            'TransferVPA': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferVPA,
                    request_deserializer=vpa__pb2.TransferVPARequest.FromString,
                    response_serializer=vpa__pb2.TransferVPAResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vpa.VPAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vpa.VPAService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VPAService(object):
    """VPA Service for Virtual Payment Address management
    """

    @staticmethod
    def CreateVPA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vpa.VPAService/CreateVPA',
            vpa__pb2.CreateVPARequest.SerializeToString,
            vpa__pb2.CreateVPAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveVPA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vpa.VPAService/ResolveVPA',
            vpa__pb2.ResolveVPARequest.SerializeToString,
            vpa__pb2.ResolveVPAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVPAs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vpa.VPAService/ListVPAs',
            vpa__pb2.ListVPAsRequest.SerializeToString,
            vpa__pb2.ListVPAsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateVPA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vpa.VPAService/UpdateVPA',
            vpa__pb2.UpdateVPARequest.SerializeToString,
            vpa__pb2.UpdateVPAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVPA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vpa.VPAService/DeleteVPA',
            vpa__pb2.DeleteVPARequest.SerializeToString,
            vpa__pb2.DeleteVPAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vpa.VPAService/CheckAvailability',
            vpa__pb2.CheckAvailabilityRequest.SerializeToString,
            vpa__pb2.CheckAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferVPA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vpa.VPAService/TransferVPA',
            vpa__pb2.TransferVPARequest.SerializeToString,
            vpa__pb2.TransferVPAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
