apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ray-serve

resources:
- namespace.yaml
- configmap.yaml
- secrets.yaml
- rbac.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- keda-scaledobject.yaml
- servicemonitor.yaml
- pdb.yaml
- networkpolicy.yaml

commonLabels:
  app.kubernetes.io/name: ray-serve-api
  app.kubernetes.io/component: ml-inference
  app.kubernetes.io/part-of: lakehouse-platform
  app.kubernetes.io/managed-by: kustomize

images:
- name: rayproject/ray-ml
  newTag: 2.9.0-py310
