apiVersion: v1
kind: Namespace
metadata:
  name: ray-serve
  labels:
    name: ray-serve
    app.kubernetes.io/name: ray-serve
    app.kubernetes.io/component: ml-inference
    app.kubernetes.io/part-of: lakehouse-platform
