# Payment Switch Platform - Ansible Inventory
# Generated by Terraform

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/payment-switch-key
ansible_python_interpreter=/usr/bin/python3

[control_plane]
%{ for node in control_plane_nodes ~}
${node.name} ansible_host=${node.public_ip} private_ip=${node.private_ip}
%{ endfor ~}

[workers]
%{ for node in worker_nodes ~}
${node.name} ansible_host=${node.private_ip} private_ip=${node.private_ip}
%{ endfor ~}

[data_nodes]
%{ for node in data_nodes ~}
${node.name} ansible_host=${node.private_ip} private_ip=${node.private_ip}
%{ endfor ~}

[k8s_cluster:children]
control_plane
workers
data_nodes

[k8s_cluster:vars]
api_server_lb=${api_lb_ip}
ingress_lb=${ingress_lb_ip}
