/**
 * Regulatory Reporting Module
 * Design: Dark Amber — OG-RMM Platform
 *
 * Gap Closure: G-04 — Regulatory Reporting Automation
 * Covers:
 *   - API 14C: Surface Safety System documentation
 *   - BSEE OGOR: Oil and Gas Operations Report (monthly production)
 *   - EPA Subpart W: Greenhouse Gas emissions reporting
 *   - PHMSA: Pipeline safety incident reports
 *   - State-level production reports (Texas RRC, NDIC, COGCC)
 *
 * In production, reports are generated by the Python analytics service
 * and submitted via agency e-filing APIs.
 */

import { useState } from "react";
import { useTranslation } from "react-i18next";
import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { FileText, CheckCircle2, AlertTriangle, Clock, Download,
  Send, RefreshCw, Shield, BarChart3, Droplets, Wind,
  ChevronRight, Calendar, Building2, Globe, ExternalLink, Eye, X
} from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, Cell, PieChart, Pie, Legend
} from "recharts";

// ── Types ─────────────────────────────────────────────────────────────────────

type ReportStatus = "SUBMITTED" | "PENDING" | "OVERDUE" | "DRAFT" | "REJECTED";
type ReportType = "API_14C" | "BSEE_OGOR" | "EPA_SUBPART_W" | "PHMSA" | "STATE_RRC" | "STATE_NDIC";

interface RegulatoryReport {
  report_id: string;
  type: ReportType;
  title: string;
  agency: string;
  period: string;
  due_date: string;
  submitted_date?: string;
  status: ReportStatus;
  wells_covered: number;
  completeness_pct: number;
  submission_ref?: string;
  notes?: string;
}

interface ComplianceMetric {
  agency: string;
  total: number;
  submitted: number;
  pending: number;
  overdue: number;
}

// ── Mock data ─────────────────────────────────────────────────────────────────

const MOCK_REPORTS: RegulatoryReport[] = [
  {
    report_id: "RPT-2026-001",
    type: "BSEE_OGOR",
    title: "BSEE OGOR — February 2026",
    agency: "Bureau of Safety and Environmental Enforcement",
    period: "February 2026",
    due_date: "2026-03-20",
    submitted_date: "2026-03-05",
    status: "SUBMITTED",
    wells_covered: 142,
    completeness_pct: 100,
    submission_ref: "BSEE-2026-OGR-00847",
    notes: "All 142 wells reported. Accepted by BSEE e-filing portal.",
  },
  {
    report_id: "RPT-2026-002",
    type: "EPA_SUBPART_W",
    title: "EPA Subpart W — Q4 2025 GHG",
    agency: "U.S. Environmental Protection Agency",
    period: "Q4 2025",
    due_date: "2026-03-31",
    status: "PENDING",
    wells_covered: 138,
    completeness_pct: 87,
    notes: "4 wells missing methane emission factors. Awaiting field measurement data.",
  },
  {
    report_id: "RPT-2026-003",
    type: "API_14C",
    title: "API 14C — Surface Safety System Annual Review",
    agency: "American Petroleum Institute",
    period: "Annual 2025",
    due_date: "2026-02-28",
    status: "OVERDUE",
    wells_covered: 89,
    completeness_pct: 72,
    notes: "Missing SIL verification records for 25 wells. Escalated to safety team.",
  },
  {
    report_id: "RPT-2026-004",
    type: "STATE_RRC",
    title: "Texas RRC Monthly Production — February 2026",
    agency: "Texas Railroad Commission",
    period: "February 2026",
    due_date: "2026-03-25",
    submitted_date: "2026-03-10",
    status: "SUBMITTED",
    wells_covered: 67,
    completeness_pct: 100,
    submission_ref: "TRRC-2026-P2-04421",
  },
  {
    report_id: "RPT-2026-005",
    type: "STATE_NDIC",
    title: "NDIC Monthly Production — February 2026",
    agency: "North Dakota Industrial Commission",
    period: "February 2026",
    due_date: "2026-03-25",
    status: "DRAFT",
    wells_covered: 33,
    completeness_pct: 95,
    notes: "Draft ready. Awaiting supervisor approval before submission.",
  },
  {
    report_id: "RPT-2026-006",
    type: "PHMSA",
    title: "PHMSA Annual Report — Pipeline Safety 2025",
    agency: "Pipeline and Hazardous Materials Safety Administration",
    period: "Annual 2025",
    due_date: "2026-03-15",
    submitted_date: "2026-03-12",
    status: "SUBMITTED",
    wells_covered: 0,
    completeness_pct: 100,
    submission_ref: "PHMSA-2026-GAS-00123",
  },
  {
    report_id: "RPT-2026-007",
    type: "BSEE_OGOR",
    title: "BSEE OGOR — March 2026",
    agency: "Bureau of Safety and Environmental Enforcement",
    period: "March 2026",
    due_date: "2026-04-20",
    status: "DRAFT",
    wells_covered: 142,
    completeness_pct: 41,
    notes: "Auto-populated from production telemetry. Month not yet complete.",
  },
];

const COMPLIANCE_METRICS: ComplianceMetric[] = [
  { agency: "BSEE", total: 12, submitted: 11, pending: 1, overdue: 0 },
  { agency: "EPA", total: 4, submitted: 3, pending: 1, overdue: 0 },
  { agency: "API", total: 1, submitted: 0, pending: 0, overdue: 1 },
  { agency: "Texas RRC", total: 12, submitted: 11, pending: 1, overdue: 0 },
  { agency: "NDIC", total: 12, submitted: 10, pending: 2, overdue: 0 },
  { agency: "PHMSA", total: 1, submitted: 1, pending: 0, overdue: 0 },
];

// EPA Subpart W GHG data
const GHG_DATA = [
  { source: "Pneumatic Controllers", co2e: 4820, category: "Methane" },
  { source: "Wellhead Venting", co2e: 3240, category: "Methane" },
  { source: "Flaring", co2e: 2180, category: "CO2" },
  { source: "Compressor Seals", co2e: 1560, category: "Methane" },
  { source: "Tank Emissions", co2e: 890, category: "Methane" },
  { source: "Fugitive Leaks", co2e: 640, category: "Methane" },
  { source: "Combustion", co2e: 420, category: "CO2" },
];

const GHG_COLORS = { Methane: "#f59e0b", CO2: "#60a5fa" };

// API 14C surface safety system data
const API14C_DATA = [
  { system: "ESD Valves", total: 142, compliant: 128, pct: 90 },
  { system: "SSSV (Subsurface)", total: 89, compliant: 72, pct: 81 },
  { system: "PSV / Relief Valves", total: 284, compliant: 271, pct: 95 },
  { system: "Fusible Loop", total: 67, compliant: 67, pct: 100 },
  { system: "High-Low Pressure Pilots", total: 142, compliant: 135, pct: 95 },
  { system: "Wellhead Chokes", total: 142, compliant: 139, pct: 98 },
];

// ── Helpers ───────────────────────────────────────────────────────────────────

function statusConfig(status: ReportStatus) {
  const map: Record<ReportStatus, { label: string; color: string; bg: string; icon: typeof CheckCircle2 }> = {
    SUBMITTED: { label: "Submitted", color: "text-emerald-400", bg: "bg-emerald-500/10 border-emerald-700/30", icon: CheckCircle2 },
    PENDING:   { label: "Pending",   color: "text-amber-400",   bg: "bg-amber-500/10 border-amber-700/30",   icon: Clock },
    OVERDUE:   { label: "Overdue",   color: "text-red-400",     bg: "bg-red-500/10 border-red-700/30",       icon: AlertTriangle },
    DRAFT:     { label: "Draft",     color: "text-blue-400",    bg: "bg-blue-500/10 border-blue-700/30",     icon: FileText },
    REJECTED:  { label: "Rejected",  color: "text-red-400",     bg: "bg-red-500/10 border-red-700/30",       icon: AlertTriangle },
  };
  return map[status];
}

function typeConfig(type: ReportType) {
  const map: Record<ReportType, { label: string; color: string }> = {
    API_14C:       { label: "API 14C",    color: "text-orange-400" },
    BSEE_OGOR:     { label: "BSEE OGOR",  color: "text-blue-400" },
    EPA_SUBPART_W: { label: "EPA Sub-W",  color: "text-green-400" },
    PHMSA:         { label: "PHMSA",      color: "text-purple-400" },
    STATE_RRC:     { label: "Texas RRC",  color: "text-amber-400" },
    STATE_NDIC:    { label: "NDIC",       color: "text-cyan-400" },
  };
  return map[type];
}

function daysUntilDue(dueDate: string): number {
  const due = new Date(dueDate);
  const now = new Date();
  return Math.ceil((due.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
}

// ── Sub-components ────────────────────────────────────────────────────────────

// Map frontend report types to backend enum values
const BACKEND_TYPE_MAP: Partial<Record<ReportType, "API_14C" | "BSEE_OGOR" | "EPA_SUBPART_W" | "MOCCAE" | "ADNOC_HSE" | "KOC_ENV" | "NCSC_INCIDENT">> = {
  API_14C: "API_14C",
  BSEE_OGOR: "BSEE_OGOR",
  EPA_SUBPART_W: "EPA_SUBPART_W",
  // Map additional report types to the closest backend enum value
  STATE_RRC: "BSEE_OGOR",   // Texas RRC uses BSEE OGOR format
  STATE_NDIC: "BSEE_OGOR",  // NDIC uses BSEE OGOR format
  PHMSA: "API_14C",          // PHMSA uses API 14C format
};

function ReportRow({ report, onPreview }: { report: RegulatoryReport; onPreview?: (url: string, title: string) => void }) {
  const sc = statusConfig(report.status);
  const tc = typeConfig(report.type);
  const StatusIcon = sc.icon;
  const days = daysUntilDue(report.due_date);
  const [generating, setGenerating] = useState(false);
  const [pdfUrl, setPdfUrl] = useState<string | null>(null);
  const [dbReportId, setDbReportId] = useState<number | null>(null);
  const [submitting, setSubmitting] = useState(false);

  const AUTHORITY_MAP: Record<string, "ADNOC" | "KOC" | "ARAMCO" | "MOCCAE" | "BSEE" | "EPA" | "NCSC"> = {
    "ADNOC": "ADNOC", "KOC": "KOC", "Saudi Aramco": "ARAMCO", "ARAMCO": "ARAMCO",
    "MOCCAE": "MOCCAE", "BSEE": "BSEE", "EPA": "EPA", "NCSC": "NCSC",
  };

  const submitToAuthority = trpc.regulatory.submitToAuthority.useMutation({
    onSuccess: (data) => {
      setSubmitting(false);
      toast.success(`Submitted to ${data.authority}`, {
        description: `Reference: ${data.submissionRef}`,
        duration: 8000,
      });
    },
    onError: (err) => {
      setSubmitting(false);
      toast.error("Submission failed", { description: err.message });
    },
  });

  const { t } = useTranslation();

  const generateBilingual = trpc.regulatory.generateBilingualPDF.useMutation({
    onSuccess: (data) => {
      // Open the bilingual HTML report in a new window
      const win = window.open("", "_blank");
      if (win) {
        win.document.write(data.html);
        win.document.close();
      }
      toast.success(`Bilingual report generated — ${data.titleEn} / ${data.titleAr}`, { duration: 6000 });
    },
    onError: (err) => toast.error(`Bilingual PDF failed: ${err.message}`),
  });

  const generatePDF = trpc.regulatory.generatePDF.useMutation({
    onSuccess: (data) => {
      setGenerating(false);
      setPdfUrl(data.url);
      setDbReportId(data.id);
      toast.success(`${report.title} — PDF generated`, {
        description: (
          <span>
            <a href={data.url} target="_blank" rel="noopener noreferrer" className="underline text-blue-400">
              Download PDF ({(data.sizeBytes / 1024).toFixed(0)} KB)
            </a>
            {" · "}
            <button
              onClick={() => onPreview?.(data.url, report.title)}
              className="underline text-amber-400"
            >
              Preview
            </button>
          </span>
        ) as any,
        duration: 10000,
      });
    },
    onError: (err) => {
      setGenerating(false);
      toast.error("PDF generation failed", { description: err.message });
    },
  });

  async function handleGenerate() {
    const backendType = BACKEND_TYPE_MAP[report.type];
    if (!backendType) {
      // Fallback for types not yet in backend enum
      setGenerating(true);
      await new Promise(r => setTimeout(r, 1200));
      setGenerating(false);
      toast.success(`${report.title} — report package generated`, {
        description: "PDF + XML e-filing package ready for download",
      });
      return;
    }
    setGenerating(true);
    generatePDF.mutate({
      reportType: backendType,
      period: report.period,
      language: "EN",
      notes: report.notes,
    });
  }

  function handleSubmit() {
    if (!dbReportId) {
      toast.warning("Generate PDF first", { description: "A PDF must be generated before submitting to the authority." });
      return;
    }
    const authority = AUTHORITY_MAP[report.agency];
    if (!authority) {
      toast.warning("Authority not mapped", { description: `No e-filing endpoint configured for ${report.agency}` });
      return;
    }
    setSubmitting(true);
    submitToAuthority.mutate({ id: dbReportId, authority });
  }

  return (
    <div className="rounded-lg border border-border/50 bg-card p-4 hover:border-border transition-colors">
      <div className="flex items-start justify-between gap-4">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1 flex-wrap">
            <span className={`text-[10px] font-mono font-bold px-1.5 py-0.5 rounded border ${tc.color} bg-card border-border/50`}>
              {tc.label}
            </span>
            <span className={`text-[10px] font-medium px-1.5 py-0.5 rounded border ${sc.bg} ${sc.color}`}>
              <StatusIcon className="w-2.5 h-2.5 inline mr-1" />
              {sc.label}
            </span>
            {report.submission_ref && (
              <span className="text-[10px] font-mono text-muted-foreground">{report.submission_ref}</span>
            )}
          </div>
          <div className="font-[Syne] font-bold text-sm text-foreground">{report.title}</div>
          <div className="text-xs text-muted-foreground mt-0.5">{report.agency} · {report.period}</div>
          {report.notes && (
            <div className="text-xs text-muted-foreground mt-1 italic">{report.notes}</div>
          )}
        </div>

        <div className="flex flex-col items-end gap-2 shrink-0">
          <div className="text-right">
            <div className="text-xs text-muted-foreground">Due {report.due_date}</div>
            {report.status !== "SUBMITTED" && (
              <div className={`text-xs font-mono font-bold ${days < 0 ? "text-red-400" : days < 7 ? "text-amber-400" : "text-muted-foreground"}`}>
                {days < 0 ? `${Math.abs(days)}d overdue` : `${days}d remaining`}
              </div>
            )}
          </div>
          <div className="flex items-center gap-1.5">
            {pdfUrl && (
              <Button
                variant="outline"
                size="sm"
                className="h-7 text-xs border-amber-700/40 text-amber-400 hover:text-amber-300"
                onClick={() => onPreview?.(pdfUrl, report.title)}
              >
                <Eye className="w-3 h-3 mr-1" />
                Preview
              </Button>
            )}
            <Button
              variant="outline"
              size="sm"
              className="h-7 text-xs border-border/50"
              onClick={handleGenerate}
              disabled={generating}
            >
              {generating ? (
                <span className="w-3 h-3 mr-1 border border-foreground/30 border-t-foreground rounded-full animate-spin inline-block" />
              ) : (
                <Download className="w-3 h-3 mr-1" />
              )}
              Generate
            </Button>
            <Button
              size="sm"
              variant="outline"
              className="h-7 text-xs border-amber-700/40 text-amber-400 hover:bg-amber-950/30"
              onClick={() => generateBilingual.mutate({ reportType: BACKEND_TYPE_MAP[report.type] ?? report.type, period: report.period, language: "bilingual" })}
              disabled={generateBilingual.isPending}
              title="Generate bilingual Arabic/English report"
            >
              <Globe className="w-3 h-3 mr-1" />
              AR/EN
            </Button>
            {(report.status === "PENDING" || report.status === "DRAFT") && (
              <Button
                size="sm"
                className="h-7 text-xs bg-amber-600 hover:bg-amber-700 text-white"
                onClick={handleSubmit}
                disabled={submitting}
              >
                {submitting ? (
                  <span className="w-3 h-3 mr-1 border border-white/30 border-t-white rounded-full animate-spin inline-block" />
                ) : (
                  <Send className="w-3 h-3 mr-1" />
                )}
                {submitting ? "Submitting..." : "Submit"}
              </Button>
            )}
          </div>
        </div>
      </div>

      {report.completeness_pct < 100 && (
        <div className="mt-3">
          <div className="flex items-center justify-between text-[10px] text-muted-foreground mb-1">
            <span>Data completeness</span>
            <span className="font-mono">{report.completeness_pct}%</span>
          </div>
          <Progress
            value={report.completeness_pct}
            className="h-1"
          />
        </div>
      )}
    </div>
  );
}

function ComplianceBar({ metric }: { metric: ComplianceMetric }) {
  const pct = Math.round((metric.submitted / metric.total) * 100);
  return (
    <div className="space-y-1">
      <div className="flex items-center justify-between text-xs">
        <span className="font-medium text-foreground">{metric.agency}</span>
        <span className="font-mono text-muted-foreground">
          {metric.submitted}/{metric.total}
          {metric.overdue > 0 && <span className="text-red-400 ml-1">({metric.overdue} overdue)</span>}
        </span>
      </div>
      <div className="h-2 rounded-full bg-muted overflow-hidden flex">
        <div className="bg-emerald-500 h-full transition-all" style={{ width: `${(metric.submitted/metric.total)*100}%` }} />
        <div className="bg-amber-500 h-full transition-all" style={{ width: `${(metric.pending/metric.total)*100}%` }} />
        <div className="bg-red-500 h-full transition-all" style={{ width: `${(metric.overdue/metric.total)*100}%` }} />
      </div>
    </div>
  );
}

// ── Main Page ─────────────────────────────────────────────────────────────────

// ── PDF Preview Modal ────────────────────────────────────────────────────────

function PDFPreviewModal({ url, title, onClose }: { url: string; title: string; onClose: () => void }) {
  return (
    <Dialog open onOpenChange={(open) => { if (!open) onClose(); }}>
      <DialogContent className="max-w-5xl w-full h-[90vh] flex flex-col p-0 gap-0">
        <DialogHeader className="px-4 py-3 border-b border-border/50 shrink-0">
          <div className="flex items-center justify-between">
            <DialogTitle className="text-sm font-[Syne] font-bold truncate pr-4">{title}</DialogTitle>
            <div className="flex items-center gap-2 shrink-0">
              <a
                href={url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-xs text-amber-400 hover:text-amber-300 flex items-center gap-1"
              >
                <ExternalLink className="w-3 h-3" />
                Open in new tab
              </a>
            </div>
          </div>
        </DialogHeader>
        <div className="flex-1 min-h-0">
          <iframe
            src={url}
            className="w-full h-full border-0"
            title={title}
          />
        </div>
      </DialogContent>
    </Dialog>
  );
}

export default function RegulatoryPage() {
  const [filterType, setFilterType] = useState<string>("ALL");
  const [filterStatus, setFilterStatus] = useState<string>("ALL");
  const [period, setPeriod] = useState("2026-Q1");
  const [pdfPreview, setPdfPreview] = useState<{ url: string; title: string } | null>(null);

  // Real tRPC data — falls back to MOCK_REPORTS when DB is empty
  const { data: liveReports, refetch: refetchReports } = trpc.regulatory.list.useQuery({ limit: 200 });
  const generateAllMutation = trpc.regulatory.generate.useMutation({
    onSuccess: () => { refetchReports(); toast.success("Report generated successfully"); },
    onError: (err) => toast.error(`Generation failed: ${err.message}`),
  });

  // Map live DB reports to the same shape as MOCK_REPORTS for display
  const allReports: RegulatoryReport[] = (liveReports && liveReports.length > 0)
    ? liveReports.map(r => ({
        report_id: r.reportId,
        type: (r.reportType as ReportType) ?? "BSEE_OGOR",
        title: `${r.reportType} — ${r.period}`,
        agency: r.reportType,
        period: r.period,
        due_date: r.submittedAt?.toISOString() ?? new Date().toISOString(),
        submitted_date: r.submittedAt?.toISOString(),
        status: (r.status as ReportStatus) ?? "DRAFT",
        wells_covered: 0,
        completeness_pct: r.status === "SUBMITTED" ? 100 : 50,
        submission_ref: r.reportId,
        notes: r.notes ?? undefined,
      }))
    : MOCK_REPORTS;

  const filtered = allReports.filter(r => {
    if (filterType !== "ALL" && r.type !== filterType) return false;
    if (filterStatus !== "ALL" && r.status !== filterStatus) return false;
    return true;
  });

  const overdueCount = allReports.filter(r => r.status === "OVERDUE").length;
  const pendingCount = allReports.filter(r => r.status === "PENDING" || r.status === "DRAFT").length;
  const submittedCount = allReports.filter(r => r.status === "SUBMITTED").length;
  const totalGHG = GHG_DATA.reduce((s, d) => s + d.co2e, 0);

  return (
    <div className="p-6 space-y-6 max-w-[1400px]">
      {/* PDF Preview Modal */}
      {pdfPreview && (
        <PDFPreviewModal
          url={pdfPreview.url}
          title={pdfPreview.title}
          onClose={() => setPdfPreview(null)}
        />
      )}
      {/* Header */}
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <h1 className="font-[Syne] font-black text-2xl text-foreground tracking-tight">
            Regulatory Reporting
          </h1>
          <p className="text-sm text-muted-foreground mt-0.5">
            Production reporting · Environmental compliance · Regulatory submissions · State filings
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Select value={period} onValueChange={setPeriod}>
            <SelectTrigger className="w-36 h-8 text-sm">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="2026-Q1">Q1 2026</SelectItem>
              <SelectItem value="2025-Q4">Q4 2025</SelectItem>
              <SelectItem value="2025-Q3">Q3 2025</SelectItem>
              <SelectItem value="2025-annual">Annual 2025</SelectItem>
            </SelectContent>
          </Select>
          <Button
            className="bg-amber-600 hover:bg-amber-700 text-white h-8 text-sm"
            onClick={() => generateAllMutation.mutate({ reportType: "BSEE_OGOR", period, language: "EN" })}
            disabled={generateAllMutation.isPending}
          >
            <RefreshCw className="w-3.5 h-3.5 mr-1.5" />
            Auto-Generate All
          </Button>
        </div>
      </div>

      {/* Overdue alert */}
      {overdueCount > 0 && (
        <div className="rounded-lg border border-red-700/40 bg-red-950/10 p-3 flex items-center gap-3">
          <AlertTriangle className="w-4 h-4 text-red-400 shrink-0" />
          <div className="text-sm">
            <span className="font-bold text-red-400">{overdueCount} report{overdueCount > 1 ? "s" : ""} overdue.</span>
            <span className="text-muted-foreground ml-1">Regulatory penalties may apply. Immediate action required.</span>
          </div>
        </div>
      )}

      {/* KPI row */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[
          { label: "Submitted", value: submittedCount, icon: CheckCircle2, color: "text-emerald-400", bg: "bg-emerald-950/40 border-emerald-700/30" },
          { label: "Pending / Draft", value: pendingCount, icon: Clock, color: "text-amber-400", bg: "bg-amber-950/40 border-amber-700/30" },
          { label: "Overdue", value: overdueCount, icon: AlertTriangle, color: "text-red-400", bg: "bg-red-950/40 border-red-700/30" },
          { label: "Total GHG (tCO₂e)", value: totalGHG.toLocaleString(), icon: Wind, color: "text-blue-400", bg: "bg-blue-950/40 border-blue-700/30" },
        ].map(kpi => {
          const Icon = kpi.icon;
          return (
            <Card key={kpi.label} className={`border ${kpi.bg}`}>
              <CardContent className="p-4">
                <div className="flex items-center gap-2 mb-1">
                  <Icon className={`w-3.5 h-3.5 ${kpi.color}`} />
                  <span className="text-xs text-muted-foreground">{kpi.label}</span>
                </div>
                <div className={`font-[Syne] font-black text-2xl ${kpi.color}`}>{kpi.value}</div>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Tabs */}
      <Tabs defaultValue="reports">
        <TabsList className="bg-muted/50 h-8">
          <TabsTrigger value="reports" className="text-xs h-7">All Reports</TabsTrigger>
          <TabsTrigger value="api14c" className="text-xs h-7">API 14C</TabsTrigger>
          <TabsTrigger value="ghg" className="text-xs h-7">EPA GHG</TabsTrigger>
          <TabsTrigger value="compliance" className="text-xs h-7">Compliance Score</TabsTrigger>
          <TabsTrigger value="history" className="text-xs h-7">Submission History</TabsTrigger>
          <TabsTrigger value="calendar" className="text-xs h-7"><Calendar className="w-3 h-3 mr-1" />Calendar</TabsTrigger>
        </TabsList>

        {/* All Reports tab */}
        <TabsContent value="reports" className="mt-4 space-y-4">
          <div className="flex gap-2 flex-wrap">
            <Select value={filterType} onValueChange={setFilterType}>
              <SelectTrigger className="w-40 h-7 text-xs">
                <SelectValue placeholder="Report Type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="ALL">All Types</SelectItem>
                <SelectItem value="API_14C">API 14C</SelectItem>
                <SelectItem value="BSEE_OGOR">BSEE OGOR</SelectItem>
                <SelectItem value="EPA_SUBPART_W">EPA Subpart W</SelectItem>
                <SelectItem value="PHMSA">PHMSA</SelectItem>
                <SelectItem value="STATE_RRC">Texas RRC</SelectItem>
                <SelectItem value="STATE_NDIC">NDIC</SelectItem>
              </SelectContent>
            </Select>
            <Select value={filterStatus} onValueChange={setFilterStatus}>
              <SelectTrigger className="w-36 h-7 text-xs">
                <SelectValue placeholder="Status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="ALL">All Status</SelectItem>
                <SelectItem value="SUBMITTED">Submitted</SelectItem>
                <SelectItem value="PENDING">Pending</SelectItem>
                <SelectItem value="DRAFT">Draft</SelectItem>
                <SelectItem value="OVERDUE">Overdue</SelectItem>
              </SelectContent>
            </Select>
            <span className="text-xs text-muted-foreground self-center ml-auto">
              {filtered.length} of {MOCK_REPORTS.length} reports
            </span>
          </div>
          <div className="space-y-2">
            {filtered.map(r => <ReportRow key={r.report_id} report={r} onPreview={(url, title) => setPdfPreview({ url, title })} />)}
          </div>
        </TabsContent>

        {/* API 14C tab */}
        <TabsContent value="api14c" className="mt-4 space-y-4">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <Card className="border-border/50">
              <CardHeader className="pb-2">
                <CardTitle className="font-[Syne] text-sm font-bold">
                  Surface Safety System Compliance — API 14C
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {API14C_DATA.map(d => (
                    <div key={d.system}>
                      <div className="flex items-center justify-between text-xs mb-1">
                        <span className="text-foreground">{d.system}</span>
                        <span className="font-mono text-muted-foreground">
                          {d.compliant}/{d.total} ({d.pct}%)
                        </span>
                      </div>
                      <div className="h-2 rounded-full bg-muted overflow-hidden">
                        <div
                          className={`h-full rounded-full transition-all ${d.pct >= 95 ? "bg-emerald-500" : d.pct >= 80 ? "bg-amber-500" : "bg-red-500"}`}
                          style={{ width: `${d.pct}%` }}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            <Card className="border-border/50">
              <CardHeader className="pb-2">
                <CardTitle className="font-[Syne] text-sm font-bold">API 14C Requirements Summary</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                {[
                  { req: "Section 4 — Safety Analysis", status: "COMPLETE", note: "All 142 wells analyzed" },
                  { req: "Section 5 — Safety Devices", status: "PARTIAL", note: "14 ESD valves require recertification" },
                  { req: "Section 6 — SSSV Documentation", status: "PARTIAL", note: "17 subsurface valves missing test records" },
                  { req: "Section 7 — Functional Testing", status: "COMPLETE", note: "Annual test records current" },
                  { req: "Section 8 — Maintenance Records", status: "COMPLETE", note: "All maintenance logs uploaded" },
                  { req: "SIL Verification (IEC 61511)", status: "OVERDUE", note: "25 wells pending SIL-2 verification" },
                ].map(item => (
                  <div key={item.req} className="flex items-start justify-between gap-2">
                    <div>
                      <div className="text-xs font-medium text-foreground">{item.req}</div>
                      <div className="text-[10px] text-muted-foreground">{item.note}</div>
                    </div>
                    <Badge
                      variant="outline"
                      className={`text-[9px] shrink-0 ${
                        item.status === "COMPLETE" ? "text-emerald-400 border-emerald-700/30" :
                        item.status === "PARTIAL" ? "text-amber-400 border-amber-700/30" :
                        "text-red-400 border-red-700/30"
                      }`}
                    >
                      {item.status}
                    </Badge>
                  </div>
                ))}
                <Button
                  className="w-full mt-2 bg-amber-600 hover:bg-amber-700 text-white text-xs h-8"
                  onClick={() => toast.success("API 14C report package generated", { description: "PDF + supporting documentation ready for download" })}
                >
                  <Download className="w-3.5 h-3.5 mr-1.5" />
                  Generate API 14C Report Package
                </Button>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* EPA GHG tab */}
        <TabsContent value="ghg" className="mt-4 space-y-4">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <Card className="border-border/50">
              <CardHeader className="pb-2">
                <CardTitle className="font-[Syne] text-sm font-bold">
                  GHG Emissions by Source — EPA Subpart W
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="h-56">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={GHG_DATA} layout="vertical" margin={{ left: 8, right: 24 }}>
                      <CartesianGrid strokeDasharray="3 3" stroke="oklch(1 0 0 / 6%)" horizontal={false} />
                      <XAxis type="number" tick={{ fontSize: 10, fill: "oklch(0.552 0.016 285.938)" }} />
                      <YAxis dataKey="source" type="category" width={130} tick={{ fontSize: 9, fill: "oklch(0.552 0.016 285.938)" }} />
                      <Tooltip
                        contentStyle={{ background: "oklch(0.21 0.006 285.885)", border: "1px solid oklch(1 0 0 / 10%)", borderRadius: "6px", fontSize: "11px" }}
                        formatter={(v: number) => [`${v.toLocaleString()} tCO₂e`, "Emissions"]}
                      />
                      <Bar dataKey="co2e" radius={[0, 3, 3, 0]}>
                        {GHG_DATA.map((d, i) => (
                          <Cell key={i} fill={d.category === "Methane" ? "#f59e0b" : "#60a5fa"} />
                        ))}
                      </Bar>
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </CardContent>
            </Card>

            <Card className="border-border/50">
              <CardHeader className="pb-2">
                <CardTitle className="font-[Syne] text-sm font-bold">Emissions Summary</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-2 gap-3">
                  {[
                    { label: "Total GHG", value: `${totalGHG.toLocaleString()} tCO₂e`, color: "text-amber-400" },
                    { label: "Methane (CH₄)", value: `${GHG_DATA.filter(d=>d.category==="Methane").reduce((s,d)=>s+d.co2e,0).toLocaleString()} tCO₂e`, color: "text-amber-400" },
                    { label: "CO₂ Direct", value: `${GHG_DATA.filter(d=>d.category==="CO2").reduce((s,d)=>s+d.co2e,0).toLocaleString()} tCO₂e`, color: "text-blue-400" },
                    { label: "vs. Prior Year", value: "-3.2%", color: "text-emerald-400" },
                  ].map(m => (
                    <div key={m.label} className="rounded-md bg-muted/30 p-2.5">
                      <div className="text-[10px] text-muted-foreground">{m.label}</div>
                      <div className={`font-mono font-bold text-sm ${m.color}`}>{m.value}</div>
                    </div>
                  ))}
                </div>
                <div className="space-y-2 text-xs">
                  <div className="flex items-center justify-between">
                    <span className="text-muted-foreground">Reporting threshold</span>
                    <span className="font-mono text-foreground">25,000 tCO₂e/yr</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-muted-foreground">Current annualized rate</span>
                    <span className="font-mono text-amber-400">{(totalGHG * 4).toLocaleString()} tCO₂e/yr</span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-muted-foreground">Reporting required</span>
                    <span className="font-mono text-emerald-400">YES — above threshold</span>
                  </div>
                </div>
                <Button
                  className="w-full bg-amber-600 hover:bg-amber-700 text-white text-xs h-8"
                  onClick={() => toast.success("EPA e-GGRT XML package generated", { description: "Ready for submission to EPA Electronic Greenhouse Gas Reporting Tool" })}
                >
                  <Send className="w-3.5 h-3.5 mr-1.5" />
                  Generate EPA e-GGRT Submission
                </Button>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* Compliance Score tab */}
        <TabsContent value="compliance" className="mt-4 space-y-4">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <Card className="border-border/50">
              <CardHeader className="pb-2">
                <CardTitle className="font-[Syne] text-sm font-bold">Compliance Rate by Agency</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {COMPLIANCE_METRICS.map(m => <ComplianceBar key={m.agency} metric={m} />)}
                <div className="flex items-center gap-3 text-[10px] text-muted-foreground pt-2 border-t border-border/50">
                  <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-emerald-500 inline-block" />Submitted</span>
                  <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-amber-500 inline-block" />Pending</span>
                  <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-red-500 inline-block" />Overdue</span>
                </div>
              </CardContent>
            </Card>

            <Card className="border-border/50">
              <CardHeader className="pb-2">
                <CardTitle className="font-[Syne] text-sm font-bold">Upcoming Deadlines</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  {MOCK_REPORTS
                    .filter(r => r.status !== "SUBMITTED")
                    .sort((a, b) => new Date(a.due_date).getTime() - new Date(b.due_date).getTime())
                    .map(r => {
                      const days = daysUntilDue(r.due_date);
                      const tc = typeConfig(r.type);
                      return (
                        <div key={r.report_id} className="flex items-center justify-between gap-2 py-2 border-b border-border/30 last:border-0">
                          <div>
                            <div className="text-xs font-medium text-foreground">{r.title}</div>
                            <div className={`text-[10px] font-mono ${tc.color}`}>{tc.label}</div>
                          </div>
                          <div className="text-right shrink-0">
                            <div className="text-xs text-muted-foreground">{r.due_date}</div>
                            <div className={`text-[10px] font-mono font-bold ${days < 0 ? "text-red-400" : days < 7 ? "text-amber-400" : "text-muted-foreground"}`}>
                              {days < 0 ? `${Math.abs(days)}d overdue` : `${days}d left`}
                            </div>
                          </div>
                        </div>
                      );
                    })}
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* Submission History tab */}
        <TabsContent value="history" className="mt-4">
          <SubmissionHistoryPanel />
        </TabsContent>
        <TabsContent value="calendar" className="mt-4">
          <RegulatoryCalendar />
        </TabsContent>
      </Tabs>
    </div>
  );
}

// ── Submission History Panel ──────────────────────────────────────────────────

function SubmissionHistoryPanel() {
  const { user } = useAuth();
  const isAdmin = (user as any)?.role === "admin";
  const { data: history, isLoading, refetch } = trpc.regulatory.submissionHistory.useQuery({ limit: 100 });
  const resubmitMutation = trpc.regulatory.resubmit.useMutation({
    onSuccess: (data) => {
      toast.success("Re-submitted successfully", { description: data.message });
      refetch();
    },
    onError: (err) => toast.error("Re-submit failed", { description: err.message }),
  });
  const updateStatusMutation = trpc.regulatory.updateSubmissionStatus.useMutation({
    onSuccess: (data) => {
      toast.success(`Status updated to ${data.status}`, { description: data.message });
      refetch();
    },
    onError: (err) => toast.error("Status update failed", { description: err.message }),
  });

  const statusBadge = (status: string) => {
    if (status === "ACCEPTED") return <Badge className="bg-emerald-600/20 text-emerald-400 border-emerald-600/30 text-xs">Accepted</Badge>;
    if (status === "REJECTED") return <Badge className="bg-rose-600/20 text-rose-400 border-rose-600/30 text-xs">Rejected</Badge>;
    return <Badge className="bg-amber-600/20 text-amber-400 border-amber-600/30 text-xs">Submitted</Badge>;
  };

  const authorityFromRef = (ref: string | null) => {
    if (!ref) return "—";
    const prefix = ref.split("-")[0];
    const map: Record<string, string> = {
      ADN: "ADNOC", KOC: "KOC", SAR: "ARAMCO",
      MOC: "MOCCAE", BSE: "BSEE", EPA: "EPA", NCS: "NCSC",
    };
    return map[prefix] ?? prefix;
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-12">
        <RefreshCw className="w-5 h-5 animate-spin text-amber-500 mr-2" />
        <span className="text-sm text-muted-foreground">Loading submission history...</span>
      </div>
    );
  }

  if (!history || history.length === 0) {
    return (
      <Card className="border-border/50">
        <CardContent className="py-12 text-center">
          <Send className="w-8 h-8 text-muted-foreground mx-auto mb-3" />
          <p className="text-sm text-muted-foreground">No submitted reports yet.</p>
          <p className="text-xs text-muted-foreground mt-1">Generate a report and click Submit to see history here.</p>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="border-border/50">
      <CardHeader className="pb-3">
        <CardTitle className="font-[Syne] text-sm font-bold flex items-center gap-2">
          <Send className="w-4 h-4 text-amber-500" />
          Submission History
          <Badge variant="outline" className="text-xs ml-1">{history.length}</Badge>
        </CardTitle>
      </CardHeader>
      <CardContent className="p-0">
        <div className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead>
              <tr className="border-b border-border/50 bg-muted/20">
                {["Report ID", "Type", "Period", "Authority", "Ref #", "Submitted", "Status", ""].map(h => (
                  <th key={h} className="text-left px-4 py-2 text-muted-foreground font-medium">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {history.map(row => (
                <tr key={row.id} className="border-b border-border/30 hover:bg-muted/10 transition-colors">
                  <td className="px-4 py-2.5 font-mono text-amber-400/80">{row.reportId}</td>
                  <td className="px-4 py-2.5 text-muted-foreground">{row.reportType.replace(/_/g, " ")}</td>
                  <td className="px-4 py-2.5">{row.period}</td>
                  <td className="px-4 py-2.5">{authorityFromRef(row.submissionRef ?? null)}</td>
                  <td className="px-4 py-2.5 font-mono text-xs text-muted-foreground">
                    {row.submissionRef ?? "—"}
                  </td>
                  <td className="px-4 py-2.5 text-muted-foreground">
                    {row.submittedAt ? new Date(row.submittedAt).toLocaleDateString() : "—"}
                  </td>
                  <td className="px-4 py-2.5">{statusBadge(row.status)}</td>
                  <td className="px-4 py-2.5">
                    <div className="flex items-center gap-1 flex-wrap">
                      {row.status === "REJECTED" && (
                        <Button
                          size="sm"
                          variant="outline"
                          className="h-6 text-xs px-2 border-amber-600/40 text-amber-400 hover:bg-amber-600/10"
                          disabled={resubmitMutation.isPending}
                          onClick={() => resubmitMutation.mutate({
                            id: row.id,
                            authority: (authorityFromRef(row.submissionRef ?? null) as any) || "ADNOC",
                          })}
                        >
                          {resubmitMutation.isPending ? <RefreshCw className="w-3 h-3 animate-spin" /> : <Send className="w-3 h-3" />}
                          <span className="ml-1">Re-submit</span>
                        </Button>
                      )}
                      {row.fileUrl && (
                        <a href={row.fileUrl} target="_blank" rel="noopener noreferrer">
                          <Button size="sm" variant="ghost" className="h-6 text-xs px-2 text-muted-foreground hover:text-foreground">
                            <ExternalLink className="w-3 h-3" />
                          </Button>
                        </a>
                      )}
                      {/* Admin-only status simulation buttons */}
                      {isAdmin && row.status === "SUBMITTED" && (
                        <>
                          <Button
                            size="sm"
                            variant="ghost"
                            className="h-6 text-xs px-2 text-emerald-400 hover:bg-emerald-600/10 border border-emerald-700/30"
                            disabled={updateStatusMutation.isPending}
                            onClick={() => updateStatusMutation.mutate({ id: row.id, status: "ACCEPTED" })}
                            title="Admin: Mark as Accepted"
                          >
                            <CheckCircle2 className="w-3 h-3 mr-1" />
                            Accept
                          </Button>
                          <Button
                            size="sm"
                            variant="ghost"
                            className="h-6 text-xs px-2 text-rose-400 hover:bg-rose-600/10 border border-rose-700/30"
                            disabled={updateStatusMutation.isPending}
                            onClick={() => updateStatusMutation.mutate({ id: row.id, status: "REJECTED", notes: "Rejected by admin (simulation)" })}
                            title="Admin: Mark as Rejected"
                          >
                            <AlertTriangle className="w-3 h-3 mr-1" />
                            Reject
                          </Button>
                        </>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </CardContent>
    </Card>
  );
}

// ── Regulatory Calendar ───────────────────────────────────────────────────────
function RegulatoryCalendar() {
  const { data: calendarItems, isLoading } = trpc.regulatory.calendarData.useQuery();
  const [viewMonth, setViewMonth] = useState(() => {
    const now = new Date();
    return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
  });

  const [viewYear, viewMonthNum] = viewMonth.split("-").map(Number);

  const daysInMonth = new Date(viewYear, viewMonthNum, 0).getDate();
  const firstDayOfWeek = new Date(viewYear, viewMonthNum - 1, 1).getDay();

  // Group items by day
  const byDay: Record<number, typeof calendarItems> = {};
  (calendarItems ?? []).forEach((item: any) => {
    if (!item.dueDate) return;
    const d = new Date(item.dueDate);
    if (d.getFullYear() === viewYear && d.getMonth() + 1 === viewMonthNum) {
      const day = d.getDate();
      if (!byDay[day]) byDay[day] = [];
      byDay[day]!.push(item);
    }
  });

  const statusColor = (status: string) => {
    if (status === "SUBMITTED" || status === "ACCEPTED") return "bg-emerald-500/20 text-emerald-400 border-emerald-700/40";
    if (status === "REJECTED") return "bg-red-500/20 text-red-400 border-red-700/40";
    const dueDate = new Date();
    return "bg-amber-500/20 text-amber-400 border-amber-700/40";
  };

  const prevMonth = () => {
    const d = new Date(viewYear, viewMonthNum - 2, 1);
    setViewMonth(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`);
  };
  const nextMonth = () => {
    const d = new Date(viewYear, viewMonthNum, 1);
    setViewMonth(`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`);
  };

  const monthName = new Date(viewYear, viewMonthNum - 1, 1).toLocaleString("default", { month: "long", year: "numeric" });

  return (
    <Card className="border-border/50">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <CardTitle className="text-base flex items-center gap-2">
            <Calendar className="w-4 h-4 text-amber-500" />
            Regulatory Calendar — {monthName}
          </CardTitle>
          <div className="flex gap-2">
            <Button size="sm" variant="outline" className="h-7 text-xs" onClick={prevMonth}>‹ Prev</Button>
            <Button size="sm" variant="outline" className="h-7 text-xs" onClick={nextMonth}>Next ›</Button>
          </div>
        </div>
        <div className="flex gap-3 text-xs text-muted-foreground mt-1">
          <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-emerald-500" />Submitted/Accepted</span>
          <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-amber-500" />Due Soon/Draft</span>
          <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-red-500" />Overdue/Rejected</span>
        </div>
      </CardHeader>
      <CardContent>
        {isLoading && <p className="text-sm text-muted-foreground">Loading calendar…</p>}
        {!isLoading && (
          <div className="grid grid-cols-7 gap-1">
            {["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d => (
              <div key={d} className="text-center text-xs text-muted-foreground font-medium py-1">{d}</div>
            ))}
            {Array.from({ length: firstDayOfWeek }).map((_, i) => (
              <div key={`empty-${i}`} />
            ))}
            {Array.from({ length: daysInMonth }).map((_, i) => {
              const day = i + 1;
              const items = byDay[day] ?? [];
              const isToday = new Date().getDate() === day &&
                new Date().getMonth() + 1 === viewMonthNum &&
                new Date().getFullYear() === viewYear;
              return (
                <div key={day} className={`min-h-[64px] rounded border p-1 ${isToday ? "border-amber-500/60 bg-amber-950/20" : "border-border/30 bg-card/30"}`}>
                  <div className={`text-xs font-medium mb-1 ${isToday ? "text-amber-400" : "text-muted-foreground"}`}>{day}</div>
                  {items.slice(0, 2).map((item: any) => (
                    <div key={item.id} className={`text-xs px-1 py-0.5 rounded border mb-0.5 truncate ${statusColor(item.status)}`}
                      title={`${item.reportType} — ${item.status}`}>
                      {item.reportType?.replace("_", " ")}
                    </div>
                  ))}
                  {items.length > 2 && (
                    <div className="text-xs text-muted-foreground">+{items.length - 2} more</div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
