apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: banking-secretstore
  namespace: banking-crm
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: namespace
    value: "banking-crm"
scopes:
  - banking-service
  - crm-service
  - customer-service
  - transaction-service
  - fraud-service
  - notification-service

