// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     underwriting_event.avsc
 */
package events

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type CaseCreatedPayload struct {
	// JSON string of the applicant's data.
	Applicant_data_json string `json:"applicant_data_json"`
}

const CaseCreatedPayloadAvroCRC64Fingerprint = "\xe1\xe4\x8f|5C\x1c\xdf"

func NewCaseCreatedPayload() CaseCreatedPayload {
	r := CaseCreatedPayload{}
	return r
}

func DeserializeCaseCreatedPayload(r io.Reader) (CaseCreatedPayload, error) {
	t := NewCaseCreatedPayload()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeCaseCreatedPayloadFromSchema(r io.Reader, schema string) (CaseCreatedPayload, error) {
	t := NewCaseCreatedPayload()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeCaseCreatedPayload(r CaseCreatedPayload, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Applicant_data_json, w)
	if err != nil {
		return err
	}
	return err
}

func (r CaseCreatedPayload) Serialize(w io.Writer) error {
	return writeCaseCreatedPayload(r, w)
}

func (r CaseCreatedPayload) Schema() string {
	return "{\"fields\":[{\"doc\":\"JSON string of the applicant's data.\",\"name\":\"applicant_data_json\",\"type\":\"string\"}],\"name\":\"com.openimis.insurance.underwriting.CaseCreatedPayload\",\"type\":\"record\"}"
}

func (r CaseCreatedPayload) SchemaName() string {
	return "com.openimis.insurance.underwriting.CaseCreatedPayload"
}

func (_ CaseCreatedPayload) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ CaseCreatedPayload) SetInt(v int32)       { panic("Unsupported operation") }
func (_ CaseCreatedPayload) SetLong(v int64)      { panic("Unsupported operation") }
func (_ CaseCreatedPayload) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ CaseCreatedPayload) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ CaseCreatedPayload) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ CaseCreatedPayload) SetString(v string)   { panic("Unsupported operation") }
func (_ CaseCreatedPayload) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *CaseCreatedPayload) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.Applicant_data_json}

		return w

	}
	panic("Unknown field index")
}

func (r *CaseCreatedPayload) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *CaseCreatedPayload) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ CaseCreatedPayload) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ CaseCreatedPayload) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ CaseCreatedPayload) HintSize(int)                     { panic("Unsupported operation") }
func (_ CaseCreatedPayload) Finalize()                        {}

func (_ CaseCreatedPayload) AvroCRC64Fingerprint() []byte {
	return []byte(CaseCreatedPayloadAvroCRC64Fingerprint)
}

func (r CaseCreatedPayload) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["applicant_data_json"], err = json.Marshal(r.Applicant_data_json)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *CaseCreatedPayload) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["applicant_data_json"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Applicant_data_json); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for applicant_data_json")
	}
	return nil
}
