// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     underwriting_event.avsc
 */
package events

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type Decision int32

const (
	DecisionAPPROVED Decision = 0
	DecisionREJECTED Decision = 1
)

func (e Decision) String() string {
	switch e {
	case DecisionAPPROVED:
		return "APPROVED"
	case DecisionREJECTED:
		return "REJECTED"
	}
	return "unknown"
}

func writeDecision(r Decision, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewDecisionValue(raw string) (r Decision, err error) {
	switch raw {
	case "APPROVED":
		return DecisionAPPROVED, nil
	case "REJECTED":
		return DecisionREJECTED, nil
	}

	return -1, fmt.Errorf("invalid value for Decision: '%s'", raw)

}

func (b Decision) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *Decision) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewDecisionValue(stringVal)
	*b = val
	return err
}

type DecisionWrapper struct {
	Target *Decision
}

func (b DecisionWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b DecisionWrapper) SetInt(v int32) {
	*(b.Target) = Decision(v)
}

func (b DecisionWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b DecisionWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b DecisionWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b DecisionWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b DecisionWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b DecisionWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b DecisionWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b DecisionWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b DecisionWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b DecisionWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b DecisionWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b DecisionWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b DecisionWrapper) Finalize() {}
