// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     underwriting_event.avsc
 */
package events

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type ManualReviewPayload struct {
	// Reason for manual review.
	Reason string `json:"reason"`
}

const ManualReviewPayloadAvroCRC64Fingerprint = "Q%\xa3#\x8c\xfc\x0f\x19"

func NewManualReviewPayload() ManualReviewPayload {
	r := ManualReviewPayload{}
	return r
}

func DeserializeManualReviewPayload(r io.Reader) (ManualReviewPayload, error) {
	t := NewManualReviewPayload()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeManualReviewPayloadFromSchema(r io.Reader, schema string) (ManualReviewPayload, error) {
	t := NewManualReviewPayload()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeManualReviewPayload(r ManualReviewPayload, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Reason, w)
	if err != nil {
		return err
	}
	return err
}

func (r ManualReviewPayload) Serialize(w io.Writer) error {
	return writeManualReviewPayload(r, w)
}

func (r ManualReviewPayload) Schema() string {
	return "{\"fields\":[{\"doc\":\"Reason for manual review.\",\"name\":\"reason\",\"type\":\"string\"}],\"name\":\"com.openimis.insurance.underwriting.ManualReviewPayload\",\"type\":\"record\"}"
}

func (r ManualReviewPayload) SchemaName() string {
	return "com.openimis.insurance.underwriting.ManualReviewPayload"
}

func (_ ManualReviewPayload) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ ManualReviewPayload) SetInt(v int32)       { panic("Unsupported operation") }
func (_ ManualReviewPayload) SetLong(v int64)      { panic("Unsupported operation") }
func (_ ManualReviewPayload) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ ManualReviewPayload) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ ManualReviewPayload) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ ManualReviewPayload) SetString(v string)   { panic("Unsupported operation") }
func (_ ManualReviewPayload) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *ManualReviewPayload) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.Reason}

		return w

	}
	panic("Unknown field index")
}

func (r *ManualReviewPayload) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *ManualReviewPayload) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ ManualReviewPayload) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ManualReviewPayload) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ ManualReviewPayload) HintSize(int)                     { panic("Unsupported operation") }
func (_ ManualReviewPayload) Finalize()                        {}

func (_ ManualReviewPayload) AvroCRC64Fingerprint() []byte {
	return []byte(ManualReviewPayloadAvroCRC64Fingerprint)
}

func (r ManualReviewPayload) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["reason"], err = json.Marshal(r.Reason)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *ManualReviewPayload) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["reason"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Reason); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for reason")
	}
	return nil
}
