// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     underwriting_event.avsc
 */
package events

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type UnderwritingEvent struct {
	// Unique identifier for the event (UUID).
	Event_id string `json:"event_id"`
	// Type of the underwriting event.
	Event_type UnderwritingEventType `json:"event_type"`
	// Identifier for the underwriting case.
	Case_id string `json:"case_id"`
	// Identifier for the related insurance policy.
	Policy_id string `json:"policy_id"`
	// Event creation timestamp (Unix epoch in milliseconds).
	Timestamp int64 `json:"timestamp"`
	// Specific data payload based on the event type.
	Payload *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload `json:"payload"`
}

const UnderwritingEventAvroCRC64Fingerprint = "\x8ft\xae-\x1f\x8e\x12\x02"

func NewUnderwritingEvent() UnderwritingEvent {
	r := UnderwritingEvent{}
	return r
}

func DeserializeUnderwritingEvent(r io.Reader) (UnderwritingEvent, error) {
	t := NewUnderwritingEvent()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeUnderwritingEventFromSchema(r io.Reader, schema string) (UnderwritingEvent, error) {
	t := NewUnderwritingEvent()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeUnderwritingEvent(r UnderwritingEvent, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Event_id, w)
	if err != nil {
		return err
	}
	err = writeUnderwritingEventType(r.Event_type, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Case_id, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Policy_id, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.Timestamp, w)
	if err != nil {
		return err
	}
	err = writeUnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload(r.Payload, w)
	if err != nil {
		return err
	}
	return err
}

func (r UnderwritingEvent) Serialize(w io.Writer) error {
	return writeUnderwritingEvent(r, w)
}

func (r UnderwritingEvent) Schema() string {
	return "{\"fields\":[{\"doc\":\"Unique identifier for the event (UUID).\",\"name\":\"event_id\",\"type\":\"string\"},{\"doc\":\"Type of the underwriting event.\",\"name\":\"event_type\",\"type\":{\"name\":\"UnderwritingEventType\",\"symbols\":[\"CASE_CREATED\",\"DECISION_MADE\",\"MANUAL_REVIEW\"],\"type\":\"enum\"}},{\"doc\":\"Identifier for the underwriting case.\",\"name\":\"case_id\",\"type\":\"string\"},{\"doc\":\"Identifier for the related insurance policy.\",\"name\":\"policy_id\",\"type\":\"string\"},{\"doc\":\"Event creation timestamp (Unix epoch in milliseconds).\",\"name\":\"timestamp\",\"type\":\"long\"},{\"doc\":\"Specific data payload based on the event type.\",\"name\":\"payload\",\"type\":[\"null\",{\"fields\":[{\"doc\":\"JSON string of the applicant's data.\",\"name\":\"applicant_data_json\",\"type\":\"string\"}],\"name\":\"CaseCreatedPayload\",\"type\":\"record\"},{\"fields\":[{\"doc\":\"The final underwriting decision.\",\"name\":\"decision\",\"type\":{\"name\":\"Decision\",\"symbols\":[\"APPROVED\",\"REJECTED\"],\"type\":\"enum\"}},{\"doc\":\"The calculated risk score.\",\"name\":\"risk_score\",\"type\":\"double\"},{\"doc\":\"Version of the risk model used.\",\"name\":\"risk_model_version\",\"type\":\"string\"}],\"name\":\"DecisionMadePayload\",\"type\":\"record\"},{\"fields\":[{\"doc\":\"Reason for manual review.\",\"name\":\"reason\",\"type\":\"string\"}],\"name\":\"ManualReviewPayload\",\"type\":\"record\"}]}],\"name\":\"com.openimis.insurance.underwriting.UnderwritingEvent\",\"type\":\"record\"}"
}

func (r UnderwritingEvent) SchemaName() string {
	return "com.openimis.insurance.underwriting.UnderwritingEvent"
}

func (_ UnderwritingEvent) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ UnderwritingEvent) SetInt(v int32)       { panic("Unsupported operation") }
func (_ UnderwritingEvent) SetLong(v int64)      { panic("Unsupported operation") }
func (_ UnderwritingEvent) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ UnderwritingEvent) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ UnderwritingEvent) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ UnderwritingEvent) SetString(v string)   { panic("Unsupported operation") }
func (_ UnderwritingEvent) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *UnderwritingEvent) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.Event_id}

		return w

	case 1:
		w := UnderwritingEventTypeWrapper{Target: &r.Event_type}

		return w

	case 2:
		w := types.String{Target: &r.Case_id}

		return w

	case 3:
		w := types.String{Target: &r.Policy_id}

		return w

	case 4:
		w := types.Long{Target: &r.Timestamp}

		return w

	case 5:
		r.Payload = NewUnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload()

		return r.Payload
	}
	panic("Unknown field index")
}

func (r *UnderwritingEvent) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *UnderwritingEvent) NullField(i int) {
	switch i {
	case 5:
		r.Payload = nil
		return
	}
	panic("Not a nullable field index")
}

func (_ UnderwritingEvent) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ UnderwritingEvent) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ UnderwritingEvent) HintSize(int)                     { panic("Unsupported operation") }
func (_ UnderwritingEvent) Finalize()                        {}

func (_ UnderwritingEvent) AvroCRC64Fingerprint() []byte {
	return []byte(UnderwritingEventAvroCRC64Fingerprint)
}

func (r UnderwritingEvent) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["event_id"], err = json.Marshal(r.Event_id)
	if err != nil {
		return nil, err
	}
	output["event_type"], err = json.Marshal(r.Event_type)
	if err != nil {
		return nil, err
	}
	output["case_id"], err = json.Marshal(r.Case_id)
	if err != nil {
		return nil, err
	}
	output["policy_id"], err = json.Marshal(r.Policy_id)
	if err != nil {
		return nil, err
	}
	output["timestamp"], err = json.Marshal(r.Timestamp)
	if err != nil {
		return nil, err
	}
	output["payload"], err = json.Marshal(r.Payload)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *UnderwritingEvent) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["event_id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Event_id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for event_id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["event_type"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Event_type); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for event_type")
	}
	val = func() json.RawMessage {
		if v, ok := fields["case_id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Case_id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for case_id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["policy_id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Policy_id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for policy_id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["timestamp"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Timestamp); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for timestamp")
	}
	val = func() json.RawMessage {
		if v, ok := fields["payload"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Payload); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for payload")
	}
	return nil
}
