// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     underwriting_event.avsc
 */
package events

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type UnderwritingEventType int32

const (
	UnderwritingEventTypeCASE_CREATED  UnderwritingEventType = 0
	UnderwritingEventTypeDECISION_MADE UnderwritingEventType = 1
	UnderwritingEventTypeMANUAL_REVIEW UnderwritingEventType = 2
)

func (e UnderwritingEventType) String() string {
	switch e {
	case UnderwritingEventTypeCASE_CREATED:
		return "CASE_CREATED"
	case UnderwritingEventTypeDECISION_MADE:
		return "DECISION_MADE"
	case UnderwritingEventTypeMANUAL_REVIEW:
		return "MANUAL_REVIEW"
	}
	return "unknown"
}

func writeUnderwritingEventType(r UnderwritingEventType, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewUnderwritingEventTypeValue(raw string) (r UnderwritingEventType, err error) {
	switch raw {
	case "CASE_CREATED":
		return UnderwritingEventTypeCASE_CREATED, nil
	case "DECISION_MADE":
		return UnderwritingEventTypeDECISION_MADE, nil
	case "MANUAL_REVIEW":
		return UnderwritingEventTypeMANUAL_REVIEW, nil
	}

	return -1, fmt.Errorf("invalid value for UnderwritingEventType: '%s'", raw)

}

func (b UnderwritingEventType) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *UnderwritingEventType) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewUnderwritingEventTypeValue(stringVal)
	*b = val
	return err
}

type UnderwritingEventTypeWrapper struct {
	Target *UnderwritingEventType
}

func (b UnderwritingEventTypeWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b UnderwritingEventTypeWrapper) SetInt(v int32) {
	*(b.Target) = UnderwritingEventType(v)
}

func (b UnderwritingEventTypeWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b UnderwritingEventTypeWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b UnderwritingEventTypeWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b UnderwritingEventTypeWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b UnderwritingEventTypeWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b UnderwritingEventTypeWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b UnderwritingEventTypeWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b UnderwritingEventTypeWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b UnderwritingEventTypeWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b UnderwritingEventTypeWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b UnderwritingEventTypeWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b UnderwritingEventTypeWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b UnderwritingEventTypeWrapper) Finalize() {}
