// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     underwriting_event.avsc
 */
package events

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

type UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayloadTypeEnum int

const (
	UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayloadTypeEnumCaseCreatedPayload UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayloadTypeEnum = 1

	UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayloadTypeEnumDecisionMadePayload UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayloadTypeEnum = 2

	UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayloadTypeEnumManualReviewPayload UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayloadTypeEnum = 3
)

type UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload struct {
	Null                *types.NullVal
	CaseCreatedPayload  CaseCreatedPayload
	DecisionMadePayload DecisionMadePayload
	ManualReviewPayload ManualReviewPayload
	UnionType           UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayloadTypeEnum
}

func writeUnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload(r *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayloadTypeEnumCaseCreatedPayload:
		return writeCaseCreatedPayload(r.CaseCreatedPayload, w)
	case UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayloadTypeEnumDecisionMadePayload:
		return writeDecisionMadePayload(r.DecisionMadePayload, w)
	case UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayloadTypeEnumManualReviewPayload:
		return writeManualReviewPayload(r.ManualReviewPayload, w)
	}
	return fmt.Errorf("invalid value for *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload")
}

func NewUnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload() *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload {
	return &UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload{}
}

func (r *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) Serialize(w io.Writer) error {
	return writeUnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload(r, w)
}

func DeserializeUnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload(r io.Reader) (*UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload, error) {
	t := NewUnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func DeserializeUnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayloadFromSchema(r io.Reader, schema string) (*UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload, error) {
	t := NewUnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload()
	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, t)

	if err != nil {
		return t, err
	}
	return t, err
}

func (r *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) Schema() string {
	return "[\"null\",{\"fields\":[{\"doc\":\"JSON string of the applicant's data.\",\"name\":\"applicant_data_json\",\"type\":\"string\"}],\"name\":\"CaseCreatedPayload\",\"type\":\"record\"},{\"fields\":[{\"doc\":\"The final underwriting decision.\",\"name\":\"decision\",\"type\":{\"name\":\"Decision\",\"symbols\":[\"APPROVED\",\"REJECTED\"],\"type\":\"enum\"}},{\"doc\":\"The calculated risk score.\",\"name\":\"risk_score\",\"type\":\"double\"},{\"doc\":\"Version of the risk model used.\",\"name\":\"risk_model_version\",\"type\":\"string\"}],\"name\":\"DecisionMadePayload\",\"type\":\"record\"},{\"fields\":[{\"doc\":\"Reason for manual review.\",\"name\":\"reason\",\"type\":\"string\"}],\"name\":\"ManualReviewPayload\",\"type\":\"record\"}]"
}

func (_ *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) SetBoolean(v bool) {
	panic("Unsupported operation")
}
func (_ *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) SetInt(v int32) {
	panic("Unsupported operation")
}
func (_ *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) SetFloat(v float32) {
	panic("Unsupported operation")
}
func (_ *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) SetDouble(v float64) {
	panic("Unsupported operation")
}
func (_ *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) SetBytes(v []byte) {
	panic("Unsupported operation")
}
func (_ *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) SetString(v string) {
	panic("Unsupported operation")
}

func (r *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) SetLong(v int64) {

	r.UnionType = (UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayloadTypeEnum)(v)
}

func (r *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) Get(i int) types.Field {

	switch i {
	case 0:
		return r.Null
	case 1:
		r.CaseCreatedPayload = NewCaseCreatedPayload()
		return &types.Record{Target: (&r.CaseCreatedPayload)}
	case 2:
		r.DecisionMadePayload = NewDecisionMadePayload()
		return &types.Record{Target: (&r.DecisionMadePayload)}
	case 3:
		r.ManualReviewPayload = NewManualReviewPayload()
		return &types.Record{Target: (&r.ManualReviewPayload)}
	}
	panic("Unknown field index")
}
func (_ *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) NullField(i int) {
	panic("Unsupported operation")
}
func (_ *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) HintSize(i int) {
	panic("Unsupported operation")
}
func (_ *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) SetDefault(i int) {
	panic("Unsupported operation")
}
func (_ *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) AppendMap(key string) types.Field {
	panic("Unsupported operation")
}
func (_ *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) AppendArray() types.Field {
	panic("Unsupported operation")
}
func (_ *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) Finalize() {}

func (r *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) MarshalJSON() ([]byte, error) {

	if r == nil {
		return []byte("null"), nil
	}

	switch r.UnionType {
	case UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayloadTypeEnumCaseCreatedPayload:
		return json.Marshal(map[string]interface{}{"com.openimis.insurance.underwriting.CaseCreatedPayload": r.CaseCreatedPayload})
	case UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayloadTypeEnumDecisionMadePayload:
		return json.Marshal(map[string]interface{}{"com.openimis.insurance.underwriting.DecisionMadePayload": r.DecisionMadePayload})
	case UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayloadTypeEnumManualReviewPayload:
		return json.Marshal(map[string]interface{}{"com.openimis.insurance.underwriting.ManualReviewPayload": r.ManualReviewPayload})
	}
	return nil, fmt.Errorf("invalid value for *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload")
}

func (r *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload) UnmarshalJSON(data []byte) error {

	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if len(fields) > 1 {
		return fmt.Errorf("more than one type supplied for union")
	}
	if value, ok := fields["com.openimis.insurance.underwriting.CaseCreatedPayload"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.CaseCreatedPayload)
	}
	if value, ok := fields["com.openimis.insurance.underwriting.DecisionMadePayload"]; ok {
		r.UnionType = 2
		return json.Unmarshal([]byte(value), &r.DecisionMadePayload)
	}
	if value, ok := fields["com.openimis.insurance.underwriting.ManualReviewPayload"]; ok {
		r.UnionType = 3
		return json.Unmarshal([]byte(value), &r.ManualReviewPayload)
	}
	return fmt.Errorf("invalid value for *UnionNullCaseCreatedPayloadDecisionMadePayloadManualReviewPayload")
}
