package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"sync"
	"time"
)

var (
	mu   sync.RWMutex
	data = [{"id": "SAR-2026-001", "customerId": "CUS-1045", "customerName": "Suspicious Transfers Ltd", "reportType": "SAR", "reason": "Structured transactions below \u20a65M CTR threshold over 5-day rolling window", "amount": 24500000, "currency": "NGN", "transactionsInvolved": 6, "period": "2026-04-10 to 2026-04-15", "filedTo": "NFIU", "nfiuReference": "NFIU/SAR/2026/04512", "cbnReference": "CBN/SAR/2026/0451", "status": "filed", "filedDate": "2026-04-16", "dueDate": "2026-04-17", "assignedTo": "Compliance Officer A", "priority": "high", "autoGenerated": true}, {"id": "SAR-2026-002", "customerId": "CUS-3021", "customerName": "ABC Import Export", "reportType": "SAR", "reason": "Trade-based money laundering indicators \u2014 over-invoicing on LC imports from high-risk jurisdiction", "amount": 150000000, "currency": "NGN", "transactionsInvolved": 12, "period": "2026-03-01 to 2026-03-20", "filedTo": "NFIU", "nfiuReference": "NFIU/SAR/2026/03215", "cbnReference": "CBN/SAR/2026/0321", "status": "escalated", "filedDate": "2026-03-21", "dueDate": "2026-03-22", "assignedTo": "MLRO", "priority": "critical", "autoGenerated": true}, {"id": "SAR-2026-003", "customerId": "CUS-2089", "customerName": "John Doe", "reportType": "STR", "reason": "Rapid movement of funds through 4 accounts within 6 hours \u2014 95% of credited amount transferred out", "amount": 25000000, "currency": "NGN", "transactionsInvolved": 8, "period": "2026-04-28 to 2026-04-28", "filedTo": "NFIU", "nfiuReference": "NFIU/STR/2026/05120", "cbnReference": "CBN/STR/2026/0512", "status": "under_review", "filedDate": "2026-05-01", "dueDate": "2026-05-02", "assignedTo": "Compliance Officer B", "priority": "high", "autoGenerated": true}]
)

func main() {
	port := os.Getenv("PORT")
	if port == "" { port = "8575" }
	mux := http.NewServeMux()

	mux.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]interface{}{
			"service": "sar-filing",
			"status":  "healthy",
			"version": "1.0.0",
			"uptime":  time.Now().Format(time.RFC3339),
			"middleware": json.RawMessage(`{"kafka": {"broker": "kafka:9092", "topics": ["aml-events", "kyc-screening", "compliance-alerts"]}, "dapr": {"appId": "sar-filing-engine-go", "pubsub": "redis-pubsub"}, "fluvio": {"topic": "aml-stream", "partitions": 6}, "temporal": {"namespace": "aml-compliance", "taskQueue": "aml-tasks"}, "postgres": {"host": "postgres", "port": 5432, "database": "bank54"}, "keycloak": {"realm": "54bank", "clientId": "aml-service"}, "permify": {"schema": "aml-compliance", "version": "v1"}, "redis": {"host": "redis", "port": 6379, "db": 3}, "mojaloop": {"hub": "http://mojaloop:4000"}, "opensearch": {"host": "opensearch", "index": "aml-events"}, "openappsec": {"policy": "aml-protection"}, "apisix": {"upstream": "sar-filing-engine-go", "route": "/v1/sar-filing"}, "tigerbeetle": {"cluster": "0", "addresses": ["tigerbeetle:3001"]}, "lakehouse": {"catalog": "aml_catalog", "warehouse": "s3://54bank-aml"}}`),
		})
	})

	mux.HandleFunc("/v1/sar-filing/list", func(w http.ResponseWriter, r *http.Request) {
		mu.RLock()
		defer mu.RUnlock()
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]interface{}{"total": len(data), "sar_reports": data})
	})

	mux.HandleFunc("/v1/sar-filing/stats", func(w http.ResponseWriter, r *http.Request) {
		mu.RLock()
		defer mu.RUnlock()
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(map[string]interface{}{
			"total": len(data), "active": len(data),
			"service": "SAR Filing Engine", "lastUpdated": time.Now().Format(time.RFC3339),
		})
	})

	fmt.Printf("SAR Filing Engine running on :%s\n", port)
	if err := http.ListenAndServe(":"+port, mux); err != nil {
		log.Fatal(err)
	}
}
