export const seedBanks = [
  { code: "000001", name: "Sterling Bank", swift: "LOYDNGLA", nibssCode: "232", category: "commercial" },
  { code: "000002", name: "Keystone Bank", swift: "PLNINGLA", nibssCode: "082", category: "commercial" },
  { code: "000003", name: "First City Monument Bank", swift: "FCMBNGLA", nibssCode: "214", category: "commercial" },
  { code: "000004", name: "United Bank for Africa", swift: "LOYDNGLA", nibssCode: "033", category: "commercial" },
  { code: "000005", name: "Diamond Bank (Access)", swift: "DIAMNGLA", nibssCode: "063", category: "commercial" },
  { code: "000006", name: "Jaiz Bank", swift: "JAIZNGLA", nibssCode: "301", category: "non-interest" },
  { code: "000007", name: "Fidelity Bank", swift: "FIDTNGLA", nibssCode: "070", category: "commercial" },
  { code: "000008", name: "Polaris Bank", swift: "PLRINGLA", nibssCode: "076", category: "commercial" },
  { code: "000009", name: "Citi Bank", swift: "LOYDNGLA", nibssCode: "023", category: "international" },
  { code: "000010", name: "Ecobank", swift: "LOYDNGLA", nibssCode: "050", category: "commercial" },
  { code: "000011", name: "Unity Bank", swift: "UNTYNG", nibssCode: "215", category: "commercial" },
  { code: "000012", name: "Stanbic IBTC Bank", swift: "SBICNGLA", nibssCode: "221", category: "commercial" },
  { code: "000013", name: "GTBank", swift: "GTBING", nibssCode: "058", category: "commercial" },
  { code: "000014", name: "Access Bank", swift: "ABNGNGLA", nibssCode: "044", category: "commercial" },
  { code: "000015", name: "Zenith Bank", swift: "ZEIBNGLA", nibssCode: "057", category: "commercial" },
  { code: "000016", name: "First Bank of Nigeria", swift: "FBNINGLA", nibssCode: "011", category: "commercial" },
  { code: "000017", name: "Wema Bank", swift: "WLOYDNGLA", nibssCode: "035", category: "commercial" },
  { code: "000018", name: "Union Bank", swift: "UBNINGLA", nibssCode: "032", category: "commercial" },
  { code: "000019", name: "Enterprise Bank", swift: "LOYDNGLA", nibssCode: "084", category: "commercial" },
  { code: "000020", name: "Heritage Bank", swift: "HLOYDNGLA", nibssCode: "030", category: "commercial" },
  { code: "000021", name: "Standard Chartered", swift: "SCBLNGLA", nibssCode: "068", category: "international" },
  { code: "000022", name: "Suntrust Bank", swift: "STBINGLA", nibssCode: "100", category: "commercial" },
  { code: "000023", name: "Providus Bank", swift: "PRVDNGLA", nibssCode: "101", category: "commercial" },
  { code: "000024", name: "Globus Bank", swift: "GLBSNGLA", nibssCode: "103", category: "commercial" },
  { code: "000025", name: "Titan Trust Bank", swift: "TTBNGLA", nibssCode: "102", category: "commercial" },
];

export const seedCorridors = [
  { id: "NGN-USD", source: "NG", target: "US", sourceCurrency: "NGN", targetCurrency: "USD", rate: 0.000625, fee: 3500, minAmount: 5000, maxAmount: 50000000, status: "active" },
  { id: "NGN-GBP", source: "NG", target: "GB", sourceCurrency: "NGN", targetCurrency: "GBP", rate: 0.000493, fee: 4000, minAmount: 5000, maxAmount: 50000000, status: "active" },
  { id: "NGN-EUR", source: "NG", target: "EU", sourceCurrency: "NGN", targetCurrency: "EUR", rate: 0.000573, fee: 3800, minAmount: 5000, maxAmount: 50000000, status: "active" },
  { id: "NGN-GHS", source: "NG", target: "GH", sourceCurrency: "NGN", targetCurrency: "GHS", rate: 0.00753, fee: 1500, minAmount: 1000, maxAmount: 20000000, status: "active" },
  { id: "NGN-KES", source: "NG", target: "KE", sourceCurrency: "NGN", targetCurrency: "KES", rate: 0.0806, fee: 2000, minAmount: 1000, maxAmount: 20000000, status: "active" },
  { id: "NGN-ZAR", source: "NG", target: "ZA", sourceCurrency: "NGN", targetCurrency: "ZAR", rate: 0.0113, fee: 2500, minAmount: 1000, maxAmount: 30000000, status: "active" },
  { id: "USD-NGN", source: "US", target: "NG", sourceCurrency: "USD", targetCurrency: "NGN", rate: 1600.0, fee: 5.0, minAmount: 10, maxAmount: 50000, status: "active" },
  { id: "GBP-NGN", source: "GB", target: "NG", sourceCurrency: "GBP", targetCurrency: "NGN", rate: 2028.0, fee: 3.5, minAmount: 5, maxAmount: 50000, status: "active" },
  { id: "EUR-NGN", source: "EU", target: "NG", sourceCurrency: "EUR", targetCurrency: "NGN", rate: 1745.0, fee: 4.0, minAmount: 5, maxAmount: 50000, status: "active" },
];

export const seedTransactions = Array.from({ length: 50 }, (_, i) => ({
  id: `TXN-${String(i + 1).padStart(6, "0")}`,
  type: ["NIP", "NEFT", "NDD", "RTGS"][i % 4],
  amount: Math.round(Math.random() * 5000000) + 1000,
  currency: "NGN",
  senderBank: seedBanks[i % seedBanks.length].name,
  senderAccount: `${Math.floor(Math.random() * 9000000000) + 1000000000}`,
  recipientBank: seedBanks[(i + 5) % seedBanks.length].name,
  recipientAccount: `${Math.floor(Math.random() * 9000000000) + 1000000000}`,
  status: ["completed", "completed", "completed", "pending", "failed"][i % 5],
  createdAt: new Date(Date.now() - Math.random() * 30 * 86400000).toISOString(),
  fee: Math.round(Math.random() * 500) + 50,
  reference: `REF${Date.now()}${i}`,
  narration: `Payment for ${["school fees", "rent", "supplies", "salary", "utilities"][i % 5]}`,
}));

export const seedSettlements = Array.from({ length: 20 }, (_, i) => ({
  id: `STL-${String(i + 1).padStart(4, "0")}`,
  date: new Date(Date.now() - i * 86400000).toISOString().split("T")[0],
  bankCode: seedBanks[i % seedBanks.length].nibssCode,
  bankName: seedBanks[i % seedBanks.length].name,
  totalTransactions: Math.floor(Math.random() * 50000) + 1000,
  totalAmount: Math.round(Math.random() * 10000000000),
  netAmount: Math.round(Math.random() * 9000000000),
  fees: Math.round(Math.random() * 100000000),
  status: ["settled", "settled", "pending", "settled"][i % 4],
}));

export const seedFraudAlerts = [
  { id: "FRD-001", type: "velocity", severity: "high", description: "50+ transactions in 5 minutes from single account", account: "0012345678", bank: "GTBank", amount: 25000000, timestamp: new Date(Date.now() - 3600000).toISOString(), status: "investigating" },
  { id: "FRD-002", type: "amount_anomaly", severity: "critical", description: "Transaction 10x above account average", account: "0098765432", bank: "Access Bank", amount: 50000000, timestamp: new Date(Date.now() - 7200000).toISOString(), status: "blocked" },
  { id: "FRD-003", type: "geo_anomaly", severity: "medium", description: "Transaction from unregistered location", account: "0011223344", bank: "Zenith Bank", amount: 1500000, timestamp: new Date(Date.now() - 14400000).toISOString(), status: "resolved" },
  { id: "FRD-004", type: "sanctions_hit", severity: "critical", description: "Beneficiary matches OFAC SDN list", account: "0055667788", bank: "First Bank", amount: 35000000, timestamp: new Date(Date.now() - 86400000).toISOString(), status: "blocked" },
  { id: "FRD-005", type: "mule_network", severity: "high", description: "Fan-out pattern detected — 1 sender to 20+ recipients", account: "0099887766", bank: "UBA", amount: 15000000, timestamp: new Date(Date.now() - 172800000).toISOString(), status: "investigating" },
];

export const seedBranches = [
  { id: "BR-001", name: "Lagos Main Branch", code: "LOS-001", region: "Lagos", address: "1 Marina Road, Lagos Island", staff: 45, status: "active" },
  { id: "BR-002", name: "Abuja Federal Branch", code: "ABJ-001", region: "Abuja", address: "Plot 1234, Wuse II, Abuja", staff: 32, status: "active" },
  { id: "BR-003", name: "Kano Northern Branch", code: "KAN-001", region: "Kano", address: "15 Bompai Road, Kano", staff: 28, status: "active" },
  { id: "BR-004", name: "Port Harcourt Branch", code: "PHC-001", region: "Rivers", address: "45 Aba Road, Port Harcourt", staff: 22, status: "active" },
  { id: "BR-005", name: "Ibadan Western Branch", code: "IBD-001", region: "Oyo", address: "28 Ring Road, Ibadan", staff: 18, status: "active" },
  { id: "BR-006", name: "Enugu Eastern Branch", code: "ENU-001", region: "Enugu", address: "12 Ogui Road, Enugu", staff: 15, status: "active" },
  { id: "BR-007", name: "Benin South-South Branch", code: "BEN-001", region: "Edo", address: "8 Airport Road, Benin", staff: 12, status: "active" },
  { id: "BR-008", name: "Maiduguri NE Branch", code: "MAI-001", region: "Borno", address: "5 Baga Road, Maiduguri", staff: 10, status: "active" },
];

export const seedComplianceRules = [
  { id: "CR-001", name: "KYC Level 1 — Tier 1", description: "BVN + Phone verification, max ₦300K daily", tier: 1, maxDaily: 300000, maxSingle: 50000, requiredDocs: ["BVN", "Phone"] },
  { id: "CR-002", name: "KYC Level 2 — Tier 2", description: "BVN + NIN + Address, max ₦5M daily", tier: 2, maxDaily: 5000000, maxSingle: 2000000, requiredDocs: ["BVN", "NIN", "Address Proof"] },
  { id: "CR-003", name: "KYC Level 3 — Tier 3", description: "Full verification, max ₦50M daily", tier: 3, maxDaily: 50000000, maxSingle: 50000000, requiredDocs: ["BVN", "NIN", "Address Proof", "Tax ID", "Board Resolution"] },
  { id: "CR-004", name: "AML Threshold Reporting", description: "Report transactions ≥ ₦5M to NFIU", threshold: 5000000, authority: "NFIU", frequency: "immediate" },
  { id: "CR-005", name: "CBN FX Reporting", description: "Report all FX transactions to CBN", threshold: 0, authority: "CBN", frequency: "daily" },
  { id: "CR-006", name: "Sanctions Screening", description: "Screen all cross-border against OFAC, UN, EU lists", lists: ["OFAC SDN", "UN Security Council", "EU Sanctions", "EFCC Watchlist"] },
];

export const seedUsers = [
  { id: "USR-001", name: "Adebayo Ogunlesi", email: "adebayo@bank.ng", role: "supervisor", branch: "BR-001", department: "Operations", securityLevel: 5, status: "active" },
  { id: "USR-002", name: "Ngozi Okafor", email: "ngozi@bank.ng", role: "teller", branch: "BR-001", department: "Operations", securityLevel: 3, status: "active" },
  { id: "USR-003", name: "Ibrahim Musa", email: "ibrahim@bank.ng", role: "compliance_officer", branch: "BR-002", department: "Compliance", securityLevel: 4, status: "active" },
  { id: "USR-004", name: "Amina Bello", email: "amina@bank.ng", role: "remittance_officer", branch: "BR-002", department: "Remittance", securityLevel: 4, status: "active" },
  { id: "USR-005", name: "Chinedu Eze", email: "chinedu@bank.ng", role: "treasury_officer", branch: "BR-001", department: "Treasury", securityLevel: 5, status: "active" },
  { id: "USR-006", name: "Fatima Ahmed", email: "fatima@bank.ng", role: "auditor", branch: "BR-003", department: "Audit", securityLevel: 4, status: "active" },
  { id: "USR-007", name: "Oluwaseun Adeyemi", email: "seun@bank.ng", role: "admin", branch: "BR-001", department: "IT", securityLevel: 5, status: "active" },
  { id: "USR-008", name: "Blessing Nwankwo", email: "blessing@bank.ng", role: "settlement_officer", branch: "BR-001", department: "Settlement", securityLevel: 5, status: "active" },
];

export const seedNigerianHolidays = [
  { date: "2025-01-01", name: "New Year's Day" },
  { date: "2025-03-31", name: "Eid-el-Fitr" },
  { date: "2025-04-01", name: "Eid-el-Fitr Holiday" },
  { date: "2025-04-18", name: "Good Friday" },
  { date: "2025-04-21", name: "Easter Monday" },
  { date: "2025-05-01", name: "Workers' Day" },
  { date: "2025-05-27", name: "Children's Day" },
  { date: "2025-06-07", name: "Eid-el-Kabir" },
  { date: "2025-06-08", name: "Eid-el-Kabir Holiday" },
  { date: "2025-06-12", name: "Democracy Day" },
  { date: "2025-09-06", name: "Eid-el-Maulud" },
  { date: "2025-10-01", name: "Independence Day" },
  { date: "2025-12-25", name: "Christmas Day" },
  { date: "2025-12-26", name: "Boxing Day" },
];

export const seedFeeSchedules = [
  { id: "FEE-NIP-001", product: "NIP Transfer", channel: "web", type: "flat", amount: 10, currency: "NGN", minTxn: 0, maxTxn: 5000, status: "active" },
  { id: "FEE-NIP-002", product: "NIP Transfer", channel: "web", type: "flat", amount: 25, currency: "NGN", minTxn: 5001, maxTxn: 50000, status: "active" },
  { id: "FEE-NIP-003", product: "NIP Transfer", channel: "web", type: "flat", amount: 50, currency: "NGN", minTxn: 50001, maxTxn: 999999999, status: "active" },
  { id: "FEE-NEFT-001", product: "NEFT Transfer", channel: "web", type: "flat", amount: 50, currency: "NGN", minTxn: 0, maxTxn: 999999999, status: "active" },
  { id: "FEE-RMT-001", product: "Outbound Remittance", channel: "web", type: "percentage", amount: 1.5, currency: "NGN", minTxn: 0, maxTxn: 999999999, cap: 50000, status: "active" },
  { id: "FEE-RMT-002", product: "Inbound Remittance", channel: "web", type: "flat", amount: 0, currency: "NGN", minTxn: 0, maxTxn: 999999999, status: "active" },
  { id: "FEE-CARD-001", product: "Card Processing", channel: "pos", type: "percentage", amount: 0.5, currency: "NGN", minTxn: 0, maxTxn: 999999999, cap: 2000, status: "active" },
];

export const defaultConstants = {
  API_BASE_URL: "http://localhost:3004",
  KEYCLOAK_URL: "http://keycloak:8180",
  KEYCLOAK_REALM: "payment-switch",
  KEYCLOAK_CLIENT_ID: "payment-switch-portal",
  KEYCLOAK_CLIENT_SECRET: "default-client-secret-change-in-prod",
  APISIX_URL: "http://apisix:9080",
  APISIX_ADMIN_KEY: "edd1c9f034335f136f87ad84b625c8f1",
  PERMIFY_URL: "http://permify:3476",
  PERMIFY_TENANT_ID: "t1",
  REDIS_URL: "redis://redis:6379",
  POSTGRES_URL: "postgresql://payment_user:payment_pass_2024@postgres:5432/payment_switch_portal",
  KAFKA_BROKERS: "kafka:9092",
  TEMPORAL_URL: "temporal:7233",
  TEMPORAL_NAMESPACE: "payment-switch",
  TIGERBEETLE_ADDRESSES: "tigerbeetle:3000",
  TIGERBEETLE_CLUSTER_ID: "0",
  OPENSEARCH_URL: "http://opensearch:9200",
  JAEGER_URL: "http://jaeger:16686",
  PROMETHEUS_URL: "http://prometheus:9090",
  GRAFANA_URL: "http://grafana:3002",
  MINIO_URL: "http://minio:9000",
  MINIO_ACCESS_KEY: "minioadmin",
  MINIO_SECRET_KEY: "minioadmin",
  MOJALOOP_HUB_URL: "http://mojaloop-hub:4000",
  FLUVIO_URL: "http://fluvio:9003",
  OPENAPPSEC_URL: "http://openappsec:4000",
  DAPR_URL: "http://dapr:50006",
  OLLAMA_URL: "http://localhost:11434",
  OLLAMA_MODEL: "llama3.2:1b",
  JWT_SECRET: "default-jwt-secret-32-chars-change-in-production",
  ENCRYPTION_MASTER_KEY: "default-master-key-for-dev-only-change-in-production",
  NIP_MAX_AMOUNT: 10000000,
  NEFT_BATCH_CUTOFF: "14:00",
  SETTLEMENT_TIME: "16:00",
  CBN_REPORTING_EMAIL: "returns@cbn.gov.ng",
  NFIU_REPORTING_THRESHOLD: 5000000,
  MAX_DAILY_TIER1: 300000,
  MAX_DAILY_TIER2: 5000000,
  MAX_DAILY_TIER3: 50000000,
  SALARY_DAYS: [25, 26, 27, 28, 29, 30],
  BUSINESS_HOURS_START: "06:00",
  BUSINESS_HOURS_END: "22:00",
};
