# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import account_pb2 as account__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in account_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccountServiceStub(object):
    """Account Service - High-performance gRPC service for account management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAccount = channel.unary_unary(
                '/account.AccountService/GetAccount',
                request_serializer=account__pb2.GetAccountRequest.SerializeToString,
                response_deserializer=account__pb2.GetAccountResponse.FromString,
                _registered_method=True)
        self.GetAccounts = channel.unary_unary(
                '/account.AccountService/GetAccounts',
                request_serializer=account__pb2.GetAccountsRequest.SerializeToString,
                response_deserializer=account__pb2.GetAccountsResponse.FromString,
                _registered_method=True)
        self.CreateQuote = channel.unary_unary(
                '/account.AccountService/CreateQuote',
                request_serializer=account__pb2.CreateQuoteRequest.SerializeToString,
                response_deserializer=account__pb2.CreateQuoteResponse.FromString,
                _registered_method=True)
        self.GetQuote = channel.unary_unary(
                '/account.AccountService/GetQuote',
                request_serializer=account__pb2.GetQuoteRequest.SerializeToString,
                response_deserializer=account__pb2.GetQuoteResponse.FromString,
                _registered_method=True)
        self.RecordTransaction = channel.unary_unary(
                '/account.AccountService/RecordTransaction',
                request_serializer=account__pb2.RecordTransactionRequest.SerializeToString,
                response_deserializer=account__pb2.RecordTransactionResponse.FromString,
                _registered_method=True)
        self.UpdateTransactionStatus = channel.unary_unary(
                '/account.AccountService/UpdateTransactionStatus',
                request_serializer=account__pb2.UpdateTransactionStatusRequest.SerializeToString,
                response_deserializer=account__pb2.UpdateTransactionStatusResponse.FromString,
                _registered_method=True)
        self.GetTransaction = channel.unary_unary(
                '/account.AccountService/GetTransaction',
                request_serializer=account__pb2.GetTransactionRequest.SerializeToString,
                response_deserializer=account__pb2.GetTransactionResponse.FromString,
                _registered_method=True)


class AccountServiceServicer(object):
    """Account Service - High-performance gRPC service for account management
    """

    def GetAccount(self, request, context):
        """GetAccount retrieves account information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccounts(self, request, context):
        """GetAccounts retrieves multiple accounts in a batch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateQuote(self, request, context):
        """CreateQuote creates a payment quote
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuote(self, request, context):
        """GetQuote retrieves a quote by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordTransaction(self, request, context):
        """RecordTransaction records a transaction in the database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTransactionStatus(self, request, context):
        """UpdateTransactionStatus updates the status of a transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransaction(self, request, context):
        """GetTransaction retrieves a transaction by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccount,
                    request_deserializer=account__pb2.GetAccountRequest.FromString,
                    response_serializer=account__pb2.GetAccountResponse.SerializeToString,
            ),
            'GetAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccounts,
                    request_deserializer=account__pb2.GetAccountsRequest.FromString,
                    response_serializer=account__pb2.GetAccountsResponse.SerializeToString,
            ),
            'CreateQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateQuote,
                    request_deserializer=account__pb2.CreateQuoteRequest.FromString,
                    response_serializer=account__pb2.CreateQuoteResponse.SerializeToString,
            ),
            'GetQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuote,
                    request_deserializer=account__pb2.GetQuoteRequest.FromString,
                    response_serializer=account__pb2.GetQuoteResponse.SerializeToString,
            ),
            'RecordTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordTransaction,
                    request_deserializer=account__pb2.RecordTransactionRequest.FromString,
                    response_serializer=account__pb2.RecordTransactionResponse.SerializeToString,
            ),
            'UpdateTransactionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTransactionStatus,
                    request_deserializer=account__pb2.UpdateTransactionStatusRequest.FromString,
                    response_serializer=account__pb2.UpdateTransactionStatusResponse.SerializeToString,
            ),
            'GetTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransaction,
                    request_deserializer=account__pb2.GetTransactionRequest.FromString,
                    response_serializer=account__pb2.GetTransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'account.AccountService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('account.AccountService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountService(object):
    """Account Service - High-performance gRPC service for account management
    """

    @staticmethod
    def GetAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account.AccountService/GetAccount',
            account__pb2.GetAccountRequest.SerializeToString,
            account__pb2.GetAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account.AccountService/GetAccounts',
            account__pb2.GetAccountsRequest.SerializeToString,
            account__pb2.GetAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account.AccountService/CreateQuote',
            account__pb2.CreateQuoteRequest.SerializeToString,
            account__pb2.CreateQuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account.AccountService/GetQuote',
            account__pb2.GetQuoteRequest.SerializeToString,
            account__pb2.GetQuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account.AccountService/RecordTransaction',
            account__pb2.RecordTransactionRequest.SerializeToString,
            account__pb2.RecordTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTransactionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account.AccountService/UpdateTransactionStatus',
            account__pb2.UpdateTransactionStatusRequest.SerializeToString,
            account__pb2.UpdateTransactionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/account.AccountService/GetTransaction',
            account__pb2.GetTransactionRequest.SerializeToString,
            account__pb2.GetTransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
