# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import party_pb2 as party__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in party_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PartyServiceStub(object):
    """Party Service - High-performance gRPC service for party registry operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterParty = channel.unary_unary(
                '/party.PartyService/RegisterParty',
                request_serializer=party__pb2.RegisterPartyRequest.SerializeToString,
                response_deserializer=party__pb2.RegisterPartyResponse.FromString,
                _registered_method=True)
        self.LookupParty = channel.unary_unary(
                '/party.PartyService/LookupParty',
                request_serializer=party__pb2.LookupPartyRequest.SerializeToString,
                response_deserializer=party__pb2.LookupPartyResponse.FromString,
                _registered_method=True)
        self.LookupParties = channel.unary_unary(
                '/party.PartyService/LookupParties',
                request_serializer=party__pb2.LookupPartiesRequest.SerializeToString,
                response_deserializer=party__pb2.LookupPartiesResponse.FromString,
                _registered_method=True)
        self.UpdateParty = channel.unary_unary(
                '/party.PartyService/UpdateParty',
                request_serializer=party__pb2.UpdatePartyRequest.SerializeToString,
                response_deserializer=party__pb2.UpdatePartyResponse.FromString,
                _registered_method=True)
        self.DeactivateParty = channel.unary_unary(
                '/party.PartyService/DeactivateParty',
                request_serializer=party__pb2.DeactivatePartyRequest.SerializeToString,
                response_deserializer=party__pb2.DeactivatePartyResponse.FromString,
                _registered_method=True)


class PartyServiceServicer(object):
    """Party Service - High-performance gRPC service for party registry operations
    """

    def RegisterParty(self, request, context):
        """RegisterParty registers a new party in the registry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupParty(self, request, context):
        """LookupParty looks up a party by type and identifier
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LookupParties(self, request, context):
        """LookupParties looks up multiple parties in a batch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateParty(self, request, context):
        """UpdateParty updates party information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeactivateParty(self, request, context):
        """DeactivateParty deactivates a party
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PartyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterParty': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterParty,
                    request_deserializer=party__pb2.RegisterPartyRequest.FromString,
                    response_serializer=party__pb2.RegisterPartyResponse.SerializeToString,
            ),
            'LookupParty': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupParty,
                    request_deserializer=party__pb2.LookupPartyRequest.FromString,
                    response_serializer=party__pb2.LookupPartyResponse.SerializeToString,
            ),
            'LookupParties': grpc.unary_unary_rpc_method_handler(
                    servicer.LookupParties,
                    request_deserializer=party__pb2.LookupPartiesRequest.FromString,
                    response_serializer=party__pb2.LookupPartiesResponse.SerializeToString,
            ),
            'UpdateParty': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateParty,
                    request_deserializer=party__pb2.UpdatePartyRequest.FromString,
                    response_serializer=party__pb2.UpdatePartyResponse.SerializeToString,
            ),
            'DeactivateParty': grpc.unary_unary_rpc_method_handler(
                    servicer.DeactivateParty,
                    request_deserializer=party__pb2.DeactivatePartyRequest.FromString,
                    response_serializer=party__pb2.DeactivatePartyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'party.PartyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('party.PartyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PartyService(object):
    """Party Service - High-performance gRPC service for party registry operations
    """

    @staticmethod
    def RegisterParty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/party.PartyService/RegisterParty',
            party__pb2.RegisterPartyRequest.SerializeToString,
            party__pb2.RegisterPartyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupParty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/party.PartyService/LookupParty',
            party__pb2.LookupPartyRequest.SerializeToString,
            party__pb2.LookupPartyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LookupParties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/party.PartyService/LookupParties',
            party__pb2.LookupPartiesRequest.SerializeToString,
            party__pb2.LookupPartiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateParty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/party.PartyService/UpdateParty',
            party__pb2.UpdatePartyRequest.SerializeToString,
            party__pb2.UpdatePartyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeactivateParty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/party.PartyService/DeactivateParty',
            party__pb2.DeactivatePartyRequest.SerializeToString,
            party__pb2.DeactivatePartyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
