// Package export provides transaction and data export functionality
// Recommendation #16: Transaction Export (CSV, Excel, PDF)
package export

import (
	"bytes"
	"context"
	"encoding/csv"
	"encoding/json"
	"fmt"
	"io"
	"strconv"
	"time"
)

// ExportFormat represents the output format for exports
type ExportFormat string

const (
	FormatCSV   ExportFormat = "csv"
	FormatJSON  ExportFormat = "json"
	FormatExcel ExportFormat = "xlsx"
	FormatPDF   ExportFormat = "pdf"
)

// ExportOptions holds options for data export
type ExportOptions struct {
	Format         ExportFormat
	Columns        []string
	DateFrom       *time.Time
	DateTo         *time.Time
	Filters        map[string]interface{}
	SortBy         string
	SortOrder      string
	Limit          int
	IncludeHeaders bool
}

// DefaultExportOptions returns default export options
func DefaultExportOptions() *ExportOptions {
	return &ExportOptions{
		Format:         FormatCSV,
		IncludeHeaders: true,
		Limit:          10000,
		SortOrder:      "desc",
	}
}

// Transaction represents a transaction for export
type Transaction struct {
	ID            string                 `json:"id" csv:"Transaction ID"`
	Reference     string                 `json:"reference" csv:"Reference"`
	Type          string                 `json:"type" csv:"Type"`
	Status        string                 `json:"status" csv:"Status"`
	Amount        float64                `json:"amount" csv:"Amount"`
	Currency      string                 `json:"currency" csv:"Currency"`
	Fee           float64                `json:"fee" csv:"Fee"`
	NetAmount     float64                `json:"net_amount" csv:"Net Amount"`
	SenderID      string                 `json:"sender_id" csv:"Sender ID"`
	SenderName    string                 `json:"sender_name" csv:"Sender Name"`
	RecipientID   string                 `json:"recipient_id" csv:"Recipient ID"`
	RecipientName string                 `json:"recipient_name" csv:"Recipient Name"`
	PaymentMethod string                 `json:"payment_method" csv:"Payment Method"`
	Description   string                 `json:"description" csv:"Description"`
	CreatedAt     time.Time              `json:"created_at" csv:"Created At"`
	CompletedAt   *time.Time             `json:"completed_at,omitempty" csv:"Completed At"`
	FailureReason string                 `json:"failure_reason,omitempty" csv:"Failure Reason"`
	Metadata      map[string]interface{} `json:"metadata,omitempty" csv:"-"`
}

// Participant represents a participant for export
type Participant struct {
	ID              string    `json:"id" csv:"Participant ID"`
	Name            string    `json:"name" csv:"Name"`
	Type            string    `json:"type" csv:"Type"`
	Status          string    `json:"status" csv:"Status"`
	Country         string    `json:"country" csv:"Country"`
	Currency        string    `json:"currency" csv:"Currency"`
	KYBStatus       string    `json:"kyb_status" csv:"KYB Status"`
	ProvisionStatus string    `json:"provision_status" csv:"Provision Status"`
	CreatedAt       time.Time `json:"created_at" csv:"Created At"`
	UpdatedAt       time.Time `json:"updated_at" csv:"Updated At"`
}

// ComplianceReport represents a compliance report for export
type ComplianceReport struct {
	ID                string    `json:"id" csv:"Report ID"`
	Type              string    `json:"type" csv:"Report Type"`
	Period            string    `json:"period" csv:"Period"`
	Status            string    `json:"status" csv:"Status"`
	TotalTransactions int64     `json:"total_transactions" csv:"Total Transactions"`
	TotalAmount       float64   `json:"total_amount" csv:"Total Amount"`
	FlaggedCount      int64     `json:"flagged_count" csv:"Flagged Count"`
	SARCount          int64     `json:"sar_count" csv:"SAR Count"`
	CTRCount          int64     `json:"ctr_count" csv:"CTR Count"`
	GeneratedAt       time.Time `json:"generated_at" csv:"Generated At"`
	GeneratedBy       string    `json:"generated_by" csv:"Generated By"`
}

// Exporter handles data export operations
type Exporter struct {
	maxRows int
}

// NewExporter creates a new exporter
func NewExporter(maxRows int) *Exporter {
	if maxRows <= 0 {
		maxRows = 100000
	}
	return &Exporter{maxRows: maxRows}
}

// ExportTransactions exports transactions to the specified format
func (e *Exporter) ExportTransactions(ctx context.Context, transactions []Transaction, opts *ExportOptions) ([]byte, error) {
	if opts == nil {
		opts = DefaultExportOptions()
	}

	if len(transactions) > e.maxRows {
		return nil, fmt.Errorf("export limit exceeded: %d rows (max %d)", len(transactions), e.maxRows)
	}

	switch opts.Format {
	case FormatCSV:
		return e.transactionsToCSV(transactions, opts)
	case FormatJSON:
		return e.transactionsToJSON(transactions)
	default:
		return nil, fmt.Errorf("unsupported format: %s", opts.Format)
	}
}

func (e *Exporter) transactionsToCSV(transactions []Transaction, opts *ExportOptions) ([]byte, error) {
	var buf bytes.Buffer
	writer := csv.NewWriter(&buf)

	// Default columns if not specified
	columns := opts.Columns
	if len(columns) == 0 {
		columns = []string{
			"Transaction ID", "Reference", "Type", "Status", "Amount", "Currency",
			"Fee", "Net Amount", "Sender Name", "Recipient Name", "Payment Method",
			"Description", "Created At", "Completed At",
		}
	}

	// Write headers
	if opts.IncludeHeaders {
		if err := writer.Write(columns); err != nil {
			return nil, fmt.Errorf("failed to write headers: %w", err)
		}
	}

	// Write data rows
	for _, tx := range transactions {
		row := make([]string, len(columns))
		for i, col := range columns {
			row[i] = getTransactionField(tx, col)
		}
		if err := writer.Write(row); err != nil {
			return nil, fmt.Errorf("failed to write row: %w", err)
		}
	}

	writer.Flush()
	if err := writer.Error(); err != nil {
		return nil, fmt.Errorf("CSV writer error: %w", err)
	}

	return buf.Bytes(), nil
}

func (e *Exporter) transactionsToJSON(transactions []Transaction) ([]byte, error) {
	return json.MarshalIndent(transactions, "", "  ")
}

func getTransactionField(tx Transaction, field string) string {
	switch field {
	case "Transaction ID":
		return tx.ID
	case "Reference":
		return tx.Reference
	case "Type":
		return tx.Type
	case "Status":
		return tx.Status
	case "Amount":
		return strconv.FormatFloat(tx.Amount, 'f', 2, 64)
	case "Currency":
		return tx.Currency
	case "Fee":
		return strconv.FormatFloat(tx.Fee, 'f', 2, 64)
	case "Net Amount":
		return strconv.FormatFloat(tx.NetAmount, 'f', 2, 64)
	case "Sender ID":
		return tx.SenderID
	case "Sender Name":
		return tx.SenderName
	case "Recipient ID":
		return tx.RecipientID
	case "Recipient Name":
		return tx.RecipientName
	case "Payment Method":
		return tx.PaymentMethod
	case "Description":
		return tx.Description
	case "Created At":
		return tx.CreatedAt.Format(time.RFC3339)
	case "Completed At":
		if tx.CompletedAt != nil {
			return tx.CompletedAt.Format(time.RFC3339)
		}
		return ""
	case "Failure Reason":
		return tx.FailureReason
	default:
		return ""
	}
}

// ExportParticipants exports participants to the specified format
func (e *Exporter) ExportParticipants(ctx context.Context, participants []Participant, opts *ExportOptions) ([]byte, error) {
	if opts == nil {
		opts = DefaultExportOptions()
	}

	if len(participants) > e.maxRows {
		return nil, fmt.Errorf("export limit exceeded: %d rows (max %d)", len(participants), e.maxRows)
	}

	switch opts.Format {
	case FormatCSV:
		return e.participantsToCSV(participants, opts)
	case FormatJSON:
		return json.MarshalIndent(participants, "", "  ")
	default:
		return nil, fmt.Errorf("unsupported format: %s", opts.Format)
	}
}

func (e *Exporter) participantsToCSV(participants []Participant, opts *ExportOptions) ([]byte, error) {
	var buf bytes.Buffer
	writer := csv.NewWriter(&buf)

	columns := []string{
		"Participant ID", "Name", "Type", "Status", "Country", "Currency",
		"KYB Status", "Provision Status", "Created At", "Updated At",
	}

	if opts.IncludeHeaders {
		if err := writer.Write(columns); err != nil {
			return nil, fmt.Errorf("failed to write headers: %w", err)
		}
	}

	for _, p := range participants {
		row := []string{
			p.ID, p.Name, p.Type, p.Status, p.Country, p.Currency,
			p.KYBStatus, p.ProvisionStatus,
			p.CreatedAt.Format(time.RFC3339),
			p.UpdatedAt.Format(time.RFC3339),
		}
		if err := writer.Write(row); err != nil {
			return nil, fmt.Errorf("failed to write row: %w", err)
		}
	}

	writer.Flush()
	return buf.Bytes(), writer.Error()
}

// ExportComplianceReports exports compliance reports
func (e *Exporter) ExportComplianceReports(ctx context.Context, reports []ComplianceReport, opts *ExportOptions) ([]byte, error) {
	if opts == nil {
		opts = DefaultExportOptions()
	}

	switch opts.Format {
	case FormatCSV:
		return e.complianceReportsToCSV(reports, opts)
	case FormatJSON:
		return json.MarshalIndent(reports, "", "  ")
	default:
		return nil, fmt.Errorf("unsupported format: %s", opts.Format)
	}
}

func (e *Exporter) complianceReportsToCSV(reports []ComplianceReport, opts *ExportOptions) ([]byte, error) {
	var buf bytes.Buffer
	writer := csv.NewWriter(&buf)

	columns := []string{
		"Report ID", "Report Type", "Period", "Status",
		"Total Transactions", "Total Amount", "Flagged Count",
		"SAR Count", "CTR Count", "Generated At", "Generated By",
	}

	if opts.IncludeHeaders {
		if err := writer.Write(columns); err != nil {
			return nil, fmt.Errorf("failed to write headers: %w", err)
		}
	}

	for _, r := range reports {
		row := []string{
			r.ID, r.Type, r.Period, r.Status,
			strconv.FormatInt(r.TotalTransactions, 10),
			strconv.FormatFloat(r.TotalAmount, 'f', 2, 64),
			strconv.FormatInt(r.FlaggedCount, 10),
			strconv.FormatInt(r.SARCount, 10),
			strconv.FormatInt(r.CTRCount, 10),
			r.GeneratedAt.Format(time.RFC3339),
			r.GeneratedBy,
		}
		if err := writer.Write(row); err != nil {
			return nil, fmt.Errorf("failed to write row: %w", err)
		}
	}

	writer.Flush()
	return buf.Bytes(), writer.Error()
}

// StreamExporter handles streaming exports for large datasets
type StreamExporter struct {
	writer    io.Writer
	format    ExportFormat
	csvWriter *csv.Writer
	rowCount  int
	maxRows   int
}

// NewStreamExporter creates a new streaming exporter
func NewStreamExporter(w io.Writer, format ExportFormat, maxRows int) *StreamExporter {
	se := &StreamExporter{
		writer:  w,
		format:  format,
		maxRows: maxRows,
	}
	if format == FormatCSV {
		se.csvWriter = csv.NewWriter(w)
	}
	return se
}

// WriteHeader writes the header row for CSV exports
func (se *StreamExporter) WriteHeader(columns []string) error {
	if se.format != FormatCSV {
		return nil
	}
	return se.csvWriter.Write(columns)
}

// WriteTransaction writes a single transaction to the stream
func (se *StreamExporter) WriteTransaction(tx Transaction) error {
	if se.rowCount >= se.maxRows {
		return fmt.Errorf("export limit exceeded: %d rows", se.maxRows)
	}

	switch se.format {
	case FormatCSV:
		row := []string{
			tx.ID, tx.Reference, tx.Type, tx.Status,
			strconv.FormatFloat(tx.Amount, 'f', 2, 64),
			tx.Currency,
			strconv.FormatFloat(tx.Fee, 'f', 2, 64),
			strconv.FormatFloat(tx.NetAmount, 'f', 2, 64),
			tx.SenderName, tx.RecipientName, tx.PaymentMethod,
			tx.Description, tx.CreatedAt.Format(time.RFC3339),
		}
		if err := se.csvWriter.Write(row); err != nil {
			return err
		}
	case FormatJSON:
		data, err := json.Marshal(tx)
		if err != nil {
			return err
		}
		if se.rowCount > 0 {
			se.writer.Write([]byte(",\n"))
		}
		se.writer.Write(data)
	}

	se.rowCount++
	return nil
}

// Flush flushes any buffered data
func (se *StreamExporter) Flush() error {
	if se.csvWriter != nil {
		se.csvWriter.Flush()
		return se.csvWriter.Error()
	}
	return nil
}

// RowCount returns the number of rows written
func (se *StreamExporter) RowCount() int {
	return se.rowCount
}

// ExportJob represents an async export job
type ExportJob struct {
	ID          string                 `json:"id"`
	Type        string                 `json:"type"`
	Format      ExportFormat           `json:"format"`
	Status      string                 `json:"status"`
	Progress    int                    `json:"progress"`
	TotalRows   int                    `json:"total_rows"`
	Filters     map[string]interface{} `json:"filters"`
	CreatedAt   time.Time              `json:"created_at"`
	CompletedAt *time.Time             `json:"completed_at,omitempty"`
	DownloadURL string                 `json:"download_url,omitempty"`
	Error       string                 `json:"error,omitempty"`
	ExpiresAt   *time.Time             `json:"expires_at,omitempty"`
}

// ExportJobStatus represents the status of an export job
const (
	ExportJobStatusPending    = "pending"
	ExportJobStatusProcessing = "processing"
	ExportJobStatusCompleted  = "completed"
	ExportJobStatusFailed     = "failed"
	ExportJobStatusExpired    = "expired"
)
