apiVersion: v1
kind: Secret
metadata:
  name: {{ include "remittance-platform.fullname" . }}-secrets
  labels:
    {{- include "remittance-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  redis-url: {{ .Values.secrets.redisUrl | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
