const now = new Date();
const oneMonthAgo = new Date(now.getFullYear(), now.getMonth() - 1, now.getDate());
const twoMonthsAgo = new Date(now.getFullYear(), now.getMonth() - 2, now.getDate());

export const DEMO = {
  dashboardMetrics: {
    total_applications: 1247,
    pending_applications: 23,
    approved_applications: 1089,
    rejected_applications: 135,
    approval_rate: 87.3,
    avg_processing_time_hours: 4.2,
    total_disbursed: 285000000,
    disbursement_count: 1089,
    avg_loan_amount: 261700,
    pending_disbursements: 12,
    total_repaid: 198000000,
    repayment_count: 3450,
    on_time_repayment_rate: 94.2,
    outstanding_balance: 87000000,
    default_count: 18,
    default_rate: 1.65,
    total_default_amount: 4700000,
    recovery_rate: 42.5,
    tier1_users: 450,
    tier2_users: 380,
    tier3_users: 210,
    tier4_users: 85,
    tier5_users: 22,
    graduation_count: 156,
    avg_credit_score_improvement: 45,
    active_users: 892,
    new_users_today: 14,
    avg_loans_per_user: 2.3,
    total_revenue: 42000000,
    total_interest_earned: 38500000,
    net_profit_margin: 23.4,
    as_of: now.toISOString(),
  },

  linkedAccounts: [
    {
      id: 'acc-1',
      bankName: 'GTBank',
      accountNumber: '0123456789',
      accountName: 'Adebayo Ogunlesi',
      balance: '2450000',
      status: 'active',
      lastSyncedAt: new Date(now.getTime() - 3600000).toISOString(),
      createdAt: twoMonthsAgo.toISOString(),
    },
    {
      id: 'acc-2',
      bankName: 'Access Bank',
      accountNumber: '9876543210',
      accountName: 'Adebayo Ogunlesi',
      balance: '1875000',
      status: 'active',
      lastSyncedAt: new Date(now.getTime() - 7200000).toISOString(),
      createdAt: twoMonthsAgo.toISOString(),
    },
    {
      id: 'acc-3',
      bankName: 'Zenith Bank',
      accountNumber: '5678901234',
      accountName: 'Adebayo Ogunlesi (Savings)',
      balance: '5200000',
      status: 'active',
      lastSyncedAt: new Date(now.getTime() - 1800000).toISOString(),
      createdAt: oneMonthAgo.toISOString(),
    },
  ],

  transactions: [
    { id: 'tx-1', description: 'Shoprite Groceries', amount: -45000, category: 'food', date: new Date(now.getTime() - 86400000).toISOString(), accountId: 'acc-1' },
    { id: 'tx-2', description: 'Salary Credit', amount: 850000, category: 'income', date: new Date(now.getTime() - 172800000).toISOString(), accountId: 'acc-1' },
    { id: 'tx-3', description: 'Uber Ride', amount: -3500, category: 'transport', date: new Date(now.getTime() - 259200000).toISOString(), accountId: 'acc-1' },
    { id: 'tx-4', description: 'Netflix Subscription', amount: -4900, category: 'entertainment', date: new Date(now.getTime() - 345600000).toISOString(), accountId: 'acc-2' },
    { id: 'tx-5', description: 'Electricity Bill - EKEDC', amount: -18500, category: 'bills', date: new Date(now.getTime() - 432000000).toISOString(), accountId: 'acc-1' },
    { id: 'tx-6', description: 'Transfer to Savings', amount: -200000, category: 'savings', date: new Date(now.getTime() - 518400000).toISOString(), accountId: 'acc-1' },
    { id: 'tx-7', description: 'POS - Chicken Republic', amount: -5200, category: 'food', date: new Date(now.getTime() - 604800000).toISOString(), accountId: 'acc-2' },
    { id: 'tx-8', description: 'Freelance Payment', amount: 350000, category: 'income', date: new Date(now.getTime() - 691200000).toISOString(), accountId: 'acc-2' },
  ],

  creditScore: {
    score: 725,
    rating: 'Good',
    lastUpdated: now.toISOString(),
    factors: {
      paymentHistory: 82,
      creditUtilization: 65,
      creditAge: 72,
      creditMix: 58,
      newCredit: 78,
    },
    recommendations: [
      'Keep your credit utilization below 30% for optimal score improvement',
      'Continue making on-time payments to maintain your strong payment history',
      'Consider diversifying your credit mix with a small installment loan',
      'Avoid opening multiple new credit accounts in a short period',
    ],
  },

  creditScoreHistory: [
    { month: '2025-03', score: 680 },
    { month: '2025-04', score: 685 },
    { month: '2025-05', score: 692 },
    { month: '2025-06', score: 698 },
    { month: '2025-07', score: 705 },
    { month: '2025-08', score: 710 },
    { month: '2025-09', score: 708 },
    { month: '2025-10', score: 715 },
    { month: '2025-11', score: 718 },
    { month: '2025-12', score: 720 },
    { month: '2026-01', score: 722 },
    { month: '2026-02', score: 725 },
  ],

  creditFactors: [
    { factor: 'Payment History', impact: 'positive', score: 82, weight: 35 },
    { factor: 'Credit Utilization', impact: 'neutral', score: 65, weight: 30 },
    { factor: 'Credit Age', impact: 'positive', score: 72, weight: 15 },
    { factor: 'Credit Mix', impact: 'neutral', score: 58, weight: 10 },
    { factor: 'New Credit', impact: 'positive', score: 78, weight: 10 },
  ],

  apiKeys: [
    {
      id: 'key-1',
      name: 'Production App',
      key: 'pk_live_a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6',
      environment: 'production' as const,
      status: 'active' as const,
      createdAt: new Date(twoMonthsAgo),
      lastUsedAt: new Date(now.getTime() - 3600000),
      requestCount: 45230,
    },
    {
      id: 'key-2',
      name: 'Development',
      key: 'pk_test_z9y8x7w6v5u4t3s2r1q0p9o8n7m6l5k4',
      environment: 'development' as const,
      status: 'active' as const,
      createdAt: new Date(oneMonthAgo),
      lastUsedAt: new Date(now.getTime() - 86400000),
      requestCount: 12450,
    },
  ],

  budgets: [
    { id: 'bud-1', category: 'food', monthlyLimit: '80000', createdAt: oneMonthAgo.toISOString() },
    { id: 'bud-2', category: 'transport', monthlyLimit: '35000', createdAt: oneMonthAgo.toISOString() },
    { id: 'bud-3', category: 'entertainment', monthlyLimit: '25000', createdAt: oneMonthAgo.toISOString() },
    { id: 'bud-4', category: 'shopping', monthlyLimit: '50000', createdAt: oneMonthAgo.toISOString() },
    { id: 'bud-5', category: 'bills', monthlyLimit: '45000', createdAt: oneMonthAgo.toISOString() },
  ],

  budgetStatus: [
    { budgetId: 'bud-1', amountSpent: 62000, percentageUsed: 77.5, isOverBudget: false, isNearLimit: false },
    { budgetId: 'bud-2', amountSpent: 28500, percentageUsed: 81.4, isOverBudget: false, isNearLimit: true },
    { budgetId: 'bud-3', amountSpent: 27800, percentageUsed: 111.2, isOverBudget: true, isNearLimit: false },
    { budgetId: 'bud-4', amountSpent: 31200, percentageUsed: 62.4, isOverBudget: false, isNearLimit: false },
    { budgetId: 'bud-5', amountSpent: 38900, percentageUsed: 86.4, isOverBudget: false, isNearLimit: true },
  ],

  categoryBreakdown: {
    totalSpent: 188400,
    totalTransactions: 47,
    breakdown: [
      { category: 'food', amount: 62000, percentage: 32.9, count: 15 },
      { category: 'bills', amount: 38900, percentage: 20.6, count: 5 },
      { category: 'shopping', amount: 31200, percentage: 16.6, count: 8 },
      { category: 'transport', amount: 28500, percentage: 15.1, count: 12 },
      { category: 'entertainment', amount: 27800, percentage: 14.8, count: 7 },
    ],
  },

  budgetComparison: [
    { category: 'food', budgetAmount: 80000, actualSpent: 62000, percentageUsed: 77.5, difference: 18000, isOverBudget: false },
    { category: 'transport', budgetAmount: 35000, actualSpent: 28500, percentageUsed: 81.4, difference: 6500, isOverBudget: false },
    { category: 'entertainment', budgetAmount: 25000, actualSpent: 27800, percentageUsed: 111.2, difference: -2800, isOverBudget: true },
    { category: 'shopping', budgetAmount: 50000, actualSpent: 31200, percentageUsed: 62.4, difference: 18800, isOverBudget: false },
    { category: 'bills', budgetAmount: 45000, actualSpent: 38900, percentageUsed: 86.4, difference: 6100, isOverBudget: false },
  ],

  monthlyTrends: [
    { month: '2025-09', label: 'Sep 2025', totalSpent: 165000 },
    { month: '2025-10', label: 'Oct 2025', totalSpent: 178000 },
    { month: '2025-11', label: 'Nov 2025', totalSpent: 195000 },
    { month: '2025-12', label: 'Dec 2025', totalSpent: 245000 },
    { month: '2026-01', label: 'Jan 2026', totalSpent: 210000 },
    { month: '2026-02', label: 'Feb 2026', totalSpent: 188400 },
  ],

  overspendingPatterns: [
    { category: 'entertainment', overspendRate: 45, overspendCount: 3, totalMonths: 6, totalSpent: '167000', budgetAmount: '150000', overPercentage: '11.3' },
    { category: 'food', overspendRate: 25, overspendCount: 2, totalMonths: 6, totalSpent: '490000', budgetAmount: '480000', overPercentage: '2.1' },
  ],

  budgetRecommendations: {
    income: {
      averageMonthlyIncome: 1200000,
      incomeStability: 'stable' as const,
      confidence: 0.92,
    },
    summary: {
      totalPotentialSavings: 85000,
      highPriorityCount: 2,
    },
    recommendations: [
      {
        category: 'entertainment',
        priority: 'high',
        reasoning: 'You consistently overspend on entertainment. Consider setting a stricter limit or finding free alternatives.',
        currentSpending: 27800,
        recommendedBudget: 20000,
        potentialSavings: 7800,
      },
      {
        category: 'food',
        priority: 'medium',
        reasoning: 'Your food spending is within budget but could be optimized with meal planning and bulk buying.',
        currentSpending: 62000,
        recommendedBudget: 55000,
        potentialSavings: 7000,
      },
      {
        category: 'savings',
        priority: 'high',
        reasoning: 'Based on your income, you should aim to save at least 20% monthly.',
        currentSpending: 200000,
        recommendedBudget: 240000,
        potentialSavings: 0,
      },
    ],
  },

  budgetInsights: {
    insights: [
      { type: 'warning', title: 'Entertainment Overspending', message: 'You exceeded your entertainment budget by 11.2% this month. Consider cutting back on subscriptions.' },
      { type: 'success', title: 'Transport Savings', message: 'Great job! Your transport spending is 18.6% below budget this month.' },
      { type: 'info', title: 'December Spike', message: 'Your spending typically increases by 25% in December. Plan ahead for holiday expenses.' },
    ],
  },

  spendingAlerts: [
    {
      id: 'alert-1',
      alertType: 'large_transaction',
      severity: 'high',
      title: 'Large Transaction Detected',
      message: 'A transaction of ₦200,000 was made at Electronics Hub. This is above your usual spending pattern.',
      createdAt: new Date(now.getTime() - 7200000).toISOString(),
      isRead: false,
      isDismissed: false,
      actionUrl: null,
    },
    {
      id: 'alert-2',
      alertType: 'spending_spike',
      severity: 'medium',
      title: 'Spending Spike in Entertainment',
      message: 'Your entertainment spending this week is 45% higher than your weekly average.',
      createdAt: new Date(now.getTime() - 86400000).toISOString(),
      isRead: false,
      isDismissed: false,
      actionUrl: null,
    },
    {
      id: 'alert-3',
      alertType: 'duplicate_charge',
      severity: 'high',
      title: 'Possible Duplicate Charge',
      message: 'Two identical charges of ₦4,900 from Netflix were detected within 24 hours.',
      createdAt: new Date(now.getTime() - 172800000).toISOString(),
      isRead: false,
      isDismissed: false,
      actionUrl: null,
    },
  ],

  spendingAlertSettings: {
    pushNotificationsEnabled: true,
    duplicateChargeEnabled: true,
    largeTransactionEnabled: true,
    largeTransactionThreshold: '50000',
    merchantChangeEnabled: true,
    unusualCategoryEnabled: false,
    spendingSpikeEnabled: true,
  },

  expenseCategories: {
    categories: [
      { id: 'cat-1', name: 'Food & Dining', icon: 'fork.knife', color: '#FF6B6B', isDefault: true, stats: { transactionCount: 15, totalAmount: 6200000 } },
      { id: 'cat-2', name: 'Transport', icon: 'car.fill', color: '#4ECDC4', isDefault: true, stats: { transactionCount: 12, totalAmount: 2850000 } },
      { id: 'cat-3', name: 'Shopping', icon: 'cart.fill', color: '#FFE66D', isDefault: true, stats: { transactionCount: 8, totalAmount: 3120000 } },
      { id: 'cat-4', name: 'Bills & Utilities', icon: 'bolt.fill', color: '#95E1D3', isDefault: true, stats: { transactionCount: 5, totalAmount: 3890000 } },
      { id: 'cat-5', name: 'Entertainment', icon: 'star.fill', color: '#C7CEEA', isDefault: true, stats: { transactionCount: 7, totalAmount: 2780000 } },
      { id: 'cat-6', name: 'Healthcare', icon: 'heart.fill', color: '#FF8B94', isDefault: true, stats: { transactionCount: 2, totalAmount: 850000 } },
      { id: 'cat-7', name: 'Subscriptions', icon: 'tv.fill', color: '#AA96DA', isDefault: false, stats: { transactionCount: 4, totalAmount: 1960000 } },
      { id: 'cat-8', name: 'Gym & Fitness', icon: 'person.fill', color: '#6BCB77', isDefault: false, stats: { transactionCount: 1, totalAmount: 2500000 } },
    ],
  },

  billReminders: {
    reminders: [
      { id: 'bill-1', merchantName: 'EKEDC Electricity', amount: 1850000, frequency: 'monthly' as const, dueDay: 15, nextDueDate: new Date(now.getFullYear(), now.getMonth(), 15).toISOString(), autoPayEnabled: true, reminderDaysBefore: 3, isAmountVariable: true, overdueCount: 0 },
      { id: 'bill-2', merchantName: 'Netflix', amount: 490000, frequency: 'monthly' as const, dueDay: 5, nextDueDate: new Date(now.getFullYear(), now.getMonth() + 1, 5).toISOString(), autoPayEnabled: true, reminderDaysBefore: 2, isAmountVariable: false, overdueCount: 0 },
      { id: 'bill-3', merchantName: 'DSTV Premium', amount: 2100000, frequency: 'monthly' as const, dueDay: 20, nextDueDate: new Date(now.getFullYear(), now.getMonth(), 20).toISOString(), autoPayEnabled: false, reminderDaysBefore: 5, isAmountVariable: false, overdueCount: 0 },
      { id: 'bill-4', merchantName: 'MTN Data Plan', amount: 500000, frequency: 'monthly' as const, dueDay: 1, nextDueDate: new Date(now.getFullYear(), now.getMonth() + 1, 1).toISOString(), autoPayEnabled: true, reminderDaysBefore: 2, isAmountVariable: false, overdueCount: 0 },
    ],
    upcomingCount: 3,
    autoPayCount: 3,
  },

  upcomingBills: {
    totalAmount: 4940000,
    bills: [],
  },

  overdueBills: {
    overdueBills: [],
  },

  savingsGoals: [
    {
      id: 'goal-1',
      name: 'Emergency Fund',
      targetAmount: '1000000',
      currentAmount: '650000',
      targetDate: new Date(now.getFullYear(), now.getMonth() + 4, 1),
      category: 'emergency',
      icon: '🚨',
      progress: 65,
      remaining: 350000,
      daysRemaining: 120,
      isActive: true,
      isCompleted: false,
      completedAt: null,
    },
    {
      id: 'goal-2',
      name: 'Vacation to Zanzibar',
      targetAmount: '500000',
      currentAmount: '280000',
      targetDate: new Date(now.getFullYear(), now.getMonth() + 6, 15),
      category: 'vacation',
      icon: '✈️',
      progress: 56,
      remaining: 220000,
      daysRemaining: 195,
      isActive: true,
      isCompleted: false,
      completedAt: null,
    },
    {
      id: 'goal-3',
      name: 'New Laptop',
      targetAmount: '350000',
      currentAmount: '350000',
      targetDate: new Date(now.getFullYear(), now.getMonth() - 1, 1),
      category: 'other',
      icon: '💰',
      progress: 100,
      remaining: 0,
      daysRemaining: 0,
      isActive: false,
      isCompleted: true,
      completedAt: new Date(now.getFullYear(), now.getMonth() - 1, 15),
    },
  ],

  recurringContributions: [
    {
      id: 'rec-1',
      goalId: 'goal-1',
      amount: '50000',
      frequency: 'monthly',
      dayOfMonth: 1,
      isActive: true,
      nextProcessDate: new Date(now.getFullYear(), now.getMonth() + 1, 1).toISOString(),
    },
  ],

  goalTemplates: [
    { id: 'tpl-1', name: 'Emergency Fund', category: 'emergency', description: 'Build 3-6 months of living expenses', suggestedAmount: 1500000, suggestedMonths: 12, icon: '🚨', popularity: 95 },
    { id: 'tpl-2', name: 'Vacation Fund', category: 'vacation', description: 'Save for your dream vacation', suggestedAmount: 500000, suggestedMonths: 6, icon: '✈️', popularity: 82 },
    { id: 'tpl-3', name: 'Home Down Payment', category: 'home', description: 'Save for your first home', suggestedAmount: 5000000, suggestedMonths: 24, icon: '🏠', popularity: 78 },
    { id: 'tpl-4', name: 'Education Fund', category: 'education', description: 'Invest in your education', suggestedAmount: 2000000, suggestedMonths: 18, icon: '🎓', popularity: 71 },
    { id: 'tpl-5', name: 'Car Fund', category: 'car', description: 'Save for a new vehicle', suggestedAmount: 3000000, suggestedMonths: 18, icon: '🚗', popularity: 65 },
  ],

  bnplApplications: [
    {
      id: 'bnpl-1',
      studentName: 'Chidi Okonkwo',
      schoolName: 'Lagos International School',
      grade: 'SS2',
      schoolFeesAmount: '450000',
      installmentPlan: 6,
      status: 'approved' as const,
      monthlyPayment: '82500',
      totalAmount: '495000',
      createdAt: new Date(oneMonthAgo),
      updatedAt: new Date(now.getTime() - 86400000),
    },
    {
      id: 'bnpl-2',
      studentName: 'Amara Okonkwo',
      schoolName: 'British International School',
      grade: 'JS1',
      schoolFeesAmount: '680000',
      installmentPlan: 9,
      status: 'pending' as const,
      monthlyPayment: '83111',
      totalAmount: '748000',
      createdAt: new Date(now.getTime() - 172800000),
      updatedAt: new Date(now.getTime() - 172800000),
    },
  ],

  savingsChallenges: [
    {
      id: 'ch-1',
      challengeType: '52-week',
      status: 'ACTIVE',
      currentAmount: '276',
      targetAmount: '1378',
      weekNumber: 23,
      consecutiveDays: undefined,
      startDate: new Date(now.getFullYear(), 0, 1).toISOString(),
    },
    {
      id: 'ch-2',
      challengeType: 'round-up',
      status: 'ACTIVE',
      currentAmount: '45.80',
      targetAmount: '500',
      weekNumber: undefined,
      consecutiveDays: undefined,
      startDate: new Date(now.getFullYear(), now.getMonth() - 1, 1).toISOString(),
    },
  ],

  leaderboard: [
    { userId: 'user-abc123', rank: 1, totalSaved: '1250.00' },
    { userId: 'user-def456', rank: 2, totalSaved: '980.50' },
    { userId: 'user-ghi789', rank: 3, totalSaved: '875.25' },
    { userId: 'user-jkl012', rank: 4, totalSaved: '650.00' },
    { userId: 'user-mno345', rank: 5, totalSaved: '520.75' },
  ],

  achievements: [
    { id: 'ach-1', title: 'First Steps', description: 'Started your first savings challenge', icon: '🎯', earnedAt: oneMonthAgo.toISOString() },
    { id: 'ach-2', title: 'Consistency King', description: 'Completed 10 consecutive weekly savings', icon: '👑', earnedAt: new Date(now.getTime() - 604800000).toISOString() },
    { id: 'ach-3', title: 'Quarter Master', description: 'Reached 25% of your 52-week challenge goal', icon: '🏆', earnedAt: new Date(now.getTime() - 259200000).toISOString() },
  ],

  financialHealth: {
    score: {
      overallScore: 72,
      creditScoreComponent: 78,
      savingsRateComponent: 65,
      debtToIncomeComponent: 80,
      budgetAdherenceComponent: 62,
      creditScore: 725,
      savingsRate: '18.5',
      debtToIncomeRatio: '22.3',
      budgetAdherence: '78',
      monthlyIncome: '1200000',
      monthlyExpenses: '780000',
      monthlyDebtPayments: '120000',
      monthlySavings: '300000',
      calculatedAt: now.toISOString(),
    },
    recommendations: [
      {
        id: 'rec-1',
        title: 'Increase Savings Rate',
        description: 'Your savings rate of 18.5% is below the recommended 20%. Try to save an additional ₦18,000 per month.',
        priority: 1,
        potentialScoreIncrease: 5,
        actionItems: ['Set up automatic transfers on payday', 'Cut one non-essential subscription', 'Use the 50/30/20 rule'],
      },
      {
        id: 'rec-2',
        title: 'Improve Budget Adherence',
        description: 'You went over budget in 2 categories this month. Tighter tracking can improve your score.',
        priority: 2,
        potentialScoreIncrease: 4,
        actionItems: ['Review spending weekly instead of monthly', 'Set up category-specific alerts', 'Use cash envelopes for discretionary spending'],
      },
      {
        id: 'rec-3',
        title: 'Maintain Payment History',
        description: 'Your payment history is strong. Keep making on-time payments to maintain this score component.',
        priority: 3,
        potentialScoreIncrease: 2,
        actionItems: ['Enable auto-pay for all recurring bills', 'Set reminders 3 days before due dates'],
      },
    ],
  },

  financialHealthHistory: [
    { overallScore: 62, scoreMonth: 'Mar' },
    { overallScore: 64, scoreMonth: 'Apr' },
    { overallScore: 65, scoreMonth: 'May' },
    { overallScore: 63, scoreMonth: 'Jun' },
    { overallScore: 67, scoreMonth: 'Jul' },
    { overallScore: 68, scoreMonth: 'Aug' },
    { overallScore: 66, scoreMonth: 'Sep' },
    { overallScore: 69, scoreMonth: 'Oct' },
    { overallScore: 70, scoreMonth: 'Nov' },
    { overallScore: 71, scoreMonth: 'Dec' },
    { overallScore: 71, scoreMonth: 'Jan' },
    { overallScore: 72, scoreMonth: 'Feb' },
  ],

  mfaStatus: {
    status: {
      enabled: true,
      method: 'totp',
      lastUsedAt: new Date(now.getTime() - 86400000).toISOString(),
      backupCodesRemaining: 7,
    },
  },

  insightsTransactions: [
    { id: 'ins-1', description: 'Shoprite', amount: -45000, category: 'food', date: now.toISOString() },
    { id: 'ins-2', description: 'Uber', amount: -3500, category: 'transport', date: now.toISOString() },
  ],
};
