// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     underwriting_event.avsc
 */
package events

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type DecisionMadePayload struct {
	// The final underwriting decision.
	Decision Decision `json:"decision"`
	// The calculated risk score.
	Risk_score float64 `json:"risk_score"`
	// Version of the risk model used.
	Risk_model_version string `json:"risk_model_version"`
}

const DecisionMadePayloadAvroCRC64Fingerprint = "\"\x9d'ej\x9ez\xaa"

func NewDecisionMadePayload() DecisionMadePayload {
	r := DecisionMadePayload{}
	return r
}

func DeserializeDecisionMadePayload(r io.Reader) (DecisionMadePayload, error) {
	t := NewDecisionMadePayload()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeDecisionMadePayloadFromSchema(r io.Reader, schema string) (DecisionMadePayload, error) {
	t := NewDecisionMadePayload()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeDecisionMadePayload(r DecisionMadePayload, w io.Writer) error {
	var err error
	err = writeDecision(r.Decision, w)
	if err != nil {
		return err
	}
	err = vm.WriteDouble(r.Risk_score, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Risk_model_version, w)
	if err != nil {
		return err
	}
	return err
}

func (r DecisionMadePayload) Serialize(w io.Writer) error {
	return writeDecisionMadePayload(r, w)
}

func (r DecisionMadePayload) Schema() string {
	return "{\"fields\":[{\"doc\":\"The final underwriting decision.\",\"name\":\"decision\",\"type\":{\"name\":\"Decision\",\"symbols\":[\"APPROVED\",\"REJECTED\"],\"type\":\"enum\"}},{\"doc\":\"The calculated risk score.\",\"name\":\"risk_score\",\"type\":\"double\"},{\"doc\":\"Version of the risk model used.\",\"name\":\"risk_model_version\",\"type\":\"string\"}],\"name\":\"com.openimis.insurance.underwriting.DecisionMadePayload\",\"type\":\"record\"}"
}

func (r DecisionMadePayload) SchemaName() string {
	return "com.openimis.insurance.underwriting.DecisionMadePayload"
}

func (_ DecisionMadePayload) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ DecisionMadePayload) SetInt(v int32)       { panic("Unsupported operation") }
func (_ DecisionMadePayload) SetLong(v int64)      { panic("Unsupported operation") }
func (_ DecisionMadePayload) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ DecisionMadePayload) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ DecisionMadePayload) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ DecisionMadePayload) SetString(v string)   { panic("Unsupported operation") }
func (_ DecisionMadePayload) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *DecisionMadePayload) Get(i int) types.Field {
	switch i {
	case 0:
		w := DecisionWrapper{Target: &r.Decision}

		return w

	case 1:
		w := types.Double{Target: &r.Risk_score}

		return w

	case 2:
		w := types.String{Target: &r.Risk_model_version}

		return w

	}
	panic("Unknown field index")
}

func (r *DecisionMadePayload) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *DecisionMadePayload) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ DecisionMadePayload) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ DecisionMadePayload) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ DecisionMadePayload) HintSize(int)                     { panic("Unsupported operation") }
func (_ DecisionMadePayload) Finalize()                        {}

func (_ DecisionMadePayload) AvroCRC64Fingerprint() []byte {
	return []byte(DecisionMadePayloadAvroCRC64Fingerprint)
}

func (r DecisionMadePayload) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["decision"], err = json.Marshal(r.Decision)
	if err != nil {
		return nil, err
	}
	output["risk_score"], err = json.Marshal(r.Risk_score)
	if err != nil {
		return nil, err
	}
	output["risk_model_version"], err = json.Marshal(r.Risk_model_version)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *DecisionMadePayload) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["decision"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Decision); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for decision")
	}
	val = func() json.RawMessage {
		if v, ok := fields["risk_score"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Risk_score); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for risk_score")
	}
	val = func() json.RawMessage {
		if v, ok := fields["risk_model_version"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Risk_model_version); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for risk_model_version")
	}
	return nil
}
