package main
import ("encoding/json";"fmt";"net/http";"os")
func envOr(k,d string)string{if v:=os.Getenv(k);v!=""{return v};return d}
var mw=map[string]interface{}{"kafka":map[string]interface{}{"broker":envOr("KAFKA_BROKER","localhost:9092"),"topics":[]string{"agent-kyc.captured","agent-kyc.synced","agent-kyc.quality-score"}},"dapr":map[string]interface{}{"app_id":"agent-kyc-capture-go"},"fluvio":map[string]interface{}{"url":envOr("FLUVIO_URL","localhost:9003")},"temporal":map[string]interface{}{"url":envOr("TEMPORAL_URL","localhost:7233"),"namespace":"agent-kyc"},"postgres":map[string]interface{}{"url":envOr("DATABASE_URL","postgresql://ndsep_user:ndsep_secure_2026@localhost:5432/ndsep_db"),"tables":[]string{"agent_kyc_captures","agent_quality_scores"}},"keycloak":map[string]interface{}{"url":envOr("KEYCLOAK_URL","http://localhost:8080"),"realm":"54bank"},"permify":map[string]interface{}{"url":envOr("PERMIFY_URL","http://localhost:3476")},"redis":map[string]interface{}{"url":envOr("REDIS_URL","redis://localhost:6379")},"mojaloop":map[string]interface{}{"url":envOr("MOJALOOP_URL","http://localhost:3002")},"opensearch":map[string]interface{}{"url":envOr("OPENSEARCH_URL","http://localhost:9200")},"openappsec":map[string]interface{}{"url":envOr("OPENAPPSEC_URL","http://localhost:4000")},"apisix":map[string]interface{}{"url":envOr("APISIX_URL","http://localhost:9080")},"tigerbeetle":map[string]interface{}{"url":envOr("TIGERBEETLE_URL","localhost:3000")},"lakehouse":map[string]interface{}{"url":envOr("LAKEHOUSE_URL","http://localhost:8181")}}
type AgentCapture struct{ID string`json:"id"`;AgentID string`json:"agentId"`;AgentName string`json:"agentName"`;CustomerName string`json:"customerName"`;CaptureType string`json:"captureType"`;GeoLat float64`json:"geoLat"`;GeoLng float64`json:"geoLng"`;LGA string`json:"lga"`;OfflineCapture bool`json:"offlineCapture"`;SyncStatus string`json:"syncStatus"`;QualityScore float64`json:"qualityScore"`;CapturedAt string`json:"capturedAt"`}
var captures=[]AgentCapture{{ID:"AC-001",AgentID:"AGT-101",AgentName:"Bola Adesanya",CustomerName:"Musa Ibrahim",CaptureType:"full_kyc_tier2",GeoLat:6.5244,GeoLng:3.3792,LGA:"Ikeja",OfflineCapture:false,SyncStatus:"synced",QualityScore:0.92,CapturedAt:"2026-05-12T10:00:00Z"},{ID:"AC-002",AgentID:"AGT-102",AgentName:"Chidinma Eze",CustomerName:"Halima Yusuf",CaptureType:"document_reverify",GeoLat:9.0765,GeoLng:7.4986,LGA:"Garki",OfflineCapture:true,SyncStatus:"pending_sync",QualityScore:0.85,CapturedAt:"2026-05-12T11:30:00Z"}}
func main(){
	port:=envOr("PORT","8295")
	http.HandleFunc("/healthz",func(w http.ResponseWriter,r*http.Request){json.NewEncoder(w).Encode(map[string]interface{}{"status":"healthy","service":"agent-kyc-capture-go","version":"1.0.0","middleware":mw})})
	http.HandleFunc("/api/captures",func(w http.ResponseWriter,r*http.Request){json.NewEncoder(w).Encode(map[string]interface{}{"items":captures,"total":len(captures)})})
	fmt.Printf("agent-kyc-capture-go listening on :%s\n",port)
	http.ListenAndServe(":"+port,nil)
}
