apiVersion: v2
name: 54bank
description: 54Bank Core Banking Platform — 186 microservices (Go/Rust/Python)
type: application
version: 2.0.0
appVersion: "2.0.0"
keywords:
  - banking
  - fintech
  - microservices
  - nigeria
maintainers:
  - name: 54Bank Platform Team
    email: platform@54bank.app
