import mysql from 'mysql2/promise';
const url = process.env.DATABASE_URL;
const urlObj = new URL(url);
const conn = await mysql.createConnection({
  host: urlObj.hostname, port: parseInt(urlObj.port || '4000'),
  user: urlObj.username, password: urlObj.password,
  database: urlObj.pathname.replace(/^\//, '').split('?')[0],
  ssl: { rejectUnauthorized: false },
  multipleStatements: false,
});

const tables = [
  `CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    open_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    email VARCHAR(255),
    avatar VARCHAR(512),
    role ENUM('user','admin','auditor','org_admin') DEFAULT 'user',
    organization_id INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS organizations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    sector VARCHAR(128),
    country VARCHAR(64) DEFAULT 'NG',
    compliance_score INT DEFAULT 0,
    compliance_status VARCHAR(64) DEFAULT 'under_review',
    risk_score INT DEFAULT 50,
    contact_email VARCHAR(256),
    regulatory_id VARCHAR(128),
    dpo_name VARCHAR(256),
    dpo_email VARCHAR(256),
    address TEXT,
    website VARCHAR(256),
    employee_count INT,
    data_volume_tb FLOAT DEFAULT 0,
    last_audit_date DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS assets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    name VARCHAR(256) NOT NULL,
    asset_type ENUM('hardware','software','cloud','network','database','saas') NOT NULL,
    status ENUM('active','inactive','quarantined','decommissioned') DEFAULT 'active',
    ip_address VARCHAR(64),
    location VARCHAR(256),
    data_classification ENUM('tier1_pii','tier2_financial','tier3_health','tier4_government','tier5_public'),
    owner VARCHAR(256),
    description TEXT,
    tags JSON,
    last_seen DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS compliance_policies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    framework VARCHAR(128),
    version VARCHAR(32),
    status VARCHAR(64) DEFAULT 'active',
    description TEXT,
    policy_definition JSON,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS compliance_violations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    policy_id INT,
    violation_type VARCHAR(128),
    severity ENUM('critical','high','medium','low','info') DEFAULT 'medium',
    description TEXT,
    status VARCHAR(64) DEFAULT 'open',
    detected_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    resolved_at DATETIME,
    evidence JSON,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS enforcement_actions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    case_id INT,
    action_type VARCHAR(128) NOT NULL,
    description TEXT,
    status VARCHAR(64) DEFAULT 'pending',
    due_date DATETIME,
    completed_at DATETIME,
    created_by INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS financial_penalties (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    violation_id INT,
    amount FLOAT NOT NULL,
    currency VARCHAR(8) DEFAULT 'NGN',
    status ENUM('pending','processing','completed','overdue','disputed') DEFAULT 'pending',
    description TEXT,
    due_date DATETIME,
    paid_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS security_alerts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(256) NOT NULL,
    description TEXT,
    severity ENUM('critical','high','medium','low','info') DEFAULT 'medium',
    source VARCHAR(128),
    status VARCHAR(64) DEFAULT 'open',
    organization_id INT,
    alert_type VARCHAR(128),
    raw_data JSON,
    resolved_at DATETIME,
    resolved_by INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS network_events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT,
    event_type ENUM('cross_border_transfer','exfiltration_attempt','anomaly','policy_violation','normal') DEFAULT 'normal',
    source_ip VARCHAR(64),
    destination_ip VARCHAR(64),
    destination_country VARCHAR(8),
    protocol VARCHAR(32),
    bytes_transferred BIGINT DEFAULT 0,
    is_flagged BOOLEAN DEFAULT FALSE,
    risk_score INT DEFAULT 0,
    metadata JSON,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS threat_intelligence (
    id INT AUTO_INCREMENT PRIMARY KEY,
    indicator_type VARCHAR(64) NOT NULL,
    indicator_value VARCHAR(512) NOT NULL,
    threat_type VARCHAR(128),
    severity ENUM('critical','high','medium','low','info') DEFAULT 'medium',
    confidence INT DEFAULT 50,
    source VARCHAR(256),
    tags JSON,
    first_seen DATETIME,
    last_seen DATETIME,
    is_active BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS audit_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    action VARCHAR(256) NOT NULL,
    resource_type VARCHAR(128),
    resource_id INT,
    details TEXT,
    ip_address VARCHAR(64),
    user_agent TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS streaming_events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    topic VARCHAR(256) NOT NULL,
    event_type VARCHAR(128),
    payload JSON,
    source VARCHAR(256),
    processed BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS data_catalog_entries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    name VARCHAR(256) NOT NULL,
    description TEXT,
    data_classification ENUM('tier1_pii','tier2_financial','tier3_health','tier4_government','tier5_public'),
    storage_location VARCHAR(512),
    storage_country VARCHAR(8),
    is_cross_border BOOLEAN DEFAULT FALSE,
    data_volume_gb FLOAT DEFAULT 0,
    retention_days INT,
    owner VARCHAR(256),
    tags JSON,
    last_scanned DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS ml_risk_predictions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    predicted_risk_score FLOAT NOT NULL,
    confidence FLOAT,
    risk_factors JSON,
    model_version VARCHAR(64),
    predicted_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS bgp_routes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    prefix VARCHAR(64) NOT NULL,
    origin_asn INT,
    next_hop VARCHAR(64),
    as_path TEXT,
    status ENUM('valid','invalid','unknown','hijacked','leaked') DEFAULT 'unknown',
    country VARCHAR(8),
    is_anomalous BOOLEAN DEFAULT FALSE,
    anomaly_reason TEXT,
    last_seen DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS residency_checks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    asset_id INT,
    check_type VARCHAR(128),
    status ENUM('compliant','violation','warning','unknown') DEFAULT 'unknown',
    storage_location VARCHAR(512),
    storage_country VARCHAR(8),
    expected_country VARCHAR(8) DEFAULT 'NG',
    violation_details TEXT,
    checked_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS financial_ledger (
    id INT AUTO_INCREMENT PRIMARY KEY,
    penalty_id INT,
    organization_id INT,
    transaction_type VARCHAR(128),
    amount FLOAT NOT NULL,
    currency VARCHAR(8) DEFAULT 'NGN',
    reference VARCHAR(256),
    description TEXT,
    status VARCHAR(64) DEFAULT 'pending',
    tigerbeetle_tx_id VARCHAR(256),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS portal_submissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    submission_token VARCHAR(256) UNIQUE,
    org_name VARCHAR(256),
    org_sector VARCHAR(64),
    org_country VARCHAR(8) DEFAULT 'NG',
    regulatory_id VARCHAR(128),
    contact_name VARCHAR(256),
    contact_email VARCHAR(256),
    contact_phone VARCHAR(64),
    current_phase VARCHAR(64) DEFAULT 'initial_registration',
    status VARCHAR(64) DEFAULT 'draft',
    submitted_at DATETIME,
    approved_at DATETIME,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS onboarding_phases (
    id INT AUTO_INCREMENT PRIMARY KEY,
    submission_id INT NOT NULL,
    phase VARCHAR(64) NOT NULL,
    status VARCHAR(64) DEFAULT 'pending',
    completed_at DATETIME,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS transfer_approvals (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    data_type VARCHAR(128),
    destination_country VARCHAR(8),
    recipient_name VARCHAR(256),
    recipient_country VARCHAR(8),
    data_volume_gb FLOAT DEFAULT 0,
    purpose TEXT,
    legal_basis VARCHAR(256),
    safeguards TEXT,
    status ENUM('pending','approved','rejected','expired','revoked') DEFAULT 'pending',
    reviewed_by INT,
    reviewed_at DATETIME,
    expires_at DATETIME,
    rejection_reason TEXT,
    approval_conditions TEXT,
    nitda_reference VARCHAR(128),
    dpa_reference VARCHAR(128),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS monitoring_snapshots (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    compliance_score INT,
    violation_count INT DEFAULT 0,
    penalty_count INT DEFAULT 0,
    open_cases INT DEFAULT 0,
    risk_score INT DEFAULT 50,
    sla_breach_count INT DEFAULT 0,
    snapshot_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS sla_breaches (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    breach_type VARCHAR(128),
    description TEXT,
    severity ENUM('critical','high','medium','low','info') DEFAULT 'medium',
    status VARCHAR(64) DEFAULT 'open',
    sla_deadline DATETIME,
    breached_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    resolved_at DATETIME
  )`,
  `CREATE TABLE IF NOT EXISTS drift_alerts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    alert_type VARCHAR(128),
    description TEXT,
    severity ENUM('critical','high','medium','low','info') DEFAULT 'medium',
    status VARCHAR(64) DEFAULT 'open',
    detected_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    resolved_at DATETIME
  )`,
  `CREATE TABLE IF NOT EXISTS policy_templates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    framework VARCHAR(128),
    version VARCHAR(32),
    description TEXT,
    status VARCHAR(64) DEFAULT 'active',
    policy_definition JSON,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS ai_systems (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    name VARCHAR(256) NOT NULL,
    description TEXT,
    risk_level ENUM('minimal','limited','high','unacceptable') DEFAULT 'limited',
    status ENUM('active','inactive','under_review','suspended') DEFAULT 'active',
    use_case TEXT,
    training_data_sources JSON,
    compliance_notes TEXT,
    last_reviewed DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS evidence_packages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    case_id INT,
    title VARCHAR(256) NOT NULL,
    description TEXT,
    evidence_type VARCHAR(128),
    file_url VARCHAR(512),
    file_hash VARCHAR(256),
    collected_by INT,
    status VARCHAR(64) DEFAULT 'pending',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS sectors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    code VARCHAR(32) NOT NULL UNIQUE,
    parent_id INT,
    description TEXT,
    regulatory_framework VARCHAR(128),
    org_count INT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS citizen_requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    request_type ENUM('access','erasure','portability','rectification','restriction','objection') NOT NULL,
    citizen_name VARCHAR(256) NOT NULL,
    citizen_email VARCHAR(256) NOT NULL,
    citizen_nin VARCHAR(128),
    organization_id INT,
    description TEXT,
    status ENUM('submitted','under_review','fulfilled','rejected','escalated') DEFAULT 'submitted',
    response_notes TEXT,
    due_date DATETIME,
    submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    resolved_at DATETIME
  )`,
  `CREATE TABLE IF NOT EXISTS config_snapshots (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    snapshot_type VARCHAR(128),
    config_data JSON,
    status ENUM('active','archived','superseded') DEFAULT 'active',
    version VARCHAR(64),
    notes TEXT,
    created_by INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS tia_assessments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    transfer_destination VARCHAR(8),
    data_categories JSON,
    recipient_name VARCHAR(256),
    recipient_country VARCHAR(8),
    legal_basis VARCHAR(256),
    safeguards TEXT,
    risk_level ENUM('low','medium','high','critical') DEFAULT 'medium',
    status ENUM('draft','submitted','under_review','approved','rejected') DEFAULT 'draft',
    assessment_notes TEXT,
    reviewed_by INT,
    reviewed_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS remediation_workflows (
    id INT AUTO_INCREMENT PRIMARY KEY,
    org_id VARCHAR(64) NOT NULL,
    violation_type VARCHAR(128),
    status ENUM('pending','in_progress','completed','overdue','cancelled') DEFAULT 'pending',
    steps JSON,
    assigned_to VARCHAR(256),
    due_date DATETIME,
    completed_at DATETIME,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS enforcement_cases (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL,
    penalty_id INT,
    case_reference VARCHAR(128) UNIQUE,
    status ENUM('open','under_investigation','notice_issued','escalated_to_nitda','settled','closed') DEFAULT 'open',
    severity ENUM('critical','high','medium','low','info') DEFAULT 'high',
    escalation_reason TEXT,
    nitda_reference_number VARCHAR(128),
    assigned_officer_id INT,
    resolution_notes TEXT,
    opened_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    closed_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS case_timeline (
    id INT AUTO_INCREMENT PRIMARY KEY,
    case_id INT NOT NULL,
    changed_by_user_id INT,
    changed_by_name VARCHAR(256),
    from_status VARCHAR(64),
    to_status VARCHAR(64),
    note TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS notification_settings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    organization_id INT NOT NULL UNIQUE,
    penalty_issued BOOLEAN DEFAULT TRUE,
    penalty_paid BOOLEAN DEFAULT TRUE,
    penalty_appeal_filed BOOLEAN DEFAULT TRUE,
    penalty_appeal_decision BOOLEAN DEFAULT TRUE,
    enforcement_case_opened BOOLEAN DEFAULT TRUE,
    certificate_granted BOOLEAN DEFAULT TRUE,
    portal_phase_update BOOLEAN DEFAULT TRUE,
    citizen_request_update BOOLEAN DEFAULT TRUE,
    sla_breach_warning BOOLEAN DEFAULT TRUE,
    compliance_score_change BOOLEAN DEFAULT FALSE,
    dpo_email VARCHAR(256),
    technical_email VARCHAR(256),
    legal_email VARCHAR(256),
    digest_frequency ENUM('immediate','daily','weekly') DEFAULT 'immediate',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`,
];

let created = 0;
let skipped = 0;
for (const sql of tables) {
  const tableName = sql.match(/CREATE TABLE IF NOT EXISTS (\w+)/)?.[1];
  try {
    await conn.query(sql);
    console.log(`✅ ${tableName}`);
    created++;
  } catch(e) {
    console.error(`❌ ${tableName}: ${e.message}`);
    skipped++;
  }
}
console.log(`\nDone: ${created} created/verified, ${skipped} errors`);
await conn.end();
