// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     claim_event.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type ClaimEvent struct {
	// Unique identifier for the claim.
	Claim_id string `json:"claim_id"`
	// Identifier for the policy associated with the claim.
	Policy_id string `json:"policy_id"`
	// The lifecycle stage of the claim.
	Event_type ClaimEventType `json:"event_type"`
	// Unix epoch timestamp (milliseconds) of the event.
	Event_timestamp int64 `json:"event_timestamp"`
	// The monetary amount of the claim.
	Claim_amount float64 `json:"claim_amount"`
	// Enriched data: The current loss ratio for the policy/portfolio.
	Loss_ratio float64 `json:"loss_ratio"`
}

const ClaimEventAvroCRC64Fingerprint = "͌\x96\xfa{a>p"

func NewClaimEvent() ClaimEvent {
	r := ClaimEvent{}
	return r
}

func DeserializeClaimEvent(r io.Reader) (ClaimEvent, error) {
	t := NewClaimEvent()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeClaimEventFromSchema(r io.Reader, schema string) (ClaimEvent, error) {
	t := NewClaimEvent()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeClaimEvent(r ClaimEvent, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Claim_id, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Policy_id, w)
	if err != nil {
		return err
	}
	err = writeClaimEventType(r.Event_type, w)
	if err != nil {
		return err
	}
	err = vm.WriteLong(r.Event_timestamp, w)
	if err != nil {
		return err
	}
	err = vm.WriteDouble(r.Claim_amount, w)
	if err != nil {
		return err
	}
	err = vm.WriteDouble(r.Loss_ratio, w)
	if err != nil {
		return err
	}
	return err
}

func (r ClaimEvent) Serialize(w io.Writer) error {
	return writeClaimEvent(r, w)
}

func (r ClaimEvent) Schema() string {
	return "{\"fields\":[{\"doc\":\"Unique identifier for the claim.\",\"name\":\"claim_id\",\"type\":\"string\"},{\"doc\":\"Identifier for the policy associated with the claim.\",\"name\":\"policy_id\",\"type\":\"string\"},{\"doc\":\"The lifecycle stage of the claim.\",\"name\":\"event_type\",\"type\":{\"name\":\"ClaimEventType\",\"symbols\":[\"REPORTED\",\"APPROVED\",\"PAID\",\"DENIED\"],\"type\":\"enum\"}},{\"doc\":\"Unix epoch timestamp (milliseconds) of the event.\",\"name\":\"event_timestamp\",\"type\":\"long\"},{\"doc\":\"The monetary amount of the claim.\",\"name\":\"claim_amount\",\"type\":\"double\"},{\"doc\":\"Enriched data: The current loss ratio for the policy/portfolio.\",\"name\":\"loss_ratio\",\"type\":\"double\"}],\"name\":\"com.openimis.insurance.ClaimEvent\",\"type\":\"record\"}"
}

func (r ClaimEvent) SchemaName() string {
	return "com.openimis.insurance.ClaimEvent"
}

func (_ ClaimEvent) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ ClaimEvent) SetInt(v int32)       { panic("Unsupported operation") }
func (_ ClaimEvent) SetLong(v int64)      { panic("Unsupported operation") }
func (_ ClaimEvent) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ ClaimEvent) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ ClaimEvent) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ ClaimEvent) SetString(v string)   { panic("Unsupported operation") }
func (_ ClaimEvent) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *ClaimEvent) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.Claim_id}

		return w

	case 1:
		w := types.String{Target: &r.Policy_id}

		return w

	case 2:
		w := ClaimEventTypeWrapper{Target: &r.Event_type}

		return w

	case 3:
		w := types.Long{Target: &r.Event_timestamp}

		return w

	case 4:
		w := types.Double{Target: &r.Claim_amount}

		return w

	case 5:
		w := types.Double{Target: &r.Loss_ratio}

		return w

	}
	panic("Unknown field index")
}

func (r *ClaimEvent) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *ClaimEvent) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ ClaimEvent) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ ClaimEvent) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ ClaimEvent) HintSize(int)                     { panic("Unsupported operation") }
func (_ ClaimEvent) Finalize()                        {}

func (_ ClaimEvent) AvroCRC64Fingerprint() []byte {
	return []byte(ClaimEventAvroCRC64Fingerprint)
}

func (r ClaimEvent) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["claim_id"], err = json.Marshal(r.Claim_id)
	if err != nil {
		return nil, err
	}
	output["policy_id"], err = json.Marshal(r.Policy_id)
	if err != nil {
		return nil, err
	}
	output["event_type"], err = json.Marshal(r.Event_type)
	if err != nil {
		return nil, err
	}
	output["event_timestamp"], err = json.Marshal(r.Event_timestamp)
	if err != nil {
		return nil, err
	}
	output["claim_amount"], err = json.Marshal(r.Claim_amount)
	if err != nil {
		return nil, err
	}
	output["loss_ratio"], err = json.Marshal(r.Loss_ratio)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *ClaimEvent) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["claim_id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Claim_id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for claim_id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["policy_id"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Policy_id); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for policy_id")
	}
	val = func() json.RawMessage {
		if v, ok := fields["event_type"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Event_type); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for event_type")
	}
	val = func() json.RawMessage {
		if v, ok := fields["event_timestamp"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Event_timestamp); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for event_timestamp")
	}
	val = func() json.RawMessage {
		if v, ok := fields["claim_amount"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Claim_amount); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for claim_amount")
	}
	val = func() json.RawMessage {
		if v, ok := fields["loss_ratio"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Loss_ratio); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for loss_ratio")
	}
	return nil
}
