// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     claim_event.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type ClaimEventType int32

const (
	ClaimEventTypeREPORTED ClaimEventType = 0
	ClaimEventTypeAPPROVED ClaimEventType = 1
	ClaimEventTypePAID     ClaimEventType = 2
	ClaimEventTypeDENIED   ClaimEventType = 3
)

func (e ClaimEventType) String() string {
	switch e {
	case ClaimEventTypeREPORTED:
		return "REPORTED"
	case ClaimEventTypeAPPROVED:
		return "APPROVED"
	case ClaimEventTypePAID:
		return "PAID"
	case ClaimEventTypeDENIED:
		return "DENIED"
	}
	return "unknown"
}

func writeClaimEventType(r ClaimEventType, w io.Writer) error {
	return vm.WriteInt(int32(r), w)
}

func NewClaimEventTypeValue(raw string) (r ClaimEventType, err error) {
	switch raw {
	case "REPORTED":
		return ClaimEventTypeREPORTED, nil
	case "APPROVED":
		return ClaimEventTypeAPPROVED, nil
	case "PAID":
		return ClaimEventTypePAID, nil
	case "DENIED":
		return ClaimEventTypeDENIED, nil
	}

	return -1, fmt.Errorf("invalid value for ClaimEventType: '%s'", raw)

}

func (b ClaimEventType) MarshalJSON() ([]byte, error) {
	return json.Marshal(b.String())
}

func (b *ClaimEventType) UnmarshalJSON(data []byte) error {
	var stringVal string
	err := json.Unmarshal(data, &stringVal)
	if err != nil {
		return err
	}
	val, err := NewClaimEventTypeValue(stringVal)
	*b = val
	return err
}

type ClaimEventTypeWrapper struct {
	Target *ClaimEventType
}

func (b ClaimEventTypeWrapper) SetBoolean(v bool) {
	panic("Unable to assign boolean to int field")
}

func (b ClaimEventTypeWrapper) SetInt(v int32) {
	*(b.Target) = ClaimEventType(v)
}

func (b ClaimEventTypeWrapper) SetLong(v int64) {
	panic("Unable to assign long to int field")
}

func (b ClaimEventTypeWrapper) SetFloat(v float32) {
	panic("Unable to assign float to int field")
}

func (b ClaimEventTypeWrapper) SetUnionElem(v int64) {
	panic("Unable to assign union elem to int field")
}

func (b ClaimEventTypeWrapper) SetDouble(v float64) {
	panic("Unable to assign double to int field")
}

func (b ClaimEventTypeWrapper) SetBytes(v []byte) {
	panic("Unable to assign bytes to int field")
}

func (b ClaimEventTypeWrapper) SetString(v string) {
	panic("Unable to assign string to int field")
}

func (b ClaimEventTypeWrapper) Get(i int) types.Field {
	panic("Unable to get field from int field")
}

func (b ClaimEventTypeWrapper) SetDefault(i int) {
	panic("Unable to set default on int field")
}

func (b ClaimEventTypeWrapper) AppendMap(key string) types.Field {
	panic("Unable to append map key to from int field")
}

func (b ClaimEventTypeWrapper) AppendArray() types.Field {
	panic("Unable to append array element to from int field")
}

func (b ClaimEventTypeWrapper) NullField(int) {
	panic("Unable to null field in int field")
}

func (b ClaimEventTypeWrapper) HintSize(int) {
	panic("Unable to hint size in int field")
}

func (b ClaimEventTypeWrapper) Finalize() {}
