apiVersion: v1
kind: Service
metadata:
  name: gif-metrics-exporter
  labels:
    app: gif-metrics-exporter
spec:
  selector:
    app: gif-metrics-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
  type: ClusterIP
