package main
import ("encoding/json";"fmt";"net/http";"os")
func envOr(k,d string)string{if v:=os.Getenv(k);v!=""{return v};return d}
var mw=map[string]interface{}{"kafka":map[string]interface{}{"broker":envOr("KAFKA_BROKER","localhost:9092"),"topics":[]string{"corp-monitor.director-change","corp-monitor.filing-overdue","corp-monitor.adverse-event"}},"dapr":map[string]interface{}{"app_id":"corporate-monitoring-go"},"fluvio":map[string]interface{}{"url":envOr("FLUVIO_URL","localhost:9003")},"temporal":map[string]interface{}{"url":envOr("TEMPORAL_URL","localhost:7233"),"namespace":"corporate-monitoring"},"postgres":map[string]interface{}{"url":envOr("DATABASE_URL","postgresql://ndsep_user:ndsep_secure_2026@localhost:5432/ndsep_db")},"keycloak":map[string]interface{}{"url":envOr("KEYCLOAK_URL","http://localhost:8080"),"realm":"54bank"},"permify":map[string]interface{}{"url":envOr("PERMIFY_URL","http://localhost:3476")},"redis":map[string]interface{}{"url":envOr("REDIS_URL","redis://localhost:6379")},"mojaloop":map[string]interface{}{"url":envOr("MOJALOOP_URL","http://localhost:3002")},"opensearch":map[string]interface{}{"url":envOr("OPENSEARCH_URL","http://localhost:9200")},"openappsec":map[string]interface{}{"url":envOr("OPENAPPSEC_URL","http://localhost:4000")},"apisix":map[string]interface{}{"url":envOr("APISIX_URL","http://localhost:9080")},"tigerbeetle":map[string]interface{}{"url":envOr("TIGERBEETLE_URL","localhost:3000")},"lakehouse":map[string]interface{}{"url":envOr("LAKEHOUSE_URL","http://localhost:8181")}}
type MonitorEvent struct{ID string`json:"id"`;CompanyID string`json:"companyId"`;CompanyName string`json:"companyName"`;EventType string`json:"eventType"`;Details string`json:"details"`;RiskImpact string`json:"riskImpact"`;DetectedAt string`json:"detectedAt"`;Action string`json:"action"`}
var events=[]MonitorEvent{{ID:"ME-001",CompanyID:"CAC-002",CompanyName:"ABC Import Export Ltd",EventType:"annual_return_overdue",Details:"Annual return overdue since Dec 2023 — 2+ years without filing",RiskImpact:"high",DetectedAt:"2026-05-12T06:00:00Z",Action:"notify_compliance_officer"},{ID:"ME-002",CompanyID:"CAC-003",CompanyName:"Quantum Resources Nigeria Ltd",EventType:"investigation_status_change",Details:"EFCC investigation status updated — charges filed",RiskImpact:"critical",DetectedAt:"2026-05-12T08:00:00Z",Action:"restrict_account_immediately"}}
func main(){
	port:=envOr("PORT","8300")
	http.HandleFunc("/healthz",func(w http.ResponseWriter,r*http.Request){json.NewEncoder(w).Encode(map[string]interface{}{"status":"healthy","service":"corporate-monitoring-go","version":"1.0.0","middleware":mw})})
	http.HandleFunc("/api/events",func(w http.ResponseWriter,r*http.Request){json.NewEncoder(w).Encode(map[string]interface{}{"items":events,"total":len(events)})})
	fmt.Printf("corporate-monitoring-go listening on :%s\n",port)
	http.ListenAndServe(":"+port,nil)
}
