import { View, Text, ScrollView, TouchableOpacity, Alert, Dimensions } from 'react-native';
import { Stack, useLocalSearchParams, useRouter } from 'expo-router';
import { useState, useEffect } from 'react';
import { ScreenContainer } from '@/components/screen-container';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Haptics from 'expo-haptics';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';

interface FinancialReport {
  id: string;
  period: string;
  type: 'monthly' | 'quarterly' | 'yearly';
  startDate: string;
  endDate: string;
  totalIncome: number;
  totalExpenses: number;
  netSavings: number;
  savingsRate: number;
  generatedAt: string;
}

interface CategoryBreakdown {
  category: string;
  amount: number;
  percentage: number;
}

export default function ReportDetailScreen() {
  const params = useLocalSearchParams();
  const router = useRouter();
  const reportId = params.id as string;

  const [report, setReport] = useState<FinancialReport | null>(null);
  const [expenseBreakdown, setExpenseBreakdown] = useState<CategoryBreakdown[]>([]);

  useEffect(() => {
    loadReport();
  }, [reportId]);

  const loadReport = async () => {
    try {
      const stored = await AsyncStorage.getItem('financialReports');
      if (stored) {
        const reports: FinancialReport[] = JSON.parse(stored);
        const found = reports.find(r => r.id === reportId);
        if (found) {
          setReport(found);
          // Mock expense breakdown
          setExpenseBreakdown([
            { category: 'Housing', amount: found.totalExpenses * 0.35, percentage: 35 },
            { category: 'Food', amount: found.totalExpenses * 0.25, percentage: 25 },
            { category: 'Transportation', amount: found.totalExpenses * 0.15, percentage: 15 },
            { category: 'Utilities', amount: found.totalExpenses * 0.10, percentage: 10 },
            { category: 'Entertainment', amount: found.totalExpenses * 0.08, percentage: 8 },
            { category: 'Other', amount: found.totalExpenses * 0.07, percentage: 7 },
          ]);
        }
      }
    } catch (error) {
      console.error('Failed to load report:', error);
    }
  };

  const exportReport = async () => {
    if (!report) return;

    try {
      await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);

      const pdfContent = `
FINANCIAL REPORT
${report.period}

Generated on ${new Date(report.generatedAt).toLocaleDateString()}
Period: ${new Date(report.startDate).toLocaleDateString()} - ${new Date(report.endDate).toLocaleDateString()}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SUMMARY
Total Income:      $${report.totalIncome.toLocaleString()}
Total Expenses:    $${report.totalExpenses.toLocaleString()}
Net Savings:       $${report.netSavings.toLocaleString()}
Savings Rate:      ${report.savingsRate.toFixed(1)}%

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EXPENSE BREAKDOWN
${expenseBreakdown.map(cat => 
  `${cat.category.padEnd(20)} $${cat.amount.toLocaleString().padEnd(10)} ${cat.percentage}%`
).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This report was generated by your African Fintech Mobile App.
      `.trim();

      const fileName = `financial-report-${report.period.replace(/\s+/g, '-')}.txt`;
      const fileUri = `${FileSystem.documentDirectory}${fileName}`;

      await FileSystem.writeAsStringAsync(fileUri, pdfContent, {
        encoding: FileSystem.EncodingType.UTF8,
      });

      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(fileUri, {
          mimeType: 'text/plain',
          dialogTitle: 'Share Financial Report',
        });
      } else {
        Alert.alert('Success', `Report saved to ${fileUri}`);
      }

      await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch (error) {
      console.error('Failed to export report:', error);
      Alert.alert('Error', 'Failed to export report');
    }
  };

  if (!report) {
    return (
      <ScreenContainer className="p-4">
        <Stack.Screen options={{ title: 'Report Detail', headerShown: true }} />
        <View className="flex-1 justify-center items-center">
          <Text className="text-muted">Loading...</Text>
        </View>
      </ScreenContainer>
    );
  }

  const getSavingsColor = (rate: number) => {
    if (rate >= 30) return 'text-success';
    if (rate >= 15) return 'text-warning';
    return 'text-error';
  };

  const screenWidth = Dimensions.get('window').width - 32; // padding

  return (
    <ScreenContainer className="p-4">
      <Stack.Screen options={{ title: report.period, headerShown: true }} />

      <ScrollView showsVerticalScrollIndicator={false}>
        {/* Summary Card */}
        <View className="bg-primary/10 rounded-xl p-6 mb-6 border border-primary/30">
          <Text className="text-foreground font-bold text-3xl mb-2">{report.period}</Text>
          <View className="bg-primary/20 px-3 py-1 rounded-full self-start mb-4">
            <Text className="text-primary text-xs font-semibold uppercase">{report.type}</Text>
          </View>
          <Text className="text-muted text-sm">
            {new Date(report.startDate).toLocaleDateString()} - {new Date(report.endDate).toLocaleDateString()}
          </Text>
        </View>

        {/* Income & Expenses */}
        <View className="bg-surface rounded-xl p-6 mb-6 border border-border">
          <Text className="text-foreground font-bold text-lg mb-4">Income & Expenses</Text>
          
          <View className="gap-4">
            <View>
              <View className="flex-row justify-between mb-2">
                <Text className="text-muted">Total Income</Text>
                <Text className="text-success font-bold text-xl">
                  +${report.totalIncome.toLocaleString()}
                </Text>
              </View>
              <View className="h-2 bg-success/20 rounded-full overflow-hidden">
                <View className="h-full bg-success rounded-full" style={{ width: '100%' }} />
              </View>
            </View>

            <View>
              <View className="flex-row justify-between mb-2">
                <Text className="text-muted">Total Expenses</Text>
                <Text className="text-error font-bold text-xl">
                  -${report.totalExpenses.toLocaleString()}
                </Text>
              </View>
              <View className="h-2 bg-error/20 rounded-full overflow-hidden">
                <View
                  className="h-full bg-error rounded-full"
                  style={{ width: `${(report.totalExpenses / report.totalIncome) * 100}%` }}
                />
              </View>
            </View>

            <View className="h-px bg-border" />

            <View className="flex-row justify-between">
              <Text className="text-foreground font-semibold text-lg">Net Savings</Text>
              <Text className={`font-bold text-2xl ${getSavingsColor(report.savingsRate)}`}>
                ${report.netSavings.toLocaleString()}
              </Text>
            </View>

            <View className="flex-row justify-between">
              <Text className="text-muted">Savings Rate</Text>
              <Text className={`font-bold text-xl ${getSavingsColor(report.savingsRate)}`}>
                {report.savingsRate.toFixed(1)}%
              </Text>
            </View>
          </View>
        </View>

        {/* Expense Breakdown */}
        <View className="bg-surface rounded-xl p-6 mb-6 border border-border">
          <Text className="text-foreground font-bold text-lg mb-4">Expense Breakdown</Text>
          
          <View className="gap-4">
            {expenseBreakdown.map((cat, index) => (
              <View key={index}>
                <View className="flex-row justify-between mb-2">
                  <Text className="text-foreground font-semibold">{cat.category}</Text>
                  <Text className="text-muted">
                    ${cat.amount.toLocaleString()} ({cat.percentage}%)
                  </Text>
                </View>
                <View className="h-2 bg-primary/20 rounded-full overflow-hidden">
                  <View
                    className="h-full bg-primary rounded-full"
                    style={{ width: `${cat.percentage}%` }}
                  />
                </View>
              </View>
            ))}
          </View>
        </View>

        {/* Insights */}
        <View className="bg-primary/5 rounded-xl p-5 mb-6 border border-primary/20">
          <Text className="text-foreground font-bold text-lg mb-3">💡 Insights</Text>
          <View className="gap-2">
            {report.savingsRate >= 30 && (
              <Text className="text-foreground leading-relaxed">
                • Excellent! You're saving {report.savingsRate.toFixed(1)}% of your income.
              </Text>
            )}
            {report.savingsRate < 30 && report.savingsRate >= 15 && (
              <Text className="text-foreground leading-relaxed">
                • Good job! Consider increasing your savings rate to 30% or more.
              </Text>
            )}
            {report.savingsRate < 15 && (
              <Text className="text-foreground leading-relaxed">
                • Your savings rate is below 15%. Review your expenses to find areas to cut back.
              </Text>
            )}
            <Text className="text-foreground leading-relaxed">
              • Your largest expense category is {expenseBreakdown[0].category} at {expenseBreakdown[0].percentage}%.
            </Text>
          </View>
        </View>

        {/* Export Button */}
        <TouchableOpacity
          onPress={exportReport}
          className="bg-primary rounded-xl p-4 mb-6"
          style={{ opacity: 1 }}
        >
          <Text className="text-white text-center font-semibold text-lg">Export Report</Text>
        </TouchableOpacity>
      </ScrollView>
    </ScreenContainer>
  );
}
