import { View, Text, ScrollView, TouchableOpacity, Alert } from 'react-native';
import { Stack, useRouter } from 'expo-router';
import { useState, useEffect } from 'react';
import { ScreenContainer } from '@/components/screen-container';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Haptics from 'expo-haptics';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';

interface FinancialReport {
  id: string;
  period: string;
  type: 'monthly' | 'quarterly' | 'yearly';
  startDate: string;
  endDate: string;
  totalIncome: number;
  totalExpenses: number;
  netSavings: number;
  savingsRate: number;
  generatedAt: string;
}

export default function FinancialReportsScreen() {
  const router = useRouter();
  const [reports, setReports] = useState<FinancialReport[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);

  useEffect(() => {
    loadReports();
  }, []);

  const loadReports = async () => {
    try {
      const stored = await AsyncStorage.getItem('financialReports');
      if (stored) {
        setReports(JSON.parse(stored));
      } else {
        // Sample reports
        const sampleReports: FinancialReport[] = [
          {
            id: '1',
            period: 'January 2026',
            type: 'monthly',
            startDate: '2026-01-01',
            endDate: '2026-01-31',
            totalIncome: 5000,
            totalExpenses: 3500,
            netSavings: 1500,
            savingsRate: 30,
            generatedAt: new Date().toISOString(),
          },
          {
            id: '2',
            period: 'Q4 2025',
            type: 'quarterly',
            startDate: '2025-10-01',
            endDate: '2025-12-31',
            totalIncome: 15000,
            totalExpenses: 11000,
            netSavings: 4000,
            savingsRate: 26.7,
            generatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
          },
        ];
        await AsyncStorage.setItem('financialReports', JSON.stringify(sampleReports));
        setReports(sampleReports);
      }
    } catch (error) {
      console.error('Failed to load reports:', error);
    }
  };

  const generateReport = async (type: 'monthly' | 'quarterly' | 'yearly') => {
    setIsGenerating(true);
    await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);

    try {
      // Calculate date range based on type
      const endDate = new Date();
      const startDate = new Date();

      if (type === 'monthly') {
        startDate.setMonth(startDate.getMonth() - 1);
      } else if (type === 'quarterly') {
        startDate.setMonth(startDate.getMonth() - 3);
      } else {
        startDate.setFullYear(startDate.getFullYear() - 1);
      }

      // Mock data - in real app, fetch from backend
      const totalIncome = Math.floor(Math.random() * 10000) + 5000;
      const totalExpenses = Math.floor(Math.random() * 7000) + 3000;
      const netSavings = totalIncome - totalExpenses;
      const savingsRate = (netSavings / totalIncome) * 100;

      const newReport: FinancialReport = {
        id: Date.now().toString(),
        period: type === 'monthly' ? endDate.toLocaleString('en-US', { month: 'long', year: 'numeric' })
          : type === 'quarterly' ? `Q${Math.ceil((endDate.getMonth() + 1) / 3)} ${endDate.getFullYear()}`
          : endDate.getFullYear().toString(),
        type,
        startDate: startDate.toISOString(),
        endDate: endDate.toISOString(),
        totalIncome,
        totalExpenses,
        netSavings,
        savingsRate,
        generatedAt: new Date().toISOString(),
      };

      const updated = [newReport, ...reports];
      await AsyncStorage.setItem('financialReports', JSON.stringify(updated));
      setReports(updated);

      await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      Alert.alert('Success', 'Report generated successfully!');
    } catch (error) {
      console.error('Failed to generate report:', error);
      Alert.alert('Error', 'Failed to generate report');
    } finally {
      setIsGenerating(false);
    }
  };

  const exportToPDF = async (report: FinancialReport) => {
    try {
      await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);

      // Generate PDF content
      const pdfContent = `
Financial Report - ${report.period}
Generated on ${new Date(report.generatedAt).toLocaleDateString()}

Period: ${new Date(report.startDate).toLocaleDateString()} - ${new Date(report.endDate).toLocaleDateString()}

INCOME & EXPENSES
Total Income:     $${report.totalIncome.toLocaleString()}
Total Expenses:   $${report.totalExpenses.toLocaleString()}
Net Savings:      $${report.netSavings.toLocaleString()}
Savings Rate:     ${report.savingsRate.toFixed(1)}%

This report was generated by your African Fintech Mobile App.
      `.trim();

      const fileName = `financial-report-${report.period.replace(/\s+/g, '-')}.txt`;
      const fileUri = `${FileSystem.documentDirectory}${fileName}`;

      await FileSystem.writeAsStringAsync(fileUri, pdfContent, {
        encoding: FileSystem.EncodingType.UTF8,
      });

      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(fileUri, {
          mimeType: 'text/plain',
          dialogTitle: 'Share Financial Report',
        });
      } else {
        Alert.alert('Success', `Report saved to ${fileUri}`);
      }

      await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
    } catch (error) {
      console.error('Failed to export PDF:', error);
      Alert.alert('Error', 'Failed to export report');
    }
  };

  const getSavingsColor = (rate: number) => {
    if (rate >= 30) return 'text-success';
    if (rate >= 15) return 'text-warning';
    return 'text-error';
  };

  return (
    <ScreenContainer className="p-4">
      <Stack.Screen options={{ title: 'Financial Reports', headerShown: true }} />

      <ScrollView showsVerticalScrollIndicator={false}>
        {/* Header */}
        <View className="mb-6">
          <Text className="text-foreground font-bold text-3xl mb-2">Financial Reports</Text>
          <Text className="text-muted">Track your financial performance</Text>
        </View>

        {/* Generate Report Buttons */}
        <View className="mb-6">
          <Text className="text-foreground font-semibold text-lg mb-3">Generate New Report</Text>
          <View className="flex-row flex-wrap gap-3">
            <TouchableOpacity
              onPress={() => generateReport('monthly')}
              disabled={isGenerating}
              className="flex-1 min-w-[30%] bg-primary rounded-xl p-4"
              style={{ opacity: isGenerating ? 0.5 : 1 }}
            >
              <Text className="text-white text-center font-semibold">Monthly</Text>
            </TouchableOpacity>
            <TouchableOpacity
              onPress={() => generateReport('quarterly')}
              disabled={isGenerating}
              className="flex-1 min-w-[30%] bg-primary rounded-xl p-4"
              style={{ opacity: isGenerating ? 0.5 : 1 }}
            >
              <Text className="text-white text-center font-semibold">Quarterly</Text>
            </TouchableOpacity>
            <TouchableOpacity
              onPress={() => generateReport('yearly')}
              disabled={isGenerating}
              className="flex-1 min-w-[30%] bg-primary rounded-xl p-4"
              style={{ opacity: isGenerating ? 0.5 : 1 }}
            >
              <Text className="text-white text-center font-semibold">Yearly</Text>
            </TouchableOpacity>
          </View>
        </View>

        {/* Reports List */}
        <View>
          <Text className="text-foreground font-semibold text-lg mb-4">Your Reports</Text>
          {reports.map(report => (
            <View
              key={report.id}
              className="bg-surface rounded-xl p-5 mb-4 border border-border"
            >
              {/* Header */}
              <View className="flex-row justify-between items-start mb-4">
                <View className="flex-1">
                  <Text className="text-foreground font-bold text-xl mb-1">
                    {report.period}
                  </Text>
                  <View className="bg-primary/20 px-3 py-1 rounded-full self-start">
                    <Text className="text-primary text-xs font-semibold uppercase">
                      {report.type}
                    </Text>
                  </View>
                </View>
                <Text className="text-muted text-sm">
                  {new Date(report.generatedAt).toLocaleDateString()}
                </Text>
              </View>

              {/* Stats */}
              <View className="gap-3 mb-4">
                <View className="flex-row justify-between">
                  <Text className="text-muted">Total Income</Text>
                  <Text className="text-success font-semibold text-lg">
                    +${report.totalIncome.toLocaleString()}
                  </Text>
                </View>
                <View className="flex-row justify-between">
                  <Text className="text-muted">Total Expenses</Text>
                  <Text className="text-error font-semibold text-lg">
                    -${report.totalExpenses.toLocaleString()}
                  </Text>
                </View>
                <View className="h-px bg-border" />
                <View className="flex-row justify-between">
                  <Text className="text-foreground font-semibold">Net Savings</Text>
                  <Text className={`font-bold text-xl ${getSavingsColor(report.savingsRate)}`}>
                    ${report.netSavings.toLocaleString()}
                  </Text>
                </View>
                <View className="flex-row justify-between">
                  <Text className="text-muted">Savings Rate</Text>
                  <Text className={`font-semibold ${getSavingsColor(report.savingsRate)}`}>
                    {report.savingsRate.toFixed(1)}%
                  </Text>
                </View>
              </View>

              {/* Actions */}
              <View className="flex-row gap-3">
                <TouchableOpacity
                  onPress={() => router.push(`/(reports)/${report.id}` as any)}
                  className="flex-1 bg-primary/10 border border-primary/30 rounded-lg p-3"
                  style={{ opacity: 1 }}
                >
                  <Text className="text-primary text-center font-semibold">View Details</Text>
                </TouchableOpacity>
                <TouchableOpacity
                  onPress={() => exportToPDF(report)}
                  className="flex-1 bg-surface border border-border rounded-lg p-3"
                  style={{ opacity: 1 }}
                >
                  <Text className="text-foreground text-center font-semibold">Export PDF</Text>
                </TouchableOpacity>
              </View>
            </View>
          ))}

          {reports.length === 0 && (
            <View className="bg-surface rounded-xl p-12 items-center border border-border">
              <Text className="text-6xl mb-4">📊</Text>
              <Text className="text-foreground font-semibold text-lg mb-2">
                No Reports Yet
              </Text>
              <Text className="text-muted text-center">
                Generate your first financial report to track your progress
              </Text>
            </View>
          )}
        </View>
      </ScrollView>
    </ScreenContainer>
  );
}
