package rules

import (
	"context"
	"regexp"
	"time"

	"github.com/google/uuid"
	"github.com/insurance-platform/insurance-radar/internal/models"
	"go.uber.org/zap"
)

// RulesEngine manages fraud detection rules
// Inspired by Stripe Radar's dynamic, AI-generated rules
type RulesEngine struct {
	rules       map[string]*Rule
	ruleGroups  map[string]*RuleGroup
	aiRules     []*AIGeneratedRule
	logger      *zap.Logger
}

// Rule represents a fraud detection rule
type Rule struct {
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	Description string            `json:"description"`
	Type        RuleType          `json:"type"`
	Conditions  []RuleCondition   `json:"conditions"`
	Action      RuleAction        `json:"action"`
	Severity    string            `json:"severity"`
	Enabled     bool              `json:"enabled"`
	Priority    int               `json:"priority"`
	CreatedAt   time.Time         `json:"created_at"`
	UpdatedAt   time.Time         `json:"updated_at"`
	Metadata    map[string]string `json:"metadata"`
}

// RuleType represents the type of rule
type RuleType string

const (
	RuleTypeStatic    RuleType = "static"
	RuleTypeDynamic   RuleType = "dynamic"
	RuleTypeAI        RuleType = "ai_generated"
	RuleTypeVelocity  RuleType = "velocity"
	RuleTypeBlacklist RuleType = "blacklist"
	RuleTypeWhitelist RuleType = "whitelist"
)

// RuleCondition represents a condition in a rule
type RuleCondition struct {
	Field    string      `json:"field"`
	Operator string      `json:"operator"`
	Value    interface{} `json:"value"`
	Logic    string      `json:"logic"` // AND, OR
}

// RuleAction represents the action to take when a rule matches
type RuleAction string

const (
	RuleActionBlock   RuleAction = "block"
	RuleActionReview  RuleAction = "review"
	RuleActionFlag    RuleAction = "flag"
	RuleActionAllow   RuleAction = "allow"
	RuleActionChallenge RuleAction = "challenge"
)

// RuleGroup represents a group of related rules
type RuleGroup struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	RuleIDs     []string `json:"rule_ids"`
	Enabled     bool     `json:"enabled"`
}

// AIGeneratedRule represents a rule generated by AI
type AIGeneratedRule struct {
	Rule
	GeneratedAt    time.Time `json:"generated_at"`
	ModelVersion   string    `json:"model_version"`
	Confidence     float64   `json:"confidence"`
	PerformanceMetrics struct {
		Precision float64 `json:"precision"`
		Recall    float64 `json:"recall"`
		F1Score   float64 `json:"f1_score"`
	} `json:"performance_metrics"`
}

// RuleEvaluationResult represents the result of rule evaluation
type RuleEvaluationResult struct {
	RuleID      string     `json:"rule_id"`
	RuleName    string     `json:"rule_name"`
	Matched     bool       `json:"matched"`
	Action      RuleAction `json:"action"`
	Severity    string     `json:"severity"`
	Description string     `json:"description"`
	MatchedAt   time.Time  `json:"matched_at"`
}

// NewRulesEngine creates a new rules engine
func NewRulesEngine(logger *zap.Logger) *RulesEngine {
	engine := &RulesEngine{
		rules:      make(map[string]*Rule),
		ruleGroups: make(map[string]*RuleGroup),
		aiRules:    make([]*AIGeneratedRule, 0),
		logger:     logger,
	}

	// Initialize default rules
	engine.initializeDefaultRules()

	return engine
}

// initializeDefaultRules sets up default fraud detection rules
func (re *RulesEngine) initializeDefaultRules() {
	// High-risk country rule
	re.AddRule(&Rule{
		ID:          "rule_high_risk_country",
		Name:        "High Risk Country",
		Description: "Block transactions from high-risk countries",
		Type:        RuleTypeStatic,
		Conditions: []RuleCondition{
			{Field: "location_country_code", Operator: "in", Value: []string{"XX", "YY"}, Logic: "AND"},
		},
		Action:   RuleActionReview,
		Severity: "high",
		Enabled:  true,
		Priority: 100,
	})

	// VPN/Proxy detection rule
	re.AddRule(&Rule{
		ID:          "rule_vpn_proxy",
		Name:        "VPN/Proxy Detection",
		Description: "Flag transactions using VPN or proxy",
		Type:        RuleTypeStatic,
		Conditions: []RuleCondition{
			{Field: "location_is_vpn", Operator: "eq", Value: true, Logic: "OR"},
			{Field: "location_is_proxy", Operator: "eq", Value: true, Logic: "OR"},
			{Field: "location_is_tor", Operator: "eq", Value: true, Logic: "OR"},
		},
		Action:   RuleActionFlag,
		Severity: "medium",
		Enabled:  true,
		Priority: 90,
	})

	// High amount claim rule
	re.AddRule(&Rule{
		ID:          "rule_high_amount_claim",
		Name:        "High Amount Claim",
		Description: "Review claims above threshold",
		Type:        RuleTypeStatic,
		Conditions: []RuleCondition{
			{Field: "fraud_type", Operator: "eq", Value: "claim", Logic: "AND"},
			{Field: "amount", Operator: "gt", Value: 1000000.0, Logic: "AND"},
		},
		Action:   RuleActionReview,
		Severity: "high",
		Enabled:  true,
		Priority: 95,
	})

	// New policy with immediate claim rule
	re.AddRule(&Rule{
		ID:          "rule_new_policy_immediate_claim",
		Name:        "New Policy Immediate Claim",
		Description: "Flag claims on policies less than 30 days old",
		Type:        RuleTypeStatic,
		Conditions: []RuleCondition{
			{Field: "fraud_type", Operator: "eq", Value: "claim", Logic: "AND"},
			{Field: "policy_age_days", Operator: "lt", Value: 30, Logic: "AND"},
		},
		Action:   RuleActionReview,
		Severity: "high",
		Enabled:  true,
		Priority: 92,
	})

	// Velocity rule - multiple claims
	re.AddRule(&Rule{
		ID:          "rule_velocity_claims",
		Name:        "Multiple Claims Velocity",
		Description: "Flag customers with multiple claims in short period",
		Type:        RuleTypeVelocity,
		Conditions: []RuleCondition{
			{Field: "claims_last_month", Operator: "gt", Value: 3, Logic: "AND"},
		},
		Action:   RuleActionReview,
		Severity: "high",
		Enabled:  true,
		Priority: 88,
	})

	// Night time transaction rule
	re.AddRule(&Rule{
		ID:          "rule_night_time",
		Name:        "Night Time Transaction",
		Description: "Flag transactions during unusual hours",
		Type:        RuleTypeStatic,
		Conditions: []RuleCondition{
			{Field: "behavior_is_night_time", Operator: "eq", Value: true, Logic: "AND"},
			{Field: "amount", Operator: "gt", Value: 500000.0, Logic: "AND"},
		},
		Action:   RuleActionFlag,
		Severity: "medium",
		Enabled:  true,
		Priority: 70,
	})

	// Device fingerprint mismatch rule
	re.AddRule(&Rule{
		ID:          "rule_device_mismatch",
		Name:        "Device Fingerprint Mismatch",
		Description: "Flag when device fingerprint doesn't match history",
		Type:        RuleTypeStatic,
		Conditions: []RuleCondition{
			{Field: "device_fingerprint_mismatch", Operator: "eq", Value: true, Logic: "AND"},
		},
		Action:   RuleActionFlag,
		Severity: "medium",
		Enabled:  true,
		Priority: 75,
	})

	// Agent fraud pattern rule
	re.AddRule(&Rule{
		ID:          "rule_agent_fraud_pattern",
		Name:        "Agent Fraud Pattern",
		Description: "Flag agents with suspicious claim patterns",
		Type:        RuleTypeStatic,
		Conditions: []RuleCondition{
			{Field: "agent_fraud_rate", Operator: "gt", Value: 0.1, Logic: "AND"},
		},
		Action:   RuleActionReview,
		Severity: "high",
		Enabled:  true,
		Priority: 85,
	})

	// Document tampering rule
	re.AddRule(&Rule{
		ID:          "rule_document_tampering",
		Name:        "Document Tampering Detected",
		Description: "Block when document tampering is detected",
		Type:        RuleTypeStatic,
		Conditions: []RuleCondition{
			{Field: "document_modification_detected", Operator: "eq", Value: true, Logic: "AND"},
		},
		Action:   RuleActionBlock,
		Severity: "critical",
		Enabled:  true,
		Priority: 100,
	})

	// Network fraud signal rule
	re.AddRule(&Rule{
		ID:          "rule_network_fraud",
		Name:        "Network Fraud Signal",
		Description: "Block when entity is flagged in cross-company fraud database",
		Type:        RuleTypeBlacklist,
		Conditions: []RuleCondition{
			{Field: "network_blacklist_match", Operator: "eq", Value: true, Logic: "AND"},
		},
		Action:   RuleActionBlock,
		Severity: "critical",
		Enabled:  true,
		Priority: 100,
	})
}

// AddRule adds a rule to the engine
func (re *RulesEngine) AddRule(rule *Rule) {
	rule.CreatedAt = time.Now()
	rule.UpdatedAt = time.Now()
	re.rules[rule.ID] = rule
	re.logger.Info("Rule added", zap.String("rule_id", rule.ID), zap.String("rule_name", rule.Name))
}

// RemoveRule removes a rule from the engine
func (re *RulesEngine) RemoveRule(ruleID string) {
	delete(re.rules, ruleID)
	re.logger.Info("Rule removed", zap.String("rule_id", ruleID))
}

// EnableRule enables a rule
func (re *RulesEngine) EnableRule(ruleID string) {
	if rule, ok := re.rules[ruleID]; ok {
		rule.Enabled = true
		rule.UpdatedAt = time.Now()
	}
}

// DisableRule disables a rule
func (re *RulesEngine) DisableRule(ruleID string) {
	if rule, ok := re.rules[ruleID]; ok {
		rule.Enabled = false
		rule.UpdatedAt = time.Now()
	}
}

// EvaluateRules evaluates all rules against the feature vector
func (re *RulesEngine) EvaluateRules(ctx context.Context, features map[string]float64) []RuleEvaluationResult {
	var results []RuleEvaluationResult

	for _, rule := range re.rules {
		if !rule.Enabled {
			continue
		}

		if re.evaluateRule(rule, features) {
			results = append(results, RuleEvaluationResult{
				RuleID:      rule.ID,
				RuleName:    rule.Name,
				Matched:     true,
				Action:      rule.Action,
				Severity:    rule.Severity,
				Description: rule.Description,
				MatchedAt:   time.Now(),
			})
		}
	}

	// Evaluate AI-generated rules
	for _, aiRule := range re.aiRules {
		if !aiRule.Enabled {
			continue
		}

		if re.evaluateRule(&aiRule.Rule, features) {
			results = append(results, RuleEvaluationResult{
				RuleID:      aiRule.ID,
				RuleName:    aiRule.Name,
				Matched:     true,
				Action:      aiRule.Action,
				Severity:    aiRule.Severity,
				Description: aiRule.Description,
				MatchedAt:   time.Now(),
			})
		}
	}

	return results
}

// evaluateRule evaluates a single rule
func (re *RulesEngine) evaluateRule(rule *Rule, features map[string]float64) bool {
	if len(rule.Conditions) == 0 {
		return false
	}

	// Evaluate conditions with AND/OR logic
	result := true
	for i, condition := range rule.Conditions {
		conditionResult := re.evaluateCondition(condition, features)

		if i == 0 {
			result = conditionResult
		} else {
			switch condition.Logic {
			case "AND":
				result = result && conditionResult
			case "OR":
				result = result || conditionResult
			default:
				result = result && conditionResult
			}
		}
	}

	return result
}

// evaluateCondition evaluates a single condition
func (re *RulesEngine) evaluateCondition(condition RuleCondition, features map[string]float64) bool {
	featureValue, exists := features[condition.Field]
	if !exists {
		return false
	}

	switch condition.Operator {
	case "eq":
		return re.compareEqual(featureValue, condition.Value)
	case "ne":
		return !re.compareEqual(featureValue, condition.Value)
	case "gt":
		return re.compareGreater(featureValue, condition.Value)
	case "gte":
		return re.compareGreaterOrEqual(featureValue, condition.Value)
	case "lt":
		return re.compareLess(featureValue, condition.Value)
	case "lte":
		return re.compareLessOrEqual(featureValue, condition.Value)
	case "in":
		return re.compareIn(featureValue, condition.Value)
	case "regex":
		return re.compareRegex(featureValue, condition.Value)
	default:
		return false
	}
}

func (re *RulesEngine) compareEqual(a float64, b interface{}) bool {
	switch v := b.(type) {
	case float64:
		return a == v
	case int:
		return a == float64(v)
	case bool:
		return (a == 1.0) == v
	default:
		return false
	}
}

func (re *RulesEngine) compareGreater(a float64, b interface{}) bool {
	switch v := b.(type) {
	case float64:
		return a > v
	case int:
		return a > float64(v)
	default:
		return false
	}
}

func (re *RulesEngine) compareGreaterOrEqual(a float64, b interface{}) bool {
	switch v := b.(type) {
	case float64:
		return a >= v
	case int:
		return a >= float64(v)
	default:
		return false
	}
}

func (re *RulesEngine) compareLess(a float64, b interface{}) bool {
	switch v := b.(type) {
	case float64:
		return a < v
	case int:
		return a < float64(v)
	default:
		return false
	}
}

func (re *RulesEngine) compareLessOrEqual(a float64, b interface{}) bool {
	switch v := b.(type) {
	case float64:
		return a <= v
	case int:
		return a <= float64(v)
	default:
		return false
	}
}

func (re *RulesEngine) compareIn(a float64, b interface{}) bool {
	switch v := b.(type) {
	case []float64:
		for _, val := range v {
			if a == val {
				return true
			}
		}
	case []int:
		for _, val := range v {
			if a == float64(val) {
				return true
			}
		}
	}
	return false
}

func (re *RulesEngine) compareRegex(a float64, b interface{}) bool {
	pattern, ok := b.(string)
	if !ok {
		return false
	}
	matched, _ := regexp.MatchString(pattern, string(rune(int(a))))
	return matched
}

// AddAIGeneratedRule adds an AI-generated rule
func (re *RulesEngine) AddAIGeneratedRule(rule *AIGeneratedRule) {
	rule.GeneratedAt = time.Now()
	rule.CreatedAt = time.Now()
	rule.UpdatedAt = time.Now()
	rule.Type = RuleTypeAI
	re.aiRules = append(re.aiRules, rule)
	re.logger.Info("AI-generated rule added",
		zap.String("rule_id", rule.ID),
		zap.Float64("confidence", rule.Confidence))
}

// GetAllRules returns all rules
func (re *RulesEngine) GetAllRules() []*Rule {
	rules := make([]*Rule, 0, len(re.rules))
	for _, rule := range re.rules {
		rules = append(rules, rule)
	}
	return rules
}

// GetRule returns a specific rule
func (re *RulesEngine) GetRule(ruleID string) (*Rule, bool) {
	rule, ok := re.rules[ruleID]
	return rule, ok
}

// GetMatchedRules converts evaluation results to matched rules for response
func (re *RulesEngine) GetMatchedRules(results []RuleEvaluationResult) []models.MatchedRule {
	matched := make([]models.MatchedRule, len(results))
	for i, result := range results {
		matched[i] = models.MatchedRule{
			RuleID:      result.RuleID,
			RuleName:    result.RuleName,
			RuleType:    string(re.rules[result.RuleID].Type),
			Action:      string(result.Action),
			Severity:    result.Severity,
			Description: result.Description,
			MatchedAt:   result.MatchedAt,
		}
	}
	return matched
}
